### ISSUE TITLE
ORA-22835 Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 4907, maximum: 4000)

### ISSUE THREAD

**Issue by DjohanKho** [pljson/pljson#102]
Hi, pljson generated an ORA-22835 error when trying to process JSON string longer than 4000 characters. I wonder if this is the restriction in the Oracle API called by pljson? Our Oracle Database is 11g Enterprise Edition Release 11.2.0.4.0 - 64bit.

**Comment by dsnz** [comment]
Hi,

Please give a specific example of this process you talk about. An example we can run and get an error.

**Comment by DjohanKho** [comment]
1. I create a JSON_DATA() function which called JSON_EXT.GET_STRING to parse the JSON data

CREATE OR REPLACE FUNCTION JSON_DATA(VJSON VARCHAR2, VPARAM VARCHAR2) RETURN VARCHAR2 DETERMINISTIC IS
  V_OBJ   JSON := JSON(VJSON);
  TMP_STR VARCHAR2(100) := '';
BEGIN
  TMP_STR := UNISTR(REPLACE(JSON_EXT.GET_STRING(V_OBJ, VPARAM), '\u', '\'));
  RETURN TMP_STR;
END;
/

2. I call the above function with SQL below:

select json_data(a.data,'entityValue.offerEffectiveType.value'), a.*
from myRegistryData a
where id='2000003495889067'

**Comment by DjohanKho** [comment]
The contents of a.data (NCLOB) in the SQL above is as below:

{"entityValue":{"isDeferable":{"type":"boolean","value":"false"},"offerEffectiveType":{"type":"codeTable","value":"DD"},"offerIneffectiveType":{"type":"codeTable","value":"DD"},"actIgnore":{"type":"boolean","value":"false"},"isQueryBillingPenalty":{"type":"boolean","value":"false"},"isStopMonthlyFee":{"type":"boolean","value":"false"},"additionalProductType":{"type":"codeTable","value":"null"},"autoExtend":{"type":"boolean","value":"false"},"claimStopMonthlyFee":{"type":"string","value":"null"},"discountPriority":{"type":"string","value":"null"},"initialBalance":{"type":"string","value":"null"},"isFirstEvent":{"type":"boolean","value":"false"},"isMain":{"type":"boolean","value":"false"},"l9AgentCode":{"type":"string","value":"null"},"l9FutureExpirationDate":{"type":"string","value":"null"},"l9OrigEffDate":{"type":"string","value":"null"},"migrationSourceOffer":{"type":"string","value":"null"},"offerEffectiveUnit":{"type":"number","value":"null"},"offerExpiredRemove":{"type":"codeTable","value":"null"},"offerTerminateRemove":{"type":"codeTable","value":"null"},"promotionId":{"type":"string","value":"null"},"reasonCode":{"type":"string","value":"null"},"actualDuration":{"type":"string","value":"null"},"suspendDuration":{"type":"string","value":"null"},"chargeCode":{"type":"string","value":"1234567890"},"vasLevel":{"type":"string","value":"199"},"uid":{"type":"string","value":"null"},"useidType":{"type":"string","value":"B"},"bookingId":{"type":"string","value":"null"},"zipcode":{"type":"string","value":"null"},"duration":{"type":"string","value":"null"},"durationUnit":{"type":"string","value":"null"},"prodOffLevel":{"type":"codeTable","value":"C"},"l3GroupType":{"type":"string","value":"XX"},"prodOffType":{"type":"codeTable","value":"YY"},"adjustCode":{"type":"string","value":"null"},"daysLimitation":{"type":"string","value":"null"},"discountAppliedMax":{"type":"string","value":"null"},"discountAppliedMin":{"type":"string","value":"null"},"discountLevel":{"type":"codeTable","value":"null"},"externalName":{"type":"string","value":"null"},"followupDesc":{"type":"string","value":"null"},"groupID":{"type":"string","value":"null"},"isGiven":{"type":"boolean","value":"false"},"isSameOrder":{"type":"boolean","value":"false"},"l4GroupType":{"type":"string","value":"GROUP111"},"offerIdentify":{"type":"codeTable","value":"null"},"partNo":{"type":"string","value":"null"},"cardUpperLimit":{"type":"number","value":"null"},"serviceGroup":{"type":"codeTable","value":"GROUP123"},"vasGroup":{"type":"codeTable","value":"AABBCCDDEE"},"addNewService":{"type":"codeTable","value":"null"},"address":{"type":"string","value":"null"},"agentCode":{"type":"string","value":"null"},"area":{"type":"string","value":"null"},"city":{"type":"string","value":"null"},"contactMobile":{"type":"string","value":"null"},"contactName":{"type":"string","value":"null"},"contactTel":{"type":"string","value":"null"},"contactWorkingTime":{"type":"codeTable","value":"null"},"hasHomeNetwork":{"type":"boolean","value":"null"},"hasWifi":{"type":"boolean","value":"null"},"installTbd":{"type":"boolean","value":"null"},"isRemote":{"type":"boolean","value":"null"},"phoneSpec":{"type":"boolean","value":"null"},"wifiOver50m":{"type":"boolean","value":"null"},"ticketDesc":{"type":"string","value":"null"},"bonusCode":{"type":"string","value":"null"},"ruleSource":{"type":"string","value":"null"},"sequenceno":{"type":"number","value":"1122"},"action":{"type":"string","value":"ACTIVATION"},"customerId":{"type":"object","value":"null"},"accountId":{"type":"object","value":"null"},"family":{"type":"object","value":"null"},"category":{"type":"object","value":"null"},"SiteId":{"type":"object","value":"null"},"serviceRegistryId":{"type":"object","value":"null"},"notes":{"type":"object","value":"null"},"prevstate":{"type":"object","value":"null"},"itemNotes":{"type":"object","value":"null"},"isCompleted":{"type":"object","value":"null"},"description":{"type":"object","value":"null"},"assignedPriority":{"type":"object","value":"null"},"biType":{"type":"object","value":"null"},"biSpecification":{"type":"object","value":"null"},"dueDate":{"type":"object","value":"null"},"completionDate":{"type":"object","value":"null"},"product":{"type":"object","value":"null"},"quantity":{"type":"object","value":"null"},"resources":{"type":"object","value":"null"},"services":{"type":"object","value":"null"},"attrs":{"type":"object","value":"null"},"processMilestones":{"type":"object","value":"null"},"apiRequest":{"type":"object","value":"null"}}}

**Comment by dsnz** [comment]
Hi,

Let me check this when I get on a Oracle database and will reply back.
Until then please tell me the database character sets (everything NLS) and if you used the 'master' or the 'develop' branch of pljson.

**Comment by DjohanKho** [comment]
Hi, 

I'm using the latest 'master' branch of pljson.
SELECT * FROM NLS_DATABASE_PARAMETERS  returns:

NLS_LANGUAGE	AMERICAN
NLS_TERRITORY	AMERICA
NLS_CURRENCY	$
NLS_ISO_CURRENCY	AMERICA
NLS_NUMERIC_CHARACTERS	.,
NLS_CHARACTERSET	AL32UTF8
NLS_CALENDAR	GREGORIAN
NLS_DATE_FORMAT	DD-MON-RR
NLS_DATE_LANGUAGE	AMERICAN
NLS_SORT	BINARY
NLS_TIME_FORMAT	HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT	HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY	$
NLS_COMP	BINARY
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CONV_EXCP	FALSE
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_RDBMS_VERSION	11.2.0.4.0

**Comment by dsnz** [comment]
Hi,

Thank you, but we will check this against the 'develop'branch. The 'master' branch is not active for more than a year and the current active branch is the 'develop' one. Sorry for the confusion. Soon we will make the 'develop' branch the new 'master' one. Please download the 'develop' branch, install it and try again.

**Comment by DjohanKho** [comment]
Hi, 

OK. I'll give it a try and reply back. Thanks a lot for helping.

**Comment by DjohanKho** [comment]
Sorry, I've just tried the 'develop'branch. Same error occurred.

**Comment by dsnz** [comment]
Hello,

Finally I managed to look at your issue and the verdict is that there is no problem at all with pljson.
The problem is in what you ask to do. Let me explain with a few examples below

the following test using a pl/sql string works fine

```
create table a (
id number not null,
data clob not null
);

declare
  str varchar2(32767) :=
  '{"entityValue":{"isDeferable":{"type":"boolean","value":"false"},"offerEffectiveType":{"type":"codeTable","value":"DD"},"offerIneffectiveType":{"type":"codeTable","value":"DD"},"actIgnore":{"type":"boolean","value":"false"},"isQueryBillingPenalty":{"type":"boolean","value":"false"},"isStopMonthlyFee":{"type":"boolean","value":"false"},"additionalProductType":{"type":"codeTable","value":"null"},"autoExtend":{"type":"boolean","value":"false"},"claimStopMonthlyFee":{"type":"string","value":"null"},"discountPriority":{"type":"string","value":"null"},"initialBalance":{"type":"string","value":"null"},"isFirstEvent":{"type":"boolean","value":"false"},"isMain":{"type":"boolean","value":"false"},"l9AgentCode":{"type":"string","value":"null"},"l9FutureExpirationDate":{"type":"string","value":"null"},"l9OrigEffDate":{"type":"string","value":"null"},"migrationSourceOffer":{"type":"string","value":"null"},"offerEffectiveUnit":{"type":"number","value":"null"},"offerExpiredRemove":{"type":"codeTable","value":"null"},"offerTerminateRemove":{"type":"codeTable","value":"null"},"promotionId":{"type":"string","value":"null"},"reasonCode":{"type":"string","value":"null"},"actualDuration":{"type":"string","value":"null"},"suspendDuration":{"type":"string","value":"null"},"chargeCode":{"type":"string","value":"1234567890"},"vasLevel":{"type":"string","value":"199"},"uid":{"type":"string","value":"null"},"useidType":{"type":"string","value":"B"},"bookingId":{"type":"string","value":"null"},"zipcode":{"type":"string","value":"null"},"duration":{"type":"string","value":"null"},"durationUnit":{"type":"string","value":"null"},"prodOffLevel":{"type":"codeTable","value":"C"},"l3GroupType":{"type":"string","value":"XX"},"prodOffType":{"type":"codeTable","value":"YY"},"adjustCode":{"type":"string","value":"null"},"daysLimitation":{"type":"string","value":"null"},"discountAppliedMax":{"type":"string","value":"null"},"discountAppliedMin":{"type":"string","value":"null"},"discountLevel":{"type":"codeTable","value":"null"},"externalName":{"type":"string","value":"null"},"followupDesc":{"type":"string","value":"null"},"groupID":{"type":"string","value":"null"},"isGiven":{"type":"boolean","value":"false"},"isSameOrder":{"type":"boolean","value":"false"},"l4GroupType":{"type":"string","value":"GROUP111"},"offerIdentify":{"type":"codeTable","value":"null"},"partNo":{"type":"string","value":"null"},"cardUpperLimit":{"type":"number","value":"null"},"serviceGroup":{"type":"codeTable","value":"GROUP123"},"vasGroup":{"type":"codeTable","value":"AABBCCDDEE"},"addNewService":{"type":"codeTable","value":"null"},"address":{"type":"string","value":"null"},"agentCode":{"type":"string","value":"null"},"area":{"type":"string","value":"null"},"city":{"type":"string","value":"null"},"contactMobile":{"type":"string","value":"null"},"contactName":{"type":"string","value":"null"},"contactTel":{"type":"string","value":"null"},"contactWorkingTime":{"type":"codeTable","value":"null"},"hasHomeNetwork":{"type":"boolean","value":"null"},"hasWifi":{"type":"boolean","value":"null"},"installTbd":{"type":"boolean","value":"null"},"isRemote":{"type":"boolean","value":"null"},"phoneSpec":{"type":"boolean","value":"null"},"wifiOver50m":{"type":"boolean","value":"null"},"ticketDesc":{"type":"string","value":"null"},"bonusCode":{"type":"string","value":"null"},"ruleSource":{"type":"string","value":"null"},"sequenceno":{"type":"number","value":"1122"},"action":{"type":"string","value":"ACTIVATION"},"customerId":{"type":"object","value":"null"},"accountId":{"type":"object","value":"null"},"family":{"type":"object","value":"null"},"category":{"type":"object","value":"null"},"SiteId":{"type":"object","value":"null"},"serviceRegistryId":{"type":"object","value":"null"},"notes":{"type":"object","value":"null"},"prevstate":{"type":"object","value":"null"},"itemNotes":{"type":"object","value":"null"},"isCompleted":{"type":"object","value":"null"},"description":{"type":"object","value":"null"},"assignedPriority":{"type":"object","value":"null"},"biType":{"type":"object","value":"null"},"biSpecification":{"type":"object","value":"null"},"dueDate":{"type":"object","value":"null"},"completionDate":{"type":"object","value":"null"},"product":{"type":"object","value":"null"},"quantity":{"type":"object","value":"null"},"resources":{"type":"object","value":"null"},"services":{"type":"object","value":"null"},"attrs":{"type":"object","value":"null"},"processMilestones":{"type":"object","value":"null"},"apiRequest":{"type":"object","value":"null"}}}';
  res varchar2(100);
begin
  insert into a values(1, str);
  res := pljson_ext.GET_STRING(pljson(str), 'entityValue.offerEffectiveType.value');
  dbms_output.put_line(res);
end;
```

remember that pl/sql varchar2 strings are able to hold 32767 bytes !

the following sql statement calling pl_json_ext(pljson(..., ...)) works fine too

```
select pljson_ext.get_string(pljson(a.data), 'entityValue.offerEffectiveType.value')
from a
where id = 1
/
```

however using this json_data function

```
CREATE OR REPLACE FUNCTION JSON_DATA(VJSON VARCHAR2, VPARAM VARCHAR2) RETURN VARCHAR2 DETERMINISTIC IS
V_OBJ JSON := JSON(VJSON);
TMP_STR VARCHAR2(100) := '';
BEGIN
TMP_STR := 'aa'; --UNISTR(REPLACE(JSON_EXT.GET_STRING(V_OBJ, VPARAM), '\u', ''));
RETURN TMP_STR;
END;
```

we get error

ORA-22835: Buffer too small for CLOB to CHAR or BLOB to RAW conversion (actual: 4542, maximum: 4000)

note that this function uses no pljson_ext but only the pljson(...) type call

I think you begin to understand what happens,
and it will be more obvious if you use the following json_data() function

```
CREATE OR REPLACE FUNCTION JSON_DATA(VJSON CLOB, VPARAM VARCHAR2) RETURN VARCHAR2 DETERMINISTIC IS
V_OBJ JSON := JSON(VJSON);
TMP_STR VARCHAR2(100) := '';
BEGIN
TMP_STR := UNISTR(REPLACE(JSON_EXT.GET_STRING(V_OBJ, VPARAM), '\u', ''));
RETURN TMP_STR;
END;
```

which works fine without errors
and has declared the first parameter as CLOB rather than VARCHAR2

what happened with your original function is that by declaring the first parameter as VARCHAR2
Oracle uses the pljson(...) constructor with varchar2 parameter and tries to convert your clob data
into varchar2 which is not possible because of its size

by a simple change to clob parameter - which is also the type of your table data - everything is fine

**Comment by DjohanKho** [comment]
Wow, thank you so much for the highlight. I never thought to look in that direction.
BTW, can I buy you a coffee? :-D

**Comment by dsnz** [comment]
Thank you !
I hope to visit Taiwan some day :)

**Comment by DjohanKho** [comment]
You are always welcome ! :)
