### ISSUE TITLE
Using json_list  insert to clob fail.

### ISSUE THREAD

**Issue by NicoFang** [pljson/pljson#103]
Hi,

Using json_list from tableA  into tableB clob column,is fail.
TOAD POP ERROR MSG:wrong number or types of arguments in call to 'TO_CLOB'.

--My source code
declare
 ret_list  json_list;
 v_sql varchar2(500) := 'select * from TableA where rownum<10';
 v_clob clob; 
begin
  --v_clob :=ret_list.to_char(); --It's work.
  v_clob :=ret_list.to_clob(); --It's fail.
 
  insert into TableB(USER_NAME,CLOB1) VALUES (99999,v_clob);

end;

--print v_sql like this:
[{
"ITEM_ID" : 541430,
"SEQ" : "1.1",
"LINE_ID" : 2169384,
"AREA" : "CW"
}, {
"ITEM_ID" : 541467,
"SEQ" : "1.1",
"LINE_ID" : 2169454,
"AREA" : "CW"
}]

**Comment by boriborm** [comment]
to_clob is not a function. It is a procedure.
Use:
Obj.to_clob(v_clob);

But you need initialize and free v_clob before and after use with procedure to_clob. 
See dbms_lob package documentation.

Other solution is insert into table record with use empty_clob function for clob field value, select field into v_clob, use to_clob(v_clob) and update record with set clob field = v_clob.

**Comment by NicoFang** [comment]
Hi,
It's work.
thanks a lot.
-----------------------------------------------
declare
  obj json_list;
  my_clob clob := '[{
"ITEM_ID" : 541430,
"SEQ" : "1.1",
"LINE_ID" : 2169384,
"AREA" : "CW"
}]';
  
begin
  obj := json_list(my_clob);
  dbms_lob.trim(my_clob, 0); --empty the lob
  obj.to_clob(my_clob);
  dbms_output.put_line(my_clob);
  my_clob := empty_clob();
  dbms_lob.createtemporary(my_clob, true);
  obj.to_clob(my_clob, true);
  insert into tableB(CLOB1) VALUES (my_clob);
  dbms_lob.freetemporary(my_clob);
end;
