### ISSUE TITLE
sql_to_json doesn't work if numeric values are less than 1

### ISSUE THREAD

**Issue by stepanz** [pljson/pljson#107]
Hi,

I have a problem with pljson_util_pkg.sql_to_json:

declare 
  -- Local variables here
  tstjson_list pljson_list;
  l_Result_json_clob clob;
begin
  -- Test statements here
  tstjson_list := pljson_list();
  dbms_lob.createtemporary(l_Result_json_clob, true);

  tstjson_list := pljson_util_pkg.sql_to_json('SELECT 0.1 as tmp from dual');
  tstjson_list.to_clob(l_Result_json_clob);
end;

When I execute this code I am getting error message: Scanner problem with the following input: {"ROWSET":{"ROW":{"TMP":.1}}}

It looks like that if query returns numeric value less than 1, then this error occurs because instead of 0.1 the result is .1! Any idea why?

Thank you, Zoran

**Comment by dsnz** [comment]
Hello,

it's all to Oracle returning by default results without leading 0

if you try inside sqlplus

select 0.1 as tmp from dual
/

the result will be .1

The correct way in an application (which should also be independent from database nls parameters) is to use the TO_CHAR function with an appropriate NUMBER FORMAT string
in your case I chose a variable length format with up to 15 decimal digits (you can adjust this yourself)
and with this change the following works fine

```
declare
  -- Local variables here
  tstjson_list pljson_list;
  l_Result_json_clob clob;
begin
  -- Test statements here
  tstjson_list := pljson_list();
  dbms_lob.createtemporary(l_Result_json_clob, true);
  
  tstjson_list := pljson_util_pkg.sql_to_json('select to_char(0.1234, ''FM0.999999999999999'') as tmp from dual');
  tstjson_list.to_clob(l_Result_json_clob);
  dbms_output.put_line(l_Result_json_clob);
end;
```
