### ISSUE TITLE
assign json > 32767 characters to a clob variable

### ISSUE THREAD

**Issue by dtstuff9** [pljson/pljson#108]
```
declare
 obj json_List;
 my_clob clob;
begin
obj := json_dyn.executeList('select * from table);
obj.print; --prints 50000 characters fine
my_clob := json_printer.pretty_print_list(obj); --fails - character string buffer too small
end;
```

How do I convert obj to a clob so I can assign it to my_clob?

I would run 
`my_clob := json_printer.pretty_print_list(obj);`
but that only works if the json is less than 32767 characters.

Thanks

**Comment by jsumners** [comment]
Use the `.to_clob` method.

**Comment by dsnz** [comment]
yes,
.to_clob() calls the pretty_print_list procedure which fills a clob
or you can do directly as in the example below which I have tested

```
declare
 obj pljson_List;
 my_clob clob;
begin
  obj := pljson_dyn.executeList('select * from user_objects');
  obj.print; --prints 50000 characters fine
  dbms_lob.createtemporary(my_clob, false);
  pljson_printer.pretty_print_list(obj, false, my_clob);
  dbms_output.put_line(dbms_lob.getlength(my_clob));
end;
```

you should download and use the updated version of pljson in the develop branch

**Comment by dtstuff9** [comment]
Thank you very much. This API is a godsend for those of us still on 11g.
