### ISSUE TITLE
Agregar una cadena larga de tipo clob con put

### ISSUE THREAD

**Issue by little-programming** [pljson/pljson#115]
Hola, estoy tratando de agregar una cadena de aprox. 410 KB usando la funcion obj.put de pl json, pero Oracle me envía un error de tipo "ORA-06502: PL/SQL: error  numérico o de valor ORA-06512: en "APP.API_CADENAS_1_0", línea 483 ORA-06512: en "APP.CADENAS_1_0", línea 565."
Esto es lo que tengo en la línea 483
/***Códifo pl sql ***/

obj.put('xml',varxml);

/**/

En la línea 565 solo retorno a la función.
Al parecer el método put no puede agregar cadenas demasiadas largas. ¿Qué configuración debo hacer, o que debo cambiar para que dicho método me pueda agregar la cadena que necesito?

Les agradezco mucho su ayuda. 
--saludos

**Comment by dsnz** [comment]
```
varxml clob;

obj.put('xml', pljson_value(varxml));
```

**Comment by little-programming** [comment]
Hola dsnz.
Estoy probando con el código que publicaste, pero me manda los siguientes errores:

Error(534,9): PL/SQL: Statement ignored
Error(534,25): PLS-00201: identifier 'PLJSON_VALUE' must be declared

"ORA-06502: PL/SQL: error : character string buffer too small numerico o de valor ORA-06512: en "APP.JSON_PRINTER", linea 47 ORA-06512: en "APP.JSON_PRINTER", linea 201 ORA-06512: en "APP.JSON_PRINTER", linea 238 ORA-06512: en "APP.JSON_PRINTER", linea 256 ORA-06512: en "APP.JSON", linea 265 ORA-06512: en "APP.API_CADENAS_1_0", linea 569 ORA-06512: en "APP.API_CADENAS_1_0", linea 622 "

Gracias por la ayuda

**Comment by dsnz** [comment]
-- el siguiente ha sido producido por Google Translate

teniendo en cuenta los errores

Error (534,9): PL / SQL: instrucción ignorada
Error (534,25): PLS-00201: el identificador 'PLJSON_VALUE' debe declararse

debes tener el código de pljson anterior
los otros errores son extraños y probablemente porque mantienes el código anterior junto con mi sugerencia

utilice lo siguiente

```
varxml clob;

obj.put('xml', json_value(varxml));
```

o instale la versión más reciente de pljson donde todos los tipos y paquetes tienen nombres cambiados y comenzando con 'PLJSON_' (¡esta es la mejor solución!) y use la sugerencia original

```
varxml clob;

obj.put('xml', pljson_value(varxml));
```

**Comment by little-programming** [comment]
Gracias dsnz.
Probaré actualizar con la nueva versión, porque ya probé con 
obj.put('xml', json_value(varxml)); y me sigue marcando error.

Tengo varios paquetes usando la versión anterior, y no se cuantos sean los cambios que deba hacer. 
Y además espero obtener el resultado que busco.
Gracias.
saludos

**Comment by little-programming** [comment]
Hola dsnz. Los errores que muestra Oracle son los siguientes:
ORA-06502: PL/SQL: numeric or value error: character string buffer too small
ORA-06512: at "APP.JSON_PRINTER", line 47
ORA-06512: at "APP.JSON_PRINTER", line 201
ORA-06512: at "APP.JSON_PRINTER", line 238
ORA-06512: at "APP.JSON_PRINTER", line 256
ORA-06512: at "APP.JSON", line 265
ORA-06512: at "APP.API_PQFMT_1_0", line 569
ORA-06512: at "APP.API_PQFMT_1_0", line 622
saludos.

**Comment by dsnz** [comment]
Hi,

su primer error fue en la línea 483,
este es un nuevo error en la línea 569,
arreglarlo de la misma manera

**Comment by dsnz** [comment]
Hello,

después de descomprimir
debe cambiar el directorio y entrar en el <directorio de instalación> de pljson y luego ejecutar

SQL> @install.sql

(no puede ejecutar SQL> @<directorio de instalación>/install.sql)

**Comment by dsnz** [comment]
el siguiente código es tuyo con la adición de crear una cadena larga de 512 KB
funciona perfectamente para mí, ¡no hay error!

por favor prueba mi código e informa de nuevo

```
set serveroutput on size 1000000

declare
  obj json;
  varxml clob;
  text_1_byte VARCHAR2(200) := '1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  CLOB_MAX_SIZE NUMBER := 512 * 1024;
  i number;
  k number;
begin
  obj:=json();
  --varxml:='Aquí va el xml';
  
  dbms_lob.createtemporary(varxml, TRUE, dbms_lob.SESSION);
  dbms_lob.trim(varxml, 0);
  k := length(text_1_byte);
  i := 0;
  while i + k < CLOB_MAX_SIZE loop
    dbms_lob.writeappend(varxml, k, text_1_byte);
    i := i + k;
  end loop;
  dbms_output.put_line('varxml, chars = ' || to_char(dbms_lob.getlength(varxml)));
  
  obj.put('xml', pljson_value(varxml));
  obj.print;
end;
```

**Comment by little-programming** [comment]
Hola dsnz .
Compilé tu código y corrió perfectamente. Modifiqué el mío y sigue enviando el mismo error.
 También en el código que publicaste reemplacé el loop y puse la cadena que  tú generas, y envía el mismo error. 
Esto es lo que hice: 

set serveroutput on size 1000000
declare
  obj json;
  varxml clob;
begin
  obj:=json();
  varxml:='La cadena que genera tu loop ';
  dbms_lob.createtemporary(varxml, TRUE, dbms_lob.SESSION);
  dbms_lob.trim(varxml, 0);
  dbms_output.put_line('varxml, chars = ' || to_char(dbms_lob.getlength(varxml)));
  obj.put('xml', pljson_value(varxml));
  obj.print;
end;

Entiendo que el loop genera  una cadena más larga, de acuerdo a una cadena inicial.  Así que en teoría si yo asigno una cadena demasiada larga a varxml, como la que genera tu loop, obj.put() lo debería agregar. Es correcto?

**Comment by dsnz** [comment]
el código que publica funciona también para mí
¡pero no es el código que ejecuta en su aplicación!

intente reducir su código tanto como sea posible para que siga produciendo un error y publíquelo aquí para que podamos ayudarle
Es cierto que el problema no está en pljson, sino en el código de tu aplicación
(muy probablemente en el lugar donde generas el clob; consulta la primera línea de error)

**Comment by little-programming** [comment]
Hola dsnz.
Podrías asignar a una variable la cadena que genera el loop que creaste en el código anterior?, y posterior intentar agregarlo con put, como le harías?.

**Comment by dsnz** [comment]
ver el siguiente ejemplo

```
declare
  obj json;
  varxml clob;
  varxml2 clob;
  text_1_byte VARCHAR2(200) := '1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  CLOB_MAX_SIZE NUMBER := 512 * 1024;
  i number;
  k number;
begin
  obj:=json();
  --varxml:='Aquí va el xml';
  
  dbms_lob.createtemporary(varxml, TRUE, dbms_lob.SESSION);
  dbms_lob.trim(varxml, 0);
  k := length(text_1_byte);
  i := 0;
  while i + k < CLOB_MAX_SIZE loop
    dbms_lob.writeappend(varxml, k, text_1_byte);
    i := i + k;
  end loop;
  dbms_output.put_line('varxml, chars = ' || to_char(dbms_lob.getlength(varxml)));
  
  varxml2 := 'NEW STRING ' || varxml;
  dbms_output.put_line('varxml2, chars = ' || to_char(dbms_lob.getlength(varxml2)));
  
  obj.put('xml2', pljson_value(varxml2));
  obj.print;
end;
```

**Comment by dsnz** [comment]
un ejemplo más simple

```
declare
  obj json;
  varxml clob;
  varxml2 clob;
  text_1_byte VARCHAR2(200) := '1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  CLOB_MAX_SIZE NUMBER := 512 * 1024;
  i number;
  k number;
begin
  obj:=json();
  --varxml:='Aquí va el xml';
  
  varxml := '';
  k := length(text_1_byte);
  i := 0;
  while i + k < CLOB_MAX_SIZE loop
    varxml := varxml || text_1_byte;
    i := i + k;
  end loop;
  dbms_output.put_line('varxml, chars = ' || to_char(dbms_lob.getlength(varxml)));
  
  varxml2 := 'NEW STRING ' || varxml;
  dbms_output.put_line('varxml2, chars = ' || to_char(dbms_lob.getlength(varxml2)));
  
  obj.put('xml2', pljson_value(varxml2));
  obj.print;
end;
```

**Comment by little-programming** [comment]
Hola dsnz. 
Confirmo que el problema fue resuelto, haber actualizado la librería me ha servido de mucho, y con los ejemplos que me estuviste mostrando he podido agregar cadenas largas de tipo clob con obj.put().
Te agradezco mucho.
saludos
