### ISSUE TITLE
pljson list to json

### ISSUE THREAD

**Issue by Gidiklf** [pljson/pljson#116]
Hi guys!
i have a CLOB column which is built from json array 
for exmaple  for json: 
["gidi" ,[{"id":"Abcdef","Createdby":"OMRI"}]]

i built procedure which put the column type in pljson_list type .

now when i print position 2 of the array it print to me : 
,[{"id":"Abcdef","Createdby":"OMRI"}]

im trying to achive just the "id" , i tried to convet position 2 withouts succesed with the following error:

 
ORA-06502:PLSQL numeric or value error : cannot assgin supertype instance to subtype

means i cannot conver the 2 nd of my element list to json , any ideas?

Thank you .

**Comment by dsnz** [comment]
Hello,

Please post your code.

**Comment by Gidiklf** [comment]
create or replace procedure JSON_PARSE

is

 

       myarr pljson_list :=pljson_list();

       dafi pljson:= pljson();

      

       begin

         select  pljson_list(AUDIT_ARGS)  into myarr from Fdz_Auditing where AUDIT_TIMESTAMP='1518110589031';

        dafi:= pljson(myarr.get(position => 2));

              end;

        --select  pljson_ext.get_string(pljson(METADATA), '.origin') from am_audit



The procedure complied successful but when im trying to execute im getting ther error

**Comment by dsnz** [comment]
Hello,

As I happen to be busy at this moment, please allow me some time to check this later and tell you how to proceed.

I will be back.

Thank you,

**Comment by Gidiklf** [comment]
i really appreciate it ! Thank you!

**Comment by boriborm** [comment]
Second element in your pljson_list is not pljson. This is pljson_list too. This list contains first json element. dafi must be pljson_list.

**Comment by Gidiklf** [comment]
i modify dafi as pljson_list 
and add the following code 👍:
dafi:=pljson_list(myarr.get(2));
now im trying to print the "id" value , any idea?

**Comment by boriborm** [comment]
pljson(dafi.get(1)).get('id').get_string()

**Comment by Gidiklf** [comment]
Hey , First thank you for the respond , i still got error :(

create or replace procedure JSON_PARSE

is

 

       myarr pljson_list :=pljson_list();

       dafi pljson_list:= pljson_list();

       gidi json:=json();

      

       begin

         select  pljson_list(AUDIT_ARGS)  into myarr from Fdz_Auditing where AUDIT_TIMESTAMP='1518110589031';

        dafi:= pljson_list(myarr.get(position => 2));

        pljson(dafi.get(1)).get('id').get_string();

              end;

        --select  pljson_ext.get_string(pljson(METADATA), '.origin') from am_audit


 

Compilation errors for PROCEDURE PULSE.JSON_PARSE

 

Error: PLS-00306: wrong number or types of arguments in call to 'GET_STRING'

Line: 11

Text: pljson(dafi.get(1)).get('id').get_string();

 

Error: PL/SQL: Statement ignored

Line: 11

Text: pljson(dafi.get(1)).get('id').get_string();

 

Error: Hint: Variable 'gidi' is declared but never used in 'JSON_PARSE'

Line: 6

Text: gidi json:=json();

**Comment by boriborm** [comment]
This is a function. Usage examples:

id:=pljson.......get_string();

Dbms_output.put_line(pljson.......get_string());

**Comment by dsnz** [comment]
wow, I was away and everything seems solved, thanks @boriborm 

@Gidiklf 
I made example standalone code for test and can verify what @boriborm told you
or alternatively you can use the .print() method
(the example uses both solutions)

```
declare
  myarr pljson_list;
  dafi pljson_list;
begin

  myarr := pljson_list('["gidi", [{"id":"Abcdef", "Createdby":"OMRI"}]]');
  dafi := pljson_list(myarr.get(position => 2));
  dbms_output.put_line(pljson(dafi.get(1)).get('id').get_string());
  pljson(dafi.get(1)).get('id').print();
end;
```

is your problem solved now ?

**Comment by Gidiklf** [comment]
Perfect its work great!
Thank you @boriborm  @dsnz
