### ISSUE TITLE
Select on CLOB with pljson

### ISSUE THREAD

**Issue by Gidiklf** [pljson/pljson#117]
Hi Guys ,

i have one more question 

lets say i have a table and one of the column is CLOB , for example AUDIT_ARGS column ,
and evrey JSON in the CLOB looks like this: 
["gidi",[{"id":"lkfaBZeAMyo0a-9CEf1NBg","createdBy":"system","createdAt":1518110501702,"updatedBy":"system","updatedAt":1518110501702,"name":"decision","desc":"decision","app":"gidi","ownership":{"groups":{"jrmgtUwhFazNKB7bVLZFJw":31},"userVisibleGroups":[],"visibility":"PUBLIC","currentUserRights":31},"schemaId":"ju0opphb5KU_PI6YPQJPoQ","targetVar":"decline","actions":[{"name":"reason","params":[{"name":"code","desc":"code","type":0,"mandatory":true}]},{"name":"alert","params":[]}],"stateful":true,"partitioningFields":[],"timestampField":"event_timestamp","rules":[],"rulesTemplates":[],"snapshots":[],"tenancyType":"SINGLE_TENANT","rulesContexts":[]}],null]

as we see the Json built from array , now i want to query a simple query and to see the Following Json as table is it possible .
for example table like 
id , createdby , createat as column - every key is a coloumn

**Comment by dsnz** [comment]
Hi,

see ```ex_pljson_table.sql``` in ```examples``` directory
modify the many examples to match your desired result

**Comment by Gidiklf** [comment]
Hi ,
im not using Oracle 12 c so i dont have json_table type

**Comment by dsnz** [comment]
Hi,

the pljson 'json_table' works with Oracle 10, 11, 12, ...
this is one reason why pljson is a good alternative to Oracle's 12c json support

try the examples, they will work on your database !
