### ISSUE TITLE
Fluent interface?

### ISSUE THREAD

**Issue by orthoxerox** [pljson/pljson#118]
Hello.

Have you thought about adding a fluent interface to pljson? That is, being able to nest calls to emulate the convenience of Oracle 12c functions:

```plsql
return pljson()
  .put('first-name', 'John')
  .put('last-name', 'Doe')
  .put('address', pljson()
    .put('state', 'CA')
    .put('zip', '90210')));
```

According to [this SO question](https://stackoverflow.com/questions/18086603/how-to-chain-calls-in-a-pl-sql-object-type-of-functions-returning-self/) it will require creating copies for every call, so the performance might suffer.

As an alternative, what about adding a bunch of constructor overloads that accept multiple key-value pairs? Then the sample statement could look like this:

```plsql
return pljson(
  'first-name', 'John',
  'last-name', 'Doe',
  'address', pljson(
    'state', 'CA',
    'zip', '90210'));
```

If any of these changes are acceptable, I could write a PR for them.

**Comment by dsnz** [comment]
Hello,

Of course it's a nice idea.
In an open source project we can't get feedback from 'customers' (!) easily and we can't judge how much pljson is used or what features to add.
Also, the idea of chained functions is not common in PL/SQL and you really save little in typing.
But it seems nice idea.

I don't know of any such use of chaining in Oracle 12c Json (I use pljson 😄 ),
but the second option you propose, using multiple key, value pairs is indeed available.
In the second option you must restrict yourself to a single value type, varchar2 typically, though this is the most common option. I think this option would be most useful.

A PR is always welcome (but include examples, tests and follow existing programming style and guidelines).

Please try to add an option that from your daily experience using pljson (you use pljson everyday, don't you ? 😄 ) will be really used by other pljson users in their applications (and not be just a fancy option).

**Comment by jsumners** [comment]
I think the best approach would be to add a wrapper that uses the core API to implement any of these features.

**Comment by dsnz** [comment]
Indeed, the core api will stay same and it should be used rather than direct manipulation of the json objects. I think the second option with many key-value pairs of varchar2 type

```
pljson(
  'first-name', 'John',
  'last-name', 'Doe'
);
```

is more useful.

**Comment by dsnz** [comment]
Hello,
I would like to ask what are your plans to create a PR for the above ?

I am planning and can work very soon (within today perhaps) a new

pljson(
  pljson_varray(
    'first-name', 'John',
    'last-name', 'Doe'
  )
);

but if you are working on this feature exactly then I will wait for your PR.
If you are working on other feature then I will push this feature.

**Comment by orthoxerox** [comment]
@dsnz I am not currently working on this feature.

**Comment by dsnz** [comment]
=== added comments ===

closing as alternative has been implemented
fluent interface is costly and saves little code but we may rethink if there are other requests with convincing examples
