### ISSUE TITLE
Extracting Diacritics with get_string

### ISSUE THREAD

**Issue by whitfordtech** [pljson/pljson#121]
Hi,

I hope you can help. In the sample code below I cannot seem to extract the diacritics  - all accents or characters beyond the base ascii are returned as question mark. I must be missing something really simple. In the real world application I am extracting many fields from many records and need to retain the diacritics.

```
declare
    obj         pljson;
    jl          pljson_list;
    json_record     pljson;
    s       varchar2(100);
begin
    obj := pljson('
        {
          "records": [
                {   
                  "FirstName": "Cèstina"
                }
            ]
        }');

    jl := pljson_ext.get_json_list(obj, 'records');
    if jl is not null then
        for i in 1 .. jl.count loop
            json_record := pljson_ext.get_json(obj, 'records['|| i || ']');
            s := pljson_ext.get_string(json_record, 'FirstName');
            dbms_output.put_line(s);  -- output: 'C?stina'
            
            select dump(s) into s from dual;
            dbms_output.put_line(s);  -- output: Typ=1 Len=7: 67,63,115,116,105,110,97 
            
            null;
        end loop;
    end if;
end;
```

**Comment by dsnz** [comment]
hello,

don't worry, pljson has no issues with special characters,
your example works fine in my development database

please tell us

- your database version
- your database characterset
- the NLS_LANG you used for the example code

**Comment by whitfordtech** [comment]
Hi there,

I value your recommendations on this.

My database version is 11.2.0.4

```
V$NLS_PAREMETERS shows:
NLS_CHARACTERSET=US7ASCII
NLS_NCHAR_CHARACTERSET=AL16UTF16
LS_LANGUAGE=ENGLISH

NLS_LANG is not set ( I believe this is an environment variable)

```
Many thanks.

**Comment by dsnz** [comment]
Hi,

with these settings, you cannot work with non-ascii characters
your database is US7ASCII and you cannot even store such characters in database unless you use nvarchar2 columns
even if you store nothing in the database and work on the fly, the NLS_LANG setting is not helpful (NLS_LANG is indeed environment variable but if you don't set it then it gets its value from NLS_LANGUAGE)

I think that you cannot perhaps do the very simple thing

```
 dbms_output.put_line('Cèstina');
```

please try it and tell me your result

also if you work on linux server and within sqlplus, the output depends on the terminal locale too (LC_ALL)

**Comment by whitfordtech** [comment]
In SQLDeveloper I get:
`C￨stina`

In Sqlplus (unix) I get:
`Cèstina`


if I do an insert from SQLDeveloper or Sqlplus(unix):
`insert into xx values ('Cèstina');`

then again, selecting in Sqldeveloper v Sqlplus(unix) gives the same as above.

So it seems that the database stores the accented character. I have tried to use **nvarchar** variables but still no joy, they just assign 2 bytes /character but still has the ? mark. Should I perhaps consider migrating from US7ASCII to at least an 8 bit superset?

Thanks so much for your help.

**Comment by dsnz** [comment]
Hi,

It is imperative that your database should have at least an 8 bit characterset, and in today's world you should move to unicode ! Every data and database should be in unicode and no regional characterset should ever be used.

The accented character was stored in this simple test (and only because Oracle did no conversion and because the database stores bytes (so it stored unconverted 8 bit bytes and did not strip the high bit). In other situations (middletier etc.) it might not be stored !

You can read this long thread which is very specific to US7ASCII for more information

https://asktom.oracle.com/pls/apex/asktom.search?tag=differrent-character-set-and-nls

your issue is not with pljson but with your database and client setup

**Comment by whitfordtech** [comment]
FYI - I switched my database to the WE8ISO8859P1 character set and everything works!! I will investigate going full Unicode as you recommend.

Many many thanks.
