### ISSUE TITLE
Detecting if path exists

### ISSUE THREAD

**Issue by whitfordtech** [pljson/pljson#122]
In the following example, how can I detect if the Account.Name path exists ? And (2), is there an option to be case agnostic so that the first test passes as well?

```
    procedure t1 as
        obj         pljson;
        jl          pljson_list;
        json_record     pljson;
    begin
        obj := pljson('
{
  "records": [
    {
      "Account": {
        "Name": "The Main Account"
      },
      "Company_Name": "BEEBE Inc."
    }
  ]
}');


        jl := pljson_ext.get_json_list(obj, 'records');
        if jl is not null then
            for i in 1 .. jl.count loop
                json_record := pljson_ext.get_json(obj, 'records['|| i || ']'); -- one record at a time
                
                if not json_record.exist('Company_name') then
                    null; -- PASS does not exist (case incorrect)
                end if;

                if json_record.exist('Company_Name') then
                    null; -- PASS exists 
                end if; 

                if not json_record.exist('Account.Name') then
                    null; -- FAIL -- Not expecting this - how can i detect if such a path exists?
                end if; 
                
            end loop;
        end if;
    end;

```

**Comment by jsumners** [comment]
https://stackoverflow.com/questions/29040055/check-if-json-object-is-null-or-empty-in-pl-json

**Comment by dsnz** [comment]
Hi,

Looking carefully at your example you can see that you test is
```
if not json_record.exist('Account.Name') then
```
i.e. you look for a path 'Account.Name' and not a single key but `exist()` works only for a key name.
You should use one of the `pljson_ext.get_<xxx>()` functions.

Unfortunately key test is not case insensitive but you can put it yourself as an option in the code of pljson type's implementation of `get()` ('`exist()` calls `get()` internally) or give me a good reason that case insensitive get() is good so I change it in the standard pljson implementation. I think one knows what json structure parses and should be able to use the correct key. Also, what if there is both `Company_name` and `company_name` ?
Alternatively, you could code a procedure that scans all keys sequentially by index and does a case-insensitive test with your search key (something like `exist_any(pljson, key_name)`; you can use the code in `get()` or `index_of()` as a template for your code).

**Comment by whitfordtech** [comment]
Thanks for the time looking at this.

The situation I have is that I am doing requests to Salesforce API and it tolerates case insensitive requests - so I can request the field Company_Name or company_name and I will get a valid response that will return {"Company_Name" : "..."} - if I have misconfigured my pljson_ext.get to look for "company_name" it simply returns NULL.

I therefore first do a check with exist() to make sure the field is present in the JSON and if not throws an exception as it is a fatal programming error.

I cannot however test to see if "Account.Name" exists - the get() just returns null if its missing and as the field is permitted to be null I cant determine if the field is missing or actually there but null.

I'm thinking I need a schema validator ideally within PLSQL?

The JSON spec states that field names should be case sensitive so I don't think you should add case-insensitivity to PLJSON.

The problem really lies with the Salesforce SOQL feature that ignores case so doesn't throw an error when I do something like this:

SOQL : http://..... select+company_name+from+contact

which returns : {"Company_Name" : "..."}
