### ISSUE TITLE
Error on character conversion

### ISSUE THREAD

**Issue by nilson-aguiar** [pljson/pljson#125]
Hi, the SQL below is crashing on execution, it worked on the first time i builted it, but later crashed as the image is showing

```sql
SELECT mes,
       ano,
       to_number(valor) valor
  FROM TABLE(pljson_table.json_table('{
      "listaReajusteFinanceiro":[
        {
            "mes":"Março",
            "ano":2017,
            "valor":0.88
        },
        {
            "mes":"Abril",
            "ano":2017,
            "valor":0.89
        },
        {
            "mes":"Maio",
            "ano":2017,
            "valor":0.84
        },
        {
            "mes":"Junho",
            "ano":2017,
            "valor":0.87
        },
        {
            "mes":"Julho",
            "ano":2017,
            "valor":0.86
        },
        {
            "mes":"Agosto",
            "ano":2017,
            "valor":0.87
        },
        {
            "mes":"Setembro",
            "ano":2017,
            "valor":0.80
        },
        {
            "mes":"Outubro",
            "ano":2017,
            "valor":0.76
        },
        {
            "mes":"Novembro",
            "ano":2017,
            "valor":0.78
        },
        {
            "mes":"Dezembro",
            "ano":2017,
            "valor":0.82
        },
        {
            "mes":"Janeiro",
            "ano":2018,
            "valor":0.88
        },
        {
            "mes":"Fevereiro",
            "ano":2017,
            "valor":0.91
        }
    ]
}
',
                                      pljson_varray('listaReajusteFinanceiro[*].mes',
                                                     'listaReajusteFinanceiro[*].valor',
                                                     'listaReajusteFinanceiro[*].ano'),
                                      pljson_varray('mes', 'valor', 'ano'),
                                      table_mode => 'nested'))
```

![captura de tela de 2018-04-04 11-08-43](https://user-images.githubusercontent.com/5804096/38312622-9ac1bb32-37f8-11e8-88d1-b5dee47e16d4.png)

**Comment by dsnz** [comment]
Hi,

your example works perfectly for me

I think you are in Brazil where you use "," as decimal separator and I guess your database has Brazilian locale setting
now the code in pljson uses number() to parse numbers and the numbers in your json are with "." decimal point so there is a character to number exception
please alter your session locale to American and try again and tell me

I think this could be a bug as in the json standard (!) numbers should be always with "." as decimal point

**Comment by dsnz** [comment]
Hi again,

you should do

alter session set NLS_TERRITORY=America;

then test


but I already did

alter session set NLS_TERRITORY=Brazil;

and the test afterwards gave the error messages you posted
so, it is surely a bug not noticed for long time

I will fix within a week

**Comment by dsnz** [comment]
@nilson-aguiar 

please download latest source
or get latest release 2.1.1 (will be released soon if not already)
test it and report here

**Comment by nilson-aguiar** [comment]
Hi! Tested and it's working! Thanks a lot!
