### ISSUE TITLE
install script - bad paths?

### ISSUE THREAD

**Issue by kidplug** [pljson/pljson#127]
Trying to run install.sql from 2.1.1

SP2-0310: unable to open file "src/pljson_element.type.decl.sql"

Why are the files prefixed with src/  ?
eg:
` @@src/pljson_element.type.decl.sql `

**Comment by dsnz** [comment]
how you try to install ???

**Comment by kidplug** [comment]
I downloaded the 2.1.1.zip from
https://github.com/pljson/pljson/releases

I guess the build-release.sh puts the files into the same .zip file.
I guess I should just download the whole repo bundle...?

**Comment by kidplug** [comment]
maybe this:
` cp -R src/* testsuite examples *install.sql CHANGELOG.md README.md target `
shouldn't have an asterisk on src/*

**Comment by dsnz** [comment]
oups...
good you said this
I downloaded and indeed the 2.1.1 zip is damaged,
first time this thing happens

please be patient some time (a few hours I guess)
until @jsumners has a look at this

**Comment by jsumners** [comment]
Thank you. I'll get it fixed soon. For now, you can just use the repo.

**Comment by jsumners** [comment]
Fix in the `master` branch. I will issue a release soon.
