### ISSUE TITLE
Accessing PLJSON object from SQL as other user gives error: OCI-21700

### ISSUE THREAD

**Issue by kidplug** [pljson/pljson#128]
I created a database user: PLJSON and I have the latest version installed using the installer script.

As the PLJSON user, the following work fine:

> desc PLJSON;
> select pljson('{}') from dual;

I also ran the grants/synonyms script to create public synonyms.
No errors occcured during install.

But as a different database user, the above commands fail with:
>  SQL> desc pljson
> ERROR:
> OCI-21700: object does not exist or is marked for delete

But using the pljson object inside PL/SQL code seems to work fine.
Do you have a missing permission on some "inner" object type?

**Comment by kidplug** [comment]
Discovered the issue is with (at least) these types:
> pljson_element
> pljson_varray

Adding these lines to the grants script seems to have fixed it:
> grant execute on pljson_element to public;
> create or replace public synonym pljson_element for pljson_element;
> grant execute on pljson_varray to public;
> create or replace public synonym pljson_varray for pljson_element;

Do you think there any other potentially missing permissions?

**Comment by dsnz** [comment]
there are two more grants needed
I will post when all is ready

**Comment by dsnz** [comment]
please get new repo update,
uninstall.sql
install.sql

then run testsuite

I have tested and it runs ok
tell us your results too

**Comment by dsnz** [comment]
@kidplug 
Have you run installation and tests again ?
Please tell us what have you done or what you plan to do, else we will assume that all is okay.

(I have tested again latest update on various platforms and everything is fine, so I'm curious if your site has a problem and under what circumstances).

**Comment by dsnz** [comment]
@kidplug 
Have you run installation and tests again ?
Please tell us what you have done or what you plan to do, else we will assume that all is okay.

(I have tested again latest update on various platforms and everything is fine, so I'm curious if your site has a problem and under what circumstances).

**Comment by dsnz** [comment]
closing as we consider solved (together with #130 and #131)
