### ISSUE TITLE
@@src/grantsandsynonyms.sql needs to come at end of install.sql

### ISSUE THREAD

**Issue by kidplug** [pljson/pljson#129]
... after all the types and packages have been created.

**Comment by dsnz** [comment]
let's stay on #128

**Comment by dsnz** [comment]
=== added comments ===

the change proposed is not entirely correct
yet a related modification of the install script was done
and clear comments were added (inside install.sql and README)
to make this a user selectable option to enable grants and synonyms to public so other oracle users can use pljson
by default it's enabled now but some sites may choose to disable
