### ISSUE TITLE
pljson_unicode.test.sql FAILS but also bombs out - no results reported

### ISSUE THREAD

**Issue by kidplug** [pljson/pljson#130]
Failed test:
> Test json with clob(s), varchar2(s) both 1-byte, 2-byte chars using to_clob()
>    FAILED: dbms_lob.getlength(json_clob) = 1896656

But its never reported b/c of pl/sql crash:
> ERROR at line 1:
> ORA-20001: Length of result JSON more than 32767 bytes. Use to_clob() procedures
> ORA-06512: at "PLJSON.PLJSON_PRINTER", line 320
During test:
>   Test json list with many small strings of 64 2-byte chars using to_char()

DB:  
> Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production 

OS:
> centos-release-7-4.1708.el7.centos.x86_64

**Comment by dsnz** [comment]
#128
