### ISSUE TITLE
How Can I Get A CORRECT FROMAT OF DATE

### ISSUE THREAD

**Issue by 2012MIKO** [pljson/pljson#133]
Hi Guys ,

i want to ask a question.

When I excute the sql in pl/sql ,I will get json data,but the format of "CreateDate" is incorrect.The type of "CreateDate" is DATE.

The sql is:

```
select json_printer.pretty_print_list(pljson_util_pkg.sql_to_json('
select * from WS_GET_VW t where T.KEY1 IN (''31'',''41'')'))
  from dual;
```

_**The result like this:**_

```
[{
	"KEY1": 31,
	"KEY2": 1,
	"CreateDate": "17-10月-17"

}, {
	"KEY1": 41,
	"KEY2": 1,
	"CreateDate": "15-10月-17"
}]
```

_**How can i get the result like this:**_

```
[{
	"KEY1": 31,
	"KEY2": 1,
	"CreateDate": "2017-10-17T10:00:00"

}, {
	"KEY1": 41,
	"KEY2": 1,
	"CreateDate": "2017-10-15T10:00:00"
}]
```

**Comment by dsnz** [comment]
please post the description of table WS_GET_VW
(column names, types, etc)

an easy solution seems to be to not ```select *```
but instead
```select key1, key2, to_char(CreateDate, 'YYYY-MM-DD"T"HH24:MI:SS')```

**Comment by 2012MIKO** [comment]
WS_GET_VW is a simple VIEW,it contains 3 columns,KEY1(number)，KEY2(number),CreateDate(date).
But,actully used VIEW is complicated,it contains multiple columns which the type of is date.
So, `"to_char(CreateDate, 'YYYY-MM-DD"T"HH24:MI:SS')" `does not apply to me.How can I get the default format of DATE like` 'YYYY-MM-DD"T"HH24:MI:SS'`.

**Comment by dsnz** [comment]
Hi,

What you are getting now is the default format for Oracle at your installation !

When you call ```sql_to_json()``` then pljson calls Oracle procedures in the background which return dates in the Oracle default format.

Oracle default date format is 'DD-MON-RR' while what you want is the ISO-8601 date format.
You have 2 solutions.

1. you use ```to_char(..., 'YYYY-MM-DD"T"HH24:MI:SS')``` as I told you and I see no reason that you cannot use it, that's why there is the select part of a SQL statement !
the fact that there are many columns and you select from a view do not matter and you can select the view column using the to_char() function I gave to you
2. you change the NLS_DATE_FORMAT
- either at the session level by ```alter session set NLS_DATE_FORMAT =  'YYYY-MM-DD"T"HH24:MI:SS'```
- or at the database level by ```alter system set NLS_DATE_FORMAT =  'YYYY-MM-DD"T"HH24:MI:SS'```

**Comment by dsnz** [comment]
Hi,

the test you do is not correct, you selected the date from a windows tool
which has set a session nls_date_format for you and which is 'YYYY/MM/DD HH24:MI:SS'

what is curious is that it appears that in the same tool you do
select from dual;
and
select json_printer.pretty_print_list(pljson_util_pkg.sql_to_json('
select sysdate from dual')) from dual;
with different format results !

I did the same test (in two systems!) and I get the same format
and it is always in the format of the session nls_date_format

in any case the date format of sql_to_json() depends on session nls_parameters

please do run

```
select * from nls_instance_parameters;
select * from v$nls_parameters;
select sysdate from dual;
select json_printer.pretty_print_list(pljson_util_pkg.sql_to_json('
select sysdate from dual')) from dual;
```

all from the same window (use script output and not table output in your tool)
or if this is not possible then run the above from sqlplus

**Comment by 2012MIKO** [comment]
Hi,

After running the sql you provided,i find the default format of my database is "DD-MON-RR".

For many reasons,I can not change the default format of my database,and i can not use `to_char(..., 'YYYY-MM-DD"T"HH24:MI:SS')`.So i  will use other way rather than pljson,but anyway ,i have learned a lot, thank you very much.

**Comment by dsnz** [comment]
good, then we will soon close this issue

you need not change the database default date format (you should not)

either in your application environment change the NLS_DATE_FORMAT to  'YYYY-MM-DD"T"HH24:MI:SS'
or within your application run at start

```alter session set NLS_DATE_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS';```
