### ISSUE TITLE
PL/JSON help

### ISSUE THREAD

**Issue by chn47** [pljson/pljson#134]
Dears,

I have a Json data which i would like to use in PL/JSON. 

> DECLARE
   v_response_text   VARCHAR2 (2000)
      := '{"status":"OK","content":{"inBoundaries":false,"distance":284724.94830337656,"nearestBoundaryPoint":{"latitude":49.545166015625,"longitude":5.81507730484009}}}';
   v_response_json   json := json (v_response_text);
BEGIN
   DBMS_OUTPUT.put_line (
      'v_response_json: ' || json_ext.get_string (v_response_json, 'inBoundaries'));
END;

I get a null value and i don't understand why.

In advance thank you soo much for your help,
Kim.

**Comment by dsnz** [comment]
Hello,

just use

```
DBMS_OUTPUT.put_line (
'v_response_json: ' || case json_ext.get_bool (v_response_json, 'inBoundaries') when true then 'true' else 'false' end);
```

inBoundaries is boolean and you must use get_bool() instead of get_string()
I used CASE expression to print it because dbms_output.put_line cannot handle booleans

**Comment by dsnz** [comment]
the case expression should better be

```
case val
when true then 'true'
when false then 'false'
else 'null'
end;
```

and the whole be a function for general use

**Comment by chn47** [comment]
Thank you verymuch for your helpfull dsnz :+1: 

And if i would like to print the "distance"?
It's a get_number but i get a null value too.

In advance thank you for your help
Kim.

**Comment by dsnz** [comment]
well it's my mistake, I forgot to mention something more

you should use

```
DBMS_OUTPUT.put_line (
'v_response_json: ' ||
case json_ext.get_bool(v_response_json, 'content.inBoundaries')
when true then 'true'
when false then 'false'
else 'null'
end);
DBMS_OUTPUT.put_line (
'v_response_json: ' || json_ext.get_number(v_response_json, 'content.distance'));
```

notice the use of  'content.distance'
the whole path is needed

**Comment by chn47** [comment]
Thank you very much dsnz.
It works very fine now.
Best regards,
Kim.
