### ISSUE TITLE
How to handle special characters in element name with json_table

### ISSUE THREAD

**Issue by slingshot322** [pljson/pljson#141]
Hello,

Is there a way to construct the json path that json_table will accept to extract the ".expires" or ".issued" element from the json below?

`SELECT * FROM TABLE (pljson_table.json_table ('{
"access_token":
"some stuff",
"token_type": "bearer",
"expires_in": 1209599,
"refresh_token":
"other stuff",
".issued": "Mon, 04 Sep 2017 14:31:46 GMT",
".expires": "Mon, 18 Sep 2017 14:31:46 GMT"
}'                    , pljson_varray ('.expires'), pljson_varray ('expires')));`

I've search a bit on json path documentation and anything I've tried produces errors when executing. The example I provided will run but the "expires" column outputs as null.

**Comment by dsnz** [comment]
run it this way

```
SELECT * FROM TABLE (pljson_table.json_table (
'{
"access_token": "some stuff",
"token_type": "bearer",
"expires_in": 1209599,
"refresh_token": "other stuff",
".issued": "Mon, 04 Sep 2017 14:31:46 GMT",
".expires": "Mon, 18 Sep 2017 14:31:46 GMT"
}' ,
pljson_varray ('[".expires"]'),
pljson_varray ('expires')));
```

see also issues #106, #67, #55

**Comment by slingshot322** [comment]
Ah, well seems I didn't look hard enough. Thanks for your help.

**Comment by aragorniiit** [comment]
How do I get solution/product_code value in below json?

SELECT *
  FROM TABLE (
          pljson_table.json_table (
             '{
"access_token": "some stuff",
"token_type": "bearer",
"expires_in": 1209599,
"refresh_token": "other stuff",
".issued": "Mon, 04 Sep 2017 14:31:46 GMT",
".expires": "Mon, 18 Sep 2017 14:31:46 GMT",
"custom_fields": {
        "country": "US",
        "solution/product_code": "999999 - Other"}
}',
             pljson_varray ('[".expires"]',
                            '["custom_fields.solution/product_code"]'),
             pljson_varray ('expires', 'code')));

**Comment by dsnz** [comment]
@aragorniiit 

```
SELECT *
FROM TABLE (
pljson_table.json_table (
'{
"access_token": "some stuff",
"token_type": "bearer",
"expires_in": 1209599,
"refresh_token": "other stuff",
".issued": "Mon, 04 Sep 2017 14:31:46 GMT",
".expires": "Mon, 18 Sep 2017 14:31:46 GMT",
"custom_fields": {
"country": "US",
"solution/product_code": "999999 - Other"}
}',
pljson_varray ('[".expires"]',
'custom_fields["solution/product_code"]'),
pljson_varray ('expires', 'code')));
```

**Comment by aragorniiit** [comment]
Thanks. It worked.
