### ISSUE TITLE
Type creation when using pljson_table.json_table

### ISSUE THREAD

**Issue by jbfrache** [pljson/pljson#142]
Hi,
Every time I call the function pljson_table.json_table, a new type is created in my schema, with a generated name like "SYSTPbvwwOeRGYobgUz04E6x+Iw==".
I installed pljson in a separate schema, and I made publics aliases on pljson objects.
Can I use this installation design ?
Thanks.

**Comment by dsnz** [comment]
Hi,

in ```ex_pljson_table.sql``` (within ```examples``` folder) there is a notice

```
  === NOTE ===
  in Oracle 12c, any run of json_table will produce 2 new types with Oracle generated names (like ST00001F3lDKZRT/+Zit/T5XWqsw=)
  for each different select (different in number or names of columns)
  these are temporary and should be cleared automatically within 12 hours
```

so, this is 12c behavior but it is no problem

about your installation, it is a good design if you follow the instructions at the end of ```install.sql``` (so that all synonyms and grants are created correctly)

**Comment by jbfrache** [comment]
Thanks for you reply.
But I am working with a 11g (11.2.0.4) database.
I will see if the created types are cleared automatically.

**Comment by dsnz** [comment]
Hi,

indeed this happens with 11.2 too
thank you for bringing to attention, the notice will be updated in next release

that the types should be cleared within 12 hours is an Oracle statement of course, not mine
the idea is that a background process will eventually clear these types
