### ISSUE TITLE
I have a stored procedure which has 3 inputs and 2 output from which 2 input and 1 output parameters are collection type. i have json formata as input please let me know how to decode it to sql inputs and encode the output of a stored procedure to json.

### ISSUE THREAD

**Issue by SoumyaSwain20** [pljson/pljson#143]

**Comment by dsnz** [comment]
this forum is mainly for problems/bugs/new features
for usage, see the examples
we could help you also if you have tried to implement something and have some code written to assist with improving or fixing it, but your question is very vague

**Comment by SoumyaSwain20** [comment]
thanks...
