### ISSUE TITLE
install pljson-2.3.0, error

### ISSUE THREAD

**Issue by jenniferzhang3** [pljson/pljson#144]
I am installing pljson-2.3.0 into Oracle 12.2.0.1C database.
I got three errors like below
     create or replace type pljson_varray as table of varchar2(32767);
     *
     ERROR at line 1:
     ORA-02303: cannot drop or replace a type with type or table dependents
    
    
     create or replace type pljson_narray as table of number;
     *
     ERROR at line 1:
     ORA-02303: cannot drop or replace a type with type or table dependents
Are those errors can be ignored?

Thanks

**Comment by dsnz** [comment]
Hi,

It's very rare that the install script will fail.
There are some error messages that can be ignored (including the ones you posted) and for this reason there are 'set termout off' commands inside some sql scripts that are called so these messages do not appear, but this works only inside sqlplus.
If you tried to install within some other sql tool then you might see these errors and you can ignore them.

**Comment by jenniferzhang3** [comment]
thanks for your quick response, the install has been finished. Just show those errors. OK, I just ignore them.
