### ISSUE TITLE
pljson_value.get_string() Chopping Off Strings at 5000 Characters

### ISSUE THREAD

**Issue by gfrobenius** [pljson/pljson#154]
I've never submitted a Git issue before so forgive me if I'm taking the wrong approach here.  I also submitted this to SO... https://stackoverflow.com/questions/52391268/oracle-12c-pl-json-chopping-off-strings-at-5000-characters

**Comment by dsnz** [comment]
Hi,
thank you for asking

there are two ```get_string``` (s)

```
member function get_string(max_byte_size number default null, max_char_size number default null) return varchar2;

member procedure get_string(self in pljson_value, buf in out nocopy clob);
```

the first is the one you used and of course is limited to varchar2 length
(which is further limited to 5000 to accommodate for unicode text)
you should use the second one (which writes to a clob buffer you have allocated)

I suggest also that you try the new version 3.0 in develop_v3 branch
which is easier to use and faster
and also will have exciting new features by the end of this week
(version 3.0 has already a ```get_clob()``` function that returns a lob pointer to the internal clob
version 2.0 will have it available by the end of this week too) 

if you need more help, feel free to ask

**Comment by gfrobenius** [comment]
Thank you so much for the fast response.  I follow you, just not sure how to call that other get_string procedure.  I changed this...

json_obj.get('n3').get_string;

to this, since it accepts "itself"...

pljson_value.get_string(json_obj.get('n3'), myClob);

But I'm getting...

ORA-06502: PL/SQL: numeric or value error: invalid LOB locator specified: ORA-22275
ORA-06512: at "SYS.DBMS_LOB", line 710

I didn't see any clob examples in this repository.  I'm reading up on how to use LOB locators now.  Thanks!

**Comment by dsnz** [comment]
the error in your code is that myClob is not really allocated

see the following example code
(I have not run it but I'm pretty sure it will work)

```
declare
  myClob clob;
begin
    dbms_lob.createtemporary(myClob, false); -- <-- allocate clob, myClob now contains a lob pointer
    pljson_value.get_string(json_obj.get('n3'), myClob); -- <-- the pljson call

    ... <code to manipulate myClob> ...
    dbms_output.put_line(dbms_lob.getlength(myClob));

    dbms_lob.freetemporary(myClob); -- <-- free the allocated clob
end;
```
you can also browse the testsuite\pljson_base64.test.sql test file
where in line 75 get_string() is called with clob parameter

I invite you to participate in the issue #153 discussion
as we need feedback from our users about pljson usage and new features to introduce

**Comment by StivenCharry** [comment]
Hola tengo este caso y cuando uso el procedumiento get_string pasa lo siguiente 

````
   lvc_nomImg := lnu_archivo.GET('nombre').GET_STRING();
   dbms_lob.createtemporary(lvc_img, false);
   json_value.get_string(lnu_archivo.GET('imagen'),lvc_img);
  dbms_output.put_line(dbms_lob.getlength(lvc_img));
   dbms_lob.freetemporary(lvc_img);
```
alguna idea del porque ?
ORA-22922: nonexistent LOB value
ORA-06512: at "SYS.DBMS_LOB", line 560
ORA-06512: at "CIKLOS.JSON_VALUE", line 99

**Comment by dsnz** [comment]
Hi,

please use English and I hope you can write in English because we can't help you (even though I happen to understand your inquiry at this moment)

the error

ORA-06512: at "CIKLOS.JSON_VALUE", line 99

is inconsistent with current PLJSON version 2
so, it seems you have a very old version

install the newest version 2 (branch: master or release 2.5.2) or alternatively install version 3 (branch: develop_v3, but you have to change your code a little), and try again

if you still get an error then post the smallest complete code that demonstrates the error with the full stack trace again
