### ISSUE TITLE
Convert XML to JSON

### ISSUE THREAD

**Issue by ARCHAMO** [pljson/pljson#158]
Good morning.
Is it possible to convert an XML to JSON directly?
I have the XML in a CLOB field of a table and I need to convert it to JSON. I appreciate your help.

**Comment by eugene-popov** [comment]
Hello. Maybe [this](https://github.com/pljson/pljson/blob/master/src/addons/pljson_ml.package.sql) could help you. For more details see http://www.jsonml.org/

**Comment by dsnz** [comment]
please see example file
```
examples\ex18.sql
```

(use pljson_ml instead of json_ml)
