### ISSUE TITLE
Method dispatch on NULL SELF argument is disallowed.

### ISSUE THREAD

**Issue by eugene-popov** [pljson/pljson#159]
Hello. I have generated a JSON using PL/JSON library. Here's the output of the json.get_char:
`{
  "list" : ["{\r\n  \"house\" : 1\r\n}", "{\r\n  \"house\" : 1\r\n}", "{\r\n  \"house\" : 2\r\n}", "{\r\n  \"house\" : 9\r\n}", "{\r\n  \"house\" : 12\r\n}"]
}`
Now, I'm trying to get the inner list by calling json.path('["list"]').to_char(). And it works correctly:
`["{\r\n  \"house\" : 1\r\n}", "{\r\n  \"house\" : 1\r\n}", "{\r\n  \"house\" : 2\r\n}", "{\r\n  \"house\" : 9\r\n}", "{\r\n  \"house\" : 12\r\n}"]`
It correctly parses the list element of the specified index (json.path('["list"][1]').to_char()):
`"{\r\n  \"house\" : 1\r\n}"`
However, for some reason, PL/JSON cannot parse the attributes (json.["list"][1]["house"].to_char()). It raises 
`ORA-30625: method dispatch on NULL SELF argument is disallowed
ORA-06512: at line 99`
I have no idea why this happens, because the JSON is considered to be correct (while it's been generated with the library itself).
I don't know exactly what version of PL/JSON I use. In our production we run Oracle 11g. The PL/JSON code has been compiled in August of 2017 for the last time.

**Comment by boriborm** [comment]
Your code has element "house" not "houses"

**Comment by eugene-popov** [comment]
> Your code has element "house" not "houses"
Oh, that was a typo. Actually, I called json.["list"][1]["house"].to_char().
I also simplified the issue (removed some unnecessary details).

**Comment by dsnz** [comment]
```
json.["list"][1]
```
is
```
"{\r\n \"house\" : 1\r\n}"
```
which is a string, not a json object
so, you cannot continue with json.["list"][1]["house"] ...

**Comment by eugene-popov** [comment]
> 
> 
> ```
> json.["list"][1]
> ```
> 
> is
> 
> ```
> "{\r\n \"house\" : 1\r\n}"
> ```
> 
> which is a string, not a json object
> so, you cannot continue with json.["list"][1]["house"] ...
The path method of the json type is declared of return type json_value. So, I think the return value should be a json_value, not a string, shouldn't it?

**Comment by dsnz** [comment]
it is a json value, but a "string" value 😄 

a pljson_value object represents any json value, for ex. number, string, boolean, object, array
your original json list contained strings so you that's what you get back

**Comment by dsnz** [comment]
it is a json value, but a "string" value 😄

a pljson_value object represents any json value, for ex. number, string, boolean, object, array
your original json list contained strings so that's what you get back
(in my previous comment I should have said more accurately **which is a json string, not a json object**)

**Comment by eugene-popov** [comment]
Ok, now I understand the problem. Now, I'm trying to parse the string as a json like `json(json$o).path('["list"][1]').to_char())` and get the exception: 
`ORA-20101: JSON Parser exception - no { start found
ORA-06512: at "WEB.JSON_PARSER", line 655
ORA-06512: at "WEB.JSON", line 37
ORA-06512: at line 99`

I used the following technique to generate the JSON:
`
declare
json$o json := new json();
houses$o json_list := new json_list();
house$o json;
begin
house$o := new json();
house$o.put('house', house.house_number);
houses$o.append(new json_value(current_house$o.to_char));                                   
json$o.put('list', houses$o);  
return json$o;
end;`
Is this a good practice or should I generate the JSON in another way?

**Comment by eugene-popov** [comment]
Oh, now I tried using json_value.get_string instead of json_value.to_char and it worked.

**Comment by eugene-popov** [comment]
So the solution was to consider JSON values stored in the list as string representations of JSON objects, and parse them to JSON objects using the JSON constructor and the get_string method of the JSON value class like this:
`json(json$obj.path('["list"][1]').get_string).get_path(["house"])`.

**Comment by eugene-popov** [comment]
@dsnz, thank you for your help.

**Comment by dsnz** [comment]
I used

```
declare
  obj pljson;
  obj2 pljson;
begin
  obj := pljson('{ "list" : [{"house" : 1}, "{\r\n \"house\" : 1\r\n}", "{\r\n \"house\" : 2\r\n}", "{\r\n \"house\" : 9\r\n}", "{\r\n \"house\" : 12\r\n}"] }');
  dbms_output.put_line(obj.path('["list"][1]').to_char());
  obj2 := pljson(obj.path('["list"][1]').to_char());
  --dbms_output.put_line(obj.path('["list"][1]["house"]').to_char());
end;
```

and it worked
generally ```to_char()``` is meant to produce a printable output
maybe there are cases where the to_char() output cannot be parsed again
but not in this case, as you see it worked for me

```get_string()``` is the correct way to get the json string as the real string it is

In my humble opinion you should not have strings representing json objects and doing all this parsing many times
your original json should be a fully one time parsable json object
but maybe your business needs are such that you have to do this ...

@eugene-popov  thank you too

**Comment by julgon2012** [comment]
In the documentation of the PLJSON subtype, there is this example. But if you run that PL / SQL block it gives the error that is being addressed in this post.

The error occurs on line 5, but if you coments it, line 6 fails. The code block only works well with line 4.
Is there something wrong with the code?   

I have version 2.4.0 installed, on a 11g base (Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
PL / SQL Release 11.2.0.4.0 - Production
"CORE 11.2.0.4.0 Production"
TNS for HPUX: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production)

declare
   myjson pljson := pljson('{ "foo": "foo", "bar": [0, 1, 2], "baz": { "foobar": "foobar" } }');
 begin
   myjson.get('foo').print(); // => dbms_output.put_line('foo')
   myjson.get('bar[1]').print(); // => dbms_output.put_line('0')
   myjson.get('baz.foobar').print(); // => dbms_output.put_line('foobar')
 end;

**Comment by dsnz** [comment]
Hi, I guess you are on version 2

you should run your code this way

```
declare
  myjson pljson := pljson('{ "foo": "foo", "bar": [0, 1, 2], "baz": { "foobar": "foobar" } }');
begin
  myjson.get('foo').print();
  
  myjson.path('bar[1]').print();
  dbms_output.put_line(pljson_ext.get_number(myjson, 'bar[1]'));
  pljson_ext.get_json_value(myjson, 'bar[1]').print();
  
  myjson.path('baz.foobar').print();
  dbms_output.put_line(pljson_ext.get_string(myjson, 'baz.foobar'));
  pljson_ext.get_json_value(myjson, 'baz.foobar').print();
end;
```

the signature of pljson.get is
```
  member function get(pair_name varchar2) return pljson_value,
```

which indicates that it accepts a pair name not a path !

where exactly did you find the example you say ?

**Comment by julgon2012** [comment]
Thank you for answering so fast and for the wonderful work you have done with this library.

The code that I sent you is in the documentation of version 2.4.0 that I downloaded from Github yesterday.


[cid:image001.png@01D4A82A.F65EFCA0]




[cid:image002.png@01D4A82B.24F31EC0]


Saludos cordiales.



Julio González
Soluciones Verticales
Dirección de Tecnología de la Información
MAPFRE ARGENTINA
gonjul@mapfre.com.ar<mailto:afurmston@mapfre.com.ar>

De: E.I.Sarmas [mailto:notifications@github.com]
Enviado el: miércoles, 09 de enero de 2019 14:34
Para: pljson/pljson <pljson@noreply.github.com>
CC: julgon2012 <julgon2012@gmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [pljson/pljson] Method dispatch on NULL SELF argument is disallowed. (#159)


Hi, I guess you are on version 2

you should run your code this way

declare

  myjson pljson := pljson('{ "foo": "foo", "bar": [0, 1, 2], "baz": { "foobar": "foobar" } }');

begin

  myjson.get('foo').print();



  myjson.path('bar[1]').print();

  dbms_output.put_line(pljson_ext.get_number(myjson, 'bar[1]'));

  pljson_ext.get_json_value(myjson, 'bar[1]').print();



  myjson.path('baz.foobar').print();

  dbms_output.put_line(pljson_ext.get_string(myjson, 'baz.foobar'));

  pljson_ext.get_json_value(myjson, 'baz.foobar').print();

end;

the signature of pljson.get is

  member function get(pair_name varchar2) return pljson_value,

which indicates that it accepts a pair name not a path !

where exactly did you find the example you say ?

**Comment by dsnz** [comment]
Thank you Julio,

The documentation is rather old but yet should be correct. I will check and try to fix it.
I have put a mini documentation in the project README and you should check the function/procedure signatures. If you'd like to see more in this README then tell us here.
We also like ideas for improvement, see #153 .

**Comment by julgon2012** [comment]
Do you have a blog or website where you teach, in a simple way, the new things of Oracle? I would be very interested in reading it.

Unfortunately, in my country it is very expensive to access good Oracle courses, and most of us who work with Oracle learn cheap, and not so good courses. And you seem to be an expert on the subject.

Again, thank you for your work. It will help a lot to mine and maybe I will get more consideration from my boss. Of course, your code is compiled in our database with all the information that indicates what your development is.


Saludos cordiales.

Julio González
Soluciones Verticales
Dirección de Tecnología de la Información
MAPFRE ARGENTINA
gonjul@mapfre.com.ar<mailto:afurmston@mapfre.com.ar>

De: E.I.Sarmas [mailto:notifications@github.com]
Enviado el: miércoles, 09 de enero de 2019 14:34
Para: pljson/pljson <pljson@noreply.github.com>
CC: julgon2012 <julgon2012@gmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [pljson/pljson] Method dispatch on NULL SELF argument is disallowed. (#159)


Hi, I guess you are on version 2

you should run your code this way

declare

  myjson pljson := pljson('{ "foo": "foo", "bar": [0, 1, 2], "baz": { "foobar": "foobar" } }');

begin

  myjson.get('foo').print();



  myjson.path('bar[1]').print();

  dbms_output.put_line(pljson_ext.get_number(myjson, 'bar[1]'));

  pljson_ext.get_json_value(myjson, 'bar[1]').print();



  myjson.path('baz.foobar').print();

  dbms_output.put_line(pljson_ext.get_string(myjson, 'baz.foobar'));

  pljson_ext.get_json_value(myjson, 'baz.foobar').print();

end;

the signature of pljson.get is

  member function get(pair_name varchar2) return pljson_value,

which indicates that it accepts a pair name not a path !

where exactly did you find the example you say ?

**Comment by dsnz** [comment]
Thank you again Julio.
