### ISSUE TITLE
json_xml : How to remove enclosing quotes ?

### ISSUE THREAD

**Issue by pmalera** [pljson/pljson#16]
PL/SQL Script : 
```
SET SERVEROUTPUT ON;

DECLARE
  l_json json;
  l_xml  XMLTYPE;
  l_clob CLOB;
BEGIN
  l_json := json('{"currency": "CHF","maxCreditAllowed": 5000,"skipFraudCheck": true,"customerIdentification": "CONFIRMED"}');
  l_json.print;
  l_xml := json_xml.json_to_xml(l_json);
  l_clob := l_xml.getstringval;
  dbms_output.put_line(l_clob);
END;
/
```

"currency" element is returned like this : 
<currency>&quot;CHF&quot;</currency>
but should return this (no quotes) : 
<currency>CHF</currency>

**Comment by jsumners** [comment]
Your JSON does not conform to [rfc4627](http://www.ietf.org/rfc/rfc4627.txt). Try again with valid JSON.

**Comment by pmalera** [comment]
I just fixed my JSON, but result is the same.

**Comment by jsumners** [comment]
At what point in your script do you see this behavior? Have you inserted a log line just after creating the JSON object to see what the result is? e.g.:

```
l_json := json('{"currency": "CHF","maxCreditAllowed": 5000,"skipFraudCheck": true,"customerIdentification": "CONFIRMED"}');
dbms_put.put_line( l_json.get('currency').to_char );
```

What does the result of the `xmlserialize` method look like? Is that adding the quotes?

**Comment by pmalera** [comment]
Yes the script is full of logs, you can simply run it in an SQL*Plus session and you will immediately see the result and understand the problem.
The "xmlserialize" is here juste for XML pretty-print output.

**Comment by jsumners** [comment]
The script you have in this bug report does not show the logging I am suggesting. If you don't want to provide me with information to go on, then I can just close the ticket. I do not believe there is a problem with this library. I believe the problem to be in the XML serialization.

**Comment by pmalera** [comment]
I just put the serialization to display the XML properly on screen, if I remove it the problem is still the same.
I will try to provide you the exact result, but if I copy/paste the XML in this issue, it is automatically interpreted by the text editor and does not display correcly (XML tag are removed), so I have to provide you the result as an image here :

![result](https://cloud.githubusercontent.com/assets/15441852/10862358/e50a751c-7fa4-11e5-8eb2-47244d9add21.jpg)

**Comment by jsumners** [comment]
You merely need to enclose the output in a fenced code block. That a header and footer of three backticks. Click the link on the top left corner of the input box.

So that's the XML output after the serialization call, I assume. What about the other output I asked for?:

```
l_json := json('{"currency": "CHF","maxCreditAllowed": 5000,"skipFraudCheck": true,"customerIdentification": "CONFIRMED"}');
dbms_put.put_line( l_json.get('currency').to_char );
```

**Comment by pmalera** [comment]
The output you asked for is in my previous comment (Original in JSON), or maybe I didn't understand well what you exactly need.
My initial question was : How to use method "json_xml.json_to_xml" correcly ?, on my point of view, there is a bug in the output, my question was not "How to get rid of this method ?". Or maybe is there any other way to convert json in XML with pl/sql.

**Comment by jsumners** [comment]
I gave you the code (twice!) to generate the output I want to see. I'm not trying to get rid of whatever method you think I'm trying to make you get rid of. I'm trying to get some information out of you that will help figure out the problem.

I looked through the `json_to_xml` method and there is nothing in there that escapes `"` characters.

**Comment by pmalera** [comment]
The output of your code given in your second comment return : "CHF", but that's not what I expect.
As I understand your last comment, you don't have the same result as me on your side ?
Mean if you execute my initial code on your side, are string values escaped or not ?

**Comment by jsumners** [comment]
```
SET SERVEROUTPUT ON;

DECLARE
  l_json json;
  l_xml  XMLTYPE;
  l_clob CLOB;
BEGIN
  l_json := json('{"currency": "CHF","maxCreditAllowed": 5000,"skipFraudCheck": true,"customerIdentification": "CONFIRMED"}');

  dbms_output.put_line( 'currency value: `' || l_json.get('currency').to_char || '`' );

  dbms_output.put_line( '' );
  dbms_output.put_line( '' );
  l_json.print;
  dbms_output.put_line( '' );
  dbms_output.put_line( '' );

  l_xml := json_xml.json_to_xml(l_json);
  l_clob := l_xml.getstringval;
  dbms_output.put_line(l_clob);
END;
/
```

Please run that script and then copy and paste the _exact_ output into a reply using a code block. I want to see every single line of the `dbms_output`.

**Comment by pmalera** [comment]
Here is the output :
```
SQL> 
SET SERVEROUTPUT ON;
DECLARE
  l_json json;
  l_xml  XMLTYPE;
  l_clob CLOB;
BEGIN
  l_json := json('{"currency": "CHF","maxCreditAllowed": 5000,"skipFraudCheck": true,"customerIdentification": "CONFIRMED"}');
  dbms_output.put_line( 'currency value: `' || l_json.get('currency').to_char || '`' );
  dbms_output.put_line( '' );
  dbms_output.put_line( '' );
  l_json.print;
  dbms_output.put_line( '' );
  dbms_output.put_line( '' );
  l_xml := json_xml.json_to_xml(l_json);
  l_clob := l_xml.getstringval;
  dbms_output.put_line(l_clob);
END;
/
currency value: `"CHF"`


{
  "currency" : "CHF",
  "maxCreditAllowed" : 5000,
  "skipFraudCheck" : true,
  "customerIdentification" : "CONFIRMED"
}


<?xml version="1.0"?><root><currency>&quot;CHF&quot;</currency><maxCreditAllowed>5000</maxCreditAllowed><skipFraudCheck>true</skipFraudCheck><customerIdentification>&quot;CONFIRMED&quot;</customerIdentification></root>
PL/SQL procedure successfully completed

**Comment by jsumners** [comment]
Thank you. That is definitely unexpected behavior. I'll dig in an see what I can find.

**Comment by boriborm** [comment]
You need change code for line 137 from
`add_to_clob(xmlstr, xmlbuf, '<' || tagname || '>'||escapeStr(obj.to_char())||'</' || tagname || '>');`
to
`add_to_clob(xmlstr, xmlbuf, '<' || tagname || '>'||escapeStr(obj.to_json_value().value_of())||'</' || tagname || '>');`

**Comment by jsumners** [comment]
@pmalera I have just merged @boriborm's pull request #21 that is supposed to solve this issue. Could you please test it and report your results?

**Comment by pmalera** [comment]
This work fine now :smiley: 
Thanks a lot  :thumbsup:

**Comment by jsumners** [comment]
@pmalera thank you for confirming.
