### ISSUE TITLE
json_value to_clob gives ORA-06502 (numeric or value error: character string buffer too small)

### ISSUE THREAD

**Issue by PimJanissen** [pljson/pljson#160]
I have a large clob value (around 35000 chars) which I'm retrieving from a REST api. Then I try to get the value from the JSON returned by the REST call and put it in a clob.

I use the following code:

![image](https://user-images.githubusercontent.com/14105644/49088514-b8b9de00-f259-11e8-8223-ac6095e8a301.png)

The error is as follows: ORA-06502: PL/SQL: numeric or value error: character string buffer too small Error Backtrace: ORA-06512: at "PLJSON.JSON_PRINTER", line 47 ORA-06512: at "PLJSON.JSON_PRINTER", line 302 ORA-06512: at "PLJSON.JSON_VALUE", line 150 ORA-06512: at "ADAPTION.PKG_CAMUNDA", line 49 ORA-06512: at "ADAPTION.PKG_CAMUNDA", line 49 ORA-06512: at line 13 ORA-06512: at line 13

**Comment by boriborm** [comment]
Are you use last version of PL/JSON?

**Comment by PimJanissen** [comment]
No. It seems I am on a very old one ;)
