### ISSUE TITLE
error pljson_list 'GET' is not a procedure or is undefined

### ISSUE THREAD

**Issue by daincabpu** [pljson/pljson#163]
declare
  obj json;
  listpl pljson_list;
  listpl2 pljson_list;
   v_dia varchar2(500):= '';
   v_horario_id integer:= 0;
   v_segmento_numero integer:= 0;
begin

    listpl := pljson_list('[[{"id":1,"nombre":"name 1"},{"id":1,"nombre":"name 1"}],[{"id":2,"nombre":"name 2"},{"id":1,"nombre":"name 1"}]]');
    listpl.print;
    DBMS_OUTPUT.PUT_LINE('-----------');
    FOR i IN 1..listpl.count LOOP
        v_dia := '';
        v_horario_id := 0;
        v_segmento_numero := v_segmento_numero+1;
        
        listpl2 := pljson_list(listpl.get(i));
        listpl2.print;
    
        FOR j IN 1..listpl2.count LOOP
            listpl2.get(j);  --error
            DBMS_OUTPUT.PUT_LINE('-----------');
            DBMS_OUTPUT.PUT_LINE(j);
            --listpl2.get(i).print; 
            /*
            v_dia = (j->>'dia')::text;
            v_horario_id = (j->>'horario_id')::INTEGER;
            SELECT v_dia, v_horario_id,v_segmento_numero;
            */
        END LOOP;
    END LOOP;
    
end;

ORA-06550: line 22, column 13:
PLS-00221: 'GET' is not a procedure or is undefined
ORA-06550: line 22, column 13:
PL/SQL: Statement ignored

**Comment by dsnz** [comment]
hi,

**get()** is a function and so the result should be used or assigned

I have changed your code to work and extended it with some more code to print the json content.
All changes are inside ```-- begin change``` and ```-- end change``` comments


```
declare
obj json;
listpl pljson_list;
listpl2 pljson_list;
-- begin change, new variable
el pljson;
-- end change
v_dia varchar2(500):= '';
v_horario_id integer:= 0;
v_segmento_numero integer:= 0;
begin

-- begin change, better example
listpl := pljson_list('[[{"id":11,"nombre":"name 11"},{"id":12,"nombre":"name 12"}],[{"id":21,"nombre":"name 21"},{"id":22,"nombre":"name 22"}]]');
-- end change
listpl.print;
DBMS_OUTPUT.PUT_LINE('-----------');
FOR i IN 1..listpl.count LOOP
    v_dia := '';
    v_horario_id := 0;
    v_segmento_numero := v_segmento_numero+1;
    
    listpl2 := pljson_list(listpl.get(i));
    listpl2.print;

    FOR j IN 1..listpl2.count LOOP
        -- begin change, modification and new code
        el := pljson(listpl2.get(j));  --error
        dbms_output.put_line(el.get_number('id') || ' => ' || el.get_string('nombre'));
        -- end change
        DBMS_OUTPUT.PUT_LINE('-----------');
        DBMS_OUTPUT.PUT_LINE(j);
        --listpl2.get(i).print; 
        /*
        v_dia = (j->>'dia')::text;
        v_horario_id = (j->>'horario_id')::INTEGER;
        SELECT v_dia, v_horario_id,v_segmento_numero;
        */
    END LOOP;
END LOOP;
end;
```
