### ISSUE TITLE
pljson_table.json_table ORA-00932

### ISSUE THREAD

**Issue by WoodG0b1in** [pljson/pljson#164]
Hello. Can you explain why this code get error ORA-00932: inconsistent datatypes: expected - got -?

CREATE OR REPLACE TYPE "FLD_T"  as object(
    item    varchar2(50),
    val     varchar2(2000),
    label   varchar2(100),
    type    varchar2(1),
    tmpl    varchar2(25),
    visible number,
    operand number);
/
CREATE OR REPLACE TYPE "FLD_TBL" as table of FLD_T;
/

declare 
  clob#pMap clob := '[{"item":"emp_id","val":"1","labal":"test","type":"V","tmpl":"123","visible":1,"operand":1}]';
begin
    for r$r in (
         select item, val from table(cast(
                pljson_table.json_table(clob#pMap,
                  pljson_varray('[*].item','[*].val','[*].label','[*].type','[*].tmpl','[*].visible','[*].operand'),
                  pljson_varray('item','val','label','type','tmpl','visible','operand'),
                  table_mode=>'nested') as FLD_TBL)))
     loop
        dbms_output.put_line(r$r.item);
     end loop;
  
end;

**Comment by boriborm** [comment]
Mistake in your example.
....,"labal":" test",....
Maybe "label"?

**Comment by WoodG0b1in** [comment]
Sorry, but it don't solve problem

**Comment by WoodG0b1in** [comment]
declare
clob#pMap clob := '[{"item":"emp_id","val":"1","label":"test","type":"V","tmpl":"123","visible":1,"operand":1}]';
begin
  
for r$r in (
select item, val from table(cast(
pljson_table.json_table(clob#pMap,
pljson_varray('[].item','[].val','[].label','[].type','[].tmpl','[].visible','[*].operand'),
pljson_varray('item','val','label','type','tmpl','visible','operand'),
table_mode=>'nested') as FLD_TBL)))
loop
dbms_output.put_line(r$r.item);
end loop;

exception
  when others then
    dbms_output.put_line(sqlerrm);
end;

ORA-00932: inconsistent datatypes: expected - got -

**Comment by dsnz** [comment]
Hi,

first, you can't use CAST() in that place, TABLE(CAST(...)) idiom is for Oracle collections
second, there is an Oracle bug/feature that has been mentioned often in issues (issues #161 and #58) that makes use of pljson_table functionality a bit more involved in PL/SQL (but not impossible)
below you can see your code modified to work correctly (this is just one style of modification which uses a record and is easier I think; another style would use individual variables)

```
declare
  clob#pMap clob := '[{"item":"emp_id","val":"1","label":"test","type":"V","tmpl":"123","visible":1,"operand":1}]';
  v_stat varchar2(1000) := q'{
select *
from table(
  pljson_table.json_table(
    :json_str,
    pljson_varray('[*].item','[*].val','[*].label','[*].type','[*].tmpl','[*].visible','[*].operand'),
    pljson_varray('item','val','label','type','tmpl','visible','operand'),
    table_mode=>'nested'
  )
)
}';
type t_fld is record (
  item varchar2(50),
  val varchar2(2000),
  label varchar2(100),
  type varchar2(1),
  tmpl varchar2(25),
  visible number,
  operand number
);
c SYS_REFCURSOR;
v_rec t_fld;
BEGIN
  open c for v_stat using clob#pMap;
  loop
    fetch c INTO v_rec;
    exit when c%NOTFOUND;
    dbms_output.put_line(v_rec.item);
  end loop;
  close c;
exception
  when others then
    dbms_output.put_line(sqlerrm);
end;
```

**Comment by WoodG0b1in** [comment]
Thanks
