### ISSUE TITLE
[Err] ORA-00910: specified length too long for its datatype

### ISSUE THREAD

**Issue by daincabpu** [pljson/pljson#168]
buenos dias:
este es mi codigo 

`DECLARE`
`	p_json_agendas clob;`
`	p_agendas_ids clob :='739634';`
`	rd_agd_marc tab_jsnsincagdmov;`
`	p_sql clob;`
`BEGIN`
`--con este json no funciona `
`--/*`
`p_json_agendas :=`
`'[{"ID":53338,"fin_planificado":"2019-06-15 06:00:00","inicio_planificado":"2019-06-14 22:00:00","agenda_id":"739634","fin_real":"2019-06-15 06:09:00","fin_registrado_por":2,"fin_real_sincronizado":true,"horario_id":75,"tiempo_extra":13440,"inicio_real":"2019-06-14 17:16:00","inicio_registrado_por":2,"inicio_real_sincronizado":true,"intervalo_id":39,"marcacion_fin_habilitado":true,"marcacion_inicio_habilitado":true,"persona_id":3817,"tareas":"[{ \"tarea_id\" : \"000000000000000-1560546341374-53\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"89 | Capacitación\", \"tarea_fecha_creacion\":\"2019-06-14 16:05:41\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\", \"duracion\":7200, \"centrocosto_id\":null, \"labor_id\":null, \"zona_id\":96, \"campo_id\":null, \"jiron_id\":null, \"cuartel_id\":null, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"89 | Capacitación\", \"inicio\":\"2019-06-14 17:16:00\", \"termino\":\"2019-06-14 19:16:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546594892-57\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"Descanso Compensatorio\", \"tarea_fecha_creacion\":\"2019-06-14 16:09:54\", \"excepcion_id\":\"000000000000000-1560546594930-61\", \"tipoexcepcion_id\":\"76\", \"excepcion_nombre\":\"Descanso Compensatorio\", \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":3817, \"configuracionexcepcion_id\":\"000000000000000-1560546594905-61\", \"excepcion_tipoexcepcion_id\":76, \"excepcion_usuariocreador_id\":419, \"agenda_id\":\"739634\", \"duracion\":14400, \"centrocosto_id\":null, \"labor_id\":null, \"zona_id\":96, \"campo_id\":null, \"jiron_id\":null, \"cuartel_id\":null, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"Descanso Compensatorio\", \"inicio\":\"2019-06-14 22:00:00\", \"termino\":\"2019-06-15 02:00:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546406872-54\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"0 | Operación - Presupuesto\", \"tarea_fecha_creacion\":\"2019-06-14 16:06:46\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\",'||`
`' \"duracion\":9840, \"centrocosto_id\":1, \"labor_id\":965, \"zona_id\":96, \"campo_id\":14256, \"jiron_id\":14676, \"cuartel_id\":1, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"0 | Operación - Presupuesto\", \"inicio\":\"2019-06-14 19:16:00\", \"termino\":\"2019-06-14 22:00:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546607649-58\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"0 | Operación - Presupuesto\", \"tarea_fecha_creacion\":\"2019-06-14 16:10:07\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\", \"duracion\":14400, \"centrocosto_id\":1, \"labor_id\":965, \"zona_id\":96, \"campo_id\":14256, \"jiron_id\":14676, \"cuartel_id\":1, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"0 | Operación - Presupuesto\", \"inicio\":\"2019-06-15 02:00:00\", \"termino\":\"2019-06-15 06:00:00\", \"estado\":1}]","ticket_id":"000000000000000-1560544770494-42","tiempo_he_refrigerio":3600,"tiempo_por_compensar":0}]';`
`--*/`
`--con este json si funciona `
`/*`
`p_json_agendas :='[{"ID":2511,"fin_planificado":"2019-06-14 13:00:00","inicio_planificado":"2019-06-14 07:00:00","agenda_id":"738275","fin_real":"2019-06-14 13:11:00","fin_registrado_por":2,"fin_real_sincronizado":true,"horario_id":156,"tiempo_extra":0,"inicio_real":"2019-06-14 06:58:00","inicio_registrado_por":2,"inicio_real_sincronizado":true,"intervalo_id":275,"marcacion_fin_habilitado":true,"marcacion_inicio_habilitado":true,"persona_id":8489,"tareas":"[{ \"tarea_id\" : \"000000000000000-1560540918223-1\", \"ticket_id\":\"000000000000000-1560540918197-3\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":8489, \"ticket_fecha_creacion\":\"2019-06-14 14:35:18\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":8489, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"310 | Riego por Goteo\", \"tarea_fecha_creacion\":\"2019-06-14 14:35:18\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"738275\", \"duracion\":21600, \"centrocosto_id\":19, \"labor_id\":1056, \"zona_id\":125, \"campo_id\":21186, \"jiron_id\":15184, \"cuartel_id\":7147, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"310 | Riego por Goteo\", \"inicio\":\"2019-06-14 07:00:00\", \"termino\":\"2019-06-14 13:00:00\", \"estado\":1}]","ticket_id":"000000000000000-1560540918197-3","tiempo_he_refrigerio":0,"tiempo_por_compensar":0}]';`
`p_agendas_ids :='738275';`
`--*/`
`p_sql := '`
`        SELECT`
`            rec_jsnsincagdmov`
`            (`
`                tmp.id,`
`                tmp.agenda_id,`
`                tmp.intervalo_id,`
`                tmp.persona_id,`
`                tmp.ticket_id,`
`                tmp.marcacion_inicio_habilitado,`
`                tmp.marcacion_fin_habilitado,`
`                tmp.horario_id,`
`                tmp.inicio_real,`
`                tmp.fin_real,`
`                tmp.inicio_planificado,`
`                tmp.fin_planificado,`
`                tmp.inicio_registrado_por,`
`                tmp.fin_registrado_por,`
`                tmp.inicio_real_sincronizado,`
`                tmp.fin_real_sincronizado,`
`                tmp.tiempo_por_compensar,`
`                tmp.tiempo_extra,`
`                tmp.tiempo_he_refrigerio,`
`                tmp.inicio_lab_dso,`
`                tmp.fin_lab_dso,`
`                tmp.cortes,`
`                tmp.tareas`
`            )`
`        FROM `
`        (`
`            SELECT    `
`                tmp.id,`
`                tmp.agenda_id,`
`                tmp.intervalo_id,`
`                tmp.persona_id,`
`                tmp.ticket_id,`
`                case when lower(to_char(tmp.marcacion_inicio_habilitado)) = ''true'' then 1 else 0 end as marcacion_inicio_habilitado,`
`                case when lower(to_char(tmp.marcacion_fin_habilitado)) = ''true'' then 1 else 0 end  as marcacion_fin_habilitado,`
`                tmp.horario_id,`
`                CASE WHEN tmp.inicio_real IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.inicio_real,''YYYY-MM-DD HH24:MI:SS'') END AS inicio_real,`
`                CASE WHEN tmp.fin_real IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.fin_real,''YYYY-MM-DD HH24:MI:SS'') END AS fin_real,`
`                CASE WHEN tmp.inicio_planificado IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.inicio_planificado,''YYYY-MM-DD HH24:MI:SS'') END AS inicio_planificado,`
`                CASE WHEN tmp.fin_planificado IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.fin_planificado,''YYYY-MM-DD HH24:MI:SS'') END AS fin_planificado,`
`                tmp.inicio_registrado_por,`
`                tmp.fin_registrado_por,`
`                case when lower(to_char(tmp.inicio_real_sincronizado)) = ''true'' then 1 else 0 end as inicio_real_sincronizado,`
`                case when lower(to_char(tmp.fin_real_sincronizado)) = ''true'' then 1 else 0 end  as fin_real_sincronizado,`
`                tmp.tiempo_por_compensar,`
`                tmp.tiempo_extra,`
`                tmp.tiempo_he_refrigerio,`
`                CASE WHEN tmp.inicio_lab_dso IS NULL THEN NULL ELSE tmp.inicio_lab_dso /*TO_TIMESTAMP(tmp.inicio_lab_dso,''0 HH24:MI:SS'')*/ END AS inicio_lab_dso,`
`                CASE WHEN tmp.fin_lab_dso IS NULL THEN NULL ELSE tmp.inicio_lab_dso/* TO_TIMESTAMP(tmp.fin_lab_dso,''0 HH24:MI:SS'') */ END AS fin_lab_dso,`
`                tmp.cortes,`
`                tmp.tareas`
`            FROM`
`            table( pljson_table.json_table(`
`                :p_json_agendas,`
`                pljson_varray(''[*].ID'',''[*].agenda_id'', ''[*].intervalo_id'', ''[*].persona_id'', ''[*].ticket_id'', ''[*].marcacion_inicio_habilitado'', ''[*].marcacion_fin_habilitado'',`
`                 ''[*].horario_id'', ''[*].inicio_real'', ''[*].fin_real'', ''[*].inicio_planificado'', ''[*].fin_planificado'', ''[*].inicio_registrado_por'', ''[*].fin_registrado_por'',`
`                 ''[*].inicio_real_sincronizado'', ''[*].fin_real_sincronizado'', ''[*].tiempo_por_compensar'', ''[*].tiempo_extra'', ''[*].tiempo_he_refrigerio'', ''[*].inicio_lab_dso'', ''[*].fin_lab_dso'',`
`                 ''[*].cortes'', ''[*].tareas''),`
`                pljson_varray(''id'',''agenda_id'', ''intervalo_id'', ''persona_id'', ''ticket_id'', ''marcacion_inicio_habilitado'', ''marcacion_fin_habilitado'',`
`                 ''horario_id'', ''inicio_real'', ''fin_real'', ''inicio_planificado'', ''fin_planificado'', ''inicio_registrado_por'', ''fin_registrado_por'',`
`                 ''inicio_real_sincronizado'', ''fin_real_sincronizado'', ''tiempo_por_compensar'', ''tiempo_extra'', ''tiempo_he_refrigerio'', ''inicio_lab_dso'', ''fin_lab_dso'',`
`                 ''cortes'', ''tareas''),`
`                table_mode => ''nested''`
`            )) tmp`
`            WHERE`
`                tmp.agenda_id IN (SELECT TO_NUMBER(tmp.val) FROM TABLE(CLOB_TO_TABLE(:p_agendas_ids, '','')) tmp ) OR isnumeric(tmp.agenda_id) = 0`
`            order by tmp.id`
`        ) tmp`
`    ';`
`EXECUTE IMMEDIATE`
`    p_sql`
`    BULK COLLECT INTO rd_agd_marc `
`    USING p_json_agendas,p_agendas_ids;`
`/*`
`	FOR i IN rd_agd_marc.FIRST..rd_agd_marc.LAST`
`	LOOP`
`	END LOOP;`
`*/`
`end;`
y me sale este error

`[Err] ORA-00910: specified length too long for its datatype
ORA-06512: at line 93`

he intentado de muchas manera poder solucionarlo pero no he podido.

Gracias.

**Comment by dsnz** [comment]
I' m sorry, I can't run this and understand if there is a PLJSON bug because it does not compile. Type "tab_jsnsincagdmov" is not defined.

**Comment by daincabpu** [comment]
Disculpe, este es el codigo completo:

`CREATE OR REPLACE`
`TYPE       REC_JSNSINCAGDMOV as object (`
`    id INTEGER,`
`    agenda_id VARCHAR2(100),`
`    intervalo_id INTEGER,`
`    persona_id INTEGER,`
`    ticket_id VARCHAR2(100),`
`    marcacion_inicio_habilitado INTEGER,`
`    marcacion_fin_habilitado INTEGER,`
`    horario_id INTEGER  ,`
`    inicio_real TIMESTAMP  ,`
`    fin_real TIMESTAMP  ,`
`    inicio_planificado TIMESTAMP ,`
`    fin_planificado TIMESTAMP,`
`    inicio_registrado_por INTEGER,`
`    fin_registrado_por INTEGER,`
`    inicio_real_sincronizado INTEGER,`
`    fin_real_sincronizado INTEGER ,`
`    tiempo_por_compensar INTEGER ,`
`    tiempo_extra INTEGER ,`
`    tiempo_he_refrigerio INTEGER ,`
`    inicio_lab_dso INTERVAL DAY TO SECOND ,`
`    fin_lab_dso INTERVAL DAY TO SECOND ,`
`    cortes clob,`
`    tareas clob`
`);`
`/`
``
`CREATE OR REPLACE`
`TYPE TAB_JSNSINCAGDMOV as TABLE OF rec_jsnsincagdmov;`
`/`

`DECLARE`
`	p_json_agendas clob;`
`	p_agendas_ids clob :='739634';`
`	rd_agd_marc tab_jsnsincagdmov;`
`	p_sql clob;`
`BEGIN`
`--con este json no funciona `
`--/*`
`p_json_agendas :=`
`'[{"ID":53338,"fin_planificado":"2019-06-15 06:00:00","inicio_planificado":"2019-06-14 22:00:00","agenda_id":"739634","fin_real":"2019-06-15 06:09:00","fin_registrado_por":2,"fin_real_sincronizado":true,"horario_id":75,"tiempo_extra":13440,"inicio_real":"2019-06-14 17:16:00","inicio_registrado_por":2,"inicio_real_sincronizado":true,"intervalo_id":39,"marcacion_fin_habilitado":true,"marcacion_inicio_habilitado":true,"persona_id":3817,"tareas":"[{ \"tarea_id\" : \"000000000000000-1560546341374-53\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"89 | Capacitación\", \"tarea_fecha_creacion\":\"2019-06-14 16:05:41\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\", \"duracion\":7200, \"centrocosto_id\":null, \"labor_id\":null, \"zona_id\":96, \"campo_id\":null, \"jiron_id\":null, \"cuartel_id\":null, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"89 | Capacitación\", \"inicio\":\"2019-06-14 17:16:00\", \"termino\":\"2019-06-14 19:16:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546594892-57\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"Descanso Compensatorio\", \"tarea_fecha_creacion\":\"2019-06-14 16:09:54\", \"excepcion_id\":\"000000000000000-1560546594930-61\", \"tipoexcepcion_id\":\"76\", \"excepcion_nombre\":\"Descanso Compensatorio\", \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":3817, \"configuracionexcepcion_id\":\"000000000000000-1560546594905-61\", \"excepcion_tipoexcepcion_id\":76, \"excepcion_usuariocreador_id\":419, \"agenda_id\":\"739634\", \"duracion\":14400, \"centrocosto_id\":null, \"labor_id\":null, \"zona_id\":96, \"campo_id\":null, \"jiron_id\":null, \"cuartel_id\":null, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"Descanso Compensatorio\", \"inicio\":\"2019-06-14 22:00:00\", \"termino\":\"2019-06-15 02:00:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546406872-54\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"0 | Operación - Presupuesto\", \"tarea_fecha_creacion\":\"2019-06-14 16:06:46\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\",'||`
`' \"duracion\":9840, \"centrocosto_id\":1, \"labor_id\":965, \"zona_id\":96, \"campo_id\":14256, \"jiron_id\":14676, \"cuartel_id\":1, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"0 | Operación - Presupuesto\", \"inicio\":\"2019-06-14 19:16:00\", \"termino\":\"2019-06-14 22:00:00\", \"estado\":1},{ \"tarea_id\" : \"000000000000000-1560546607649-58\", \"ticket_id\":\"000000000000000-1560544770494-42\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":3817, \"ticket_fecha_creacion\":\"2019-06-14 15:39:30\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":3817, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"0 | Operación - Presupuesto\", \"tarea_fecha_creacion\":\"2019-06-14 16:10:07\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"739634\", \"duracion\":14400, \"centrocosto_id\":1, \"labor_id\":965, \"zona_id\":96, \"campo_id\":14256, \"jiron_id\":14676, \"cuartel_id\":1, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"0 | Operación - Presupuesto\", \"inicio\":\"2019-06-15 02:00:00\", \"termino\":\"2019-06-15 06:00:00\", \"estado\":1}]","ticket_id":"000000000000000-1560544770494-42","tiempo_he_refrigerio":3600,"tiempo_por_compensar":0}]';`
`--*/`
`--con este json si funciona `
`/*`
`p_json_agendas :='[{"ID":2511,"fin_planificado":"2019-06-14 13:00:00","inicio_planificado":"2019-06-14 07:00:00","agenda_id":"738275","fin_real":"2019-06-14 13:11:00","fin_registrado_por":2,"fin_real_sincronizado":true,"horario_id":156,"tiempo_extra":0,"inicio_real":"2019-06-14 06:58:00","inicio_registrado_por":2,"inicio_real_sincronizado":true,"intervalo_id":275,"marcacion_fin_habilitado":true,"marcacion_inicio_habilitado":true,"persona_id":8489,"tareas":"[{ \"tarea_id\" : \"000000000000000-1560540918223-1\", \"ticket_id\":\"000000000000000-1560540918197-3\", \"ticket_sincronizado\":0, \"ticket_usuariocreador_id\":419, \"ticket_registrado_por\":1, \"ticket_propietario_id\":8489, \"ticket_responsable_id\":8489, \"ticket_fecha_creacion\":\"2019-06-14 14:35:18\", \"tarea_sincronizado\":0, \"tarea_registrado_por\":1, \"tarea_propietario_id\":8489, \"tarea_responsable_id\":8489, \"tarea_usuariocreador_id\":419, \"tarea_nombre\":\"310 | Riego por Goteo\", \"tarea_fecha_creacion\":\"2019-06-14 14:35:18\", \"excepcion_id\":\"0\", \"tipoexcepcion_id\":\"0\", \"excepcion_nombre\":null, \"fecha_hora_inicio\":null, \"fecha_hora_fin\":null, \"excepcion_fecha_creacion\":null, \"excepcion_persona_id\":null, \"configuracionexcepcion_id\":null, \"excepcion_tipoexcepcion_id\":null, \"excepcion_usuariocreador_id\":null, \"agenda_id\":\"738275\", \"duracion\":21600, \"centrocosto_id\":19, \"labor_id\":1056, \"zona_id\":125, \"campo_id\":21186, \"jiron_id\":15184, \"cuartel_id\":7147, \"personacliente_id\":null, \"personasede_id\":null, \"personaarea_id\":null, \"costo_id\":null, \"tercios\":0, \"cosecha\":0, \"nombre\":\"310 | Riego por Goteo\", \"inicio\":\"2019-06-14 07:00:00\", \"termino\":\"2019-06-14 13:00:00\", \"estado\":1}]","ticket_id":"000000000000000-1560540918197-3","tiempo_he_refrigerio":0,"tiempo_por_compensar":0}]';`
`p_agendas_ids :='738275';`
`--*/`
`p_sql := '`
`        SELECT`
`            rec_jsnsincagdmov`
`            (`
`                tmp.id,`
`                tmp.agenda_id,`
`                tmp.intervalo_id,`
`                tmp.persona_id,`
`                tmp.ticket_id,`
`                tmp.marcacion_inicio_habilitado,`
`                tmp.marcacion_fin_habilitado,`
`                tmp.horario_id,`
`                tmp.inicio_real,`
`                tmp.fin_real,`
`                tmp.inicio_planificado,`
`                tmp.fin_planificado,`
`                tmp.inicio_registrado_por,`
`                tmp.fin_registrado_por,`
`                tmp.inicio_real_sincronizado,`
`                tmp.fin_real_sincronizado,`
`                tmp.tiempo_por_compensar,`
`                tmp.tiempo_extra,`
`                tmp.tiempo_he_refrigerio,`
`                tmp.inicio_lab_dso,`
`                tmp.fin_lab_dso,`
`                tmp.cortes,`
`                tmp.tareas`
`            )`
`        FROM `
`        (`
`            SELECT    `
`                tmp.id,`
`                tmp.agenda_id,`
`                tmp.intervalo_id,`
`                tmp.persona_id,`
`                tmp.ticket_id,`
`                case when lower(to_char(tmp.marcacion_inicio_habilitado)) = ''true'' then 1 else 0 end as marcacion_inicio_habilitado,`
`                case when lower(to_char(tmp.marcacion_fin_habilitado)) = ''true'' then 1 else 0 end  as marcacion_fin_habilitado,`
`                tmp.horario_id,`
`                CASE WHEN tmp.inicio_real IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.inicio_real,''YYYY-MM-DD HH24:MI:SS'') END AS inicio_real,`
`                CASE WHEN tmp.fin_real IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.fin_real,''YYYY-MM-DD HH24:MI:SS'') END AS fin_real,`
`                CASE WHEN tmp.inicio_planificado IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.inicio_planificado,''YYYY-MM-DD HH24:MI:SS'') END AS inicio_planificado,`
`                CASE WHEN tmp.fin_planificado IS NULL THEN NULL ELSE TO_TIMESTAMP(tmp.fin_planificado,''YYYY-MM-DD HH24:MI:SS'') END AS fin_planificado,`
`                tmp.inicio_registrado_por,`
`                tmp.fin_registrado_por,`
`                case when lower(to_char(tmp.inicio_real_sincronizado)) = ''true'' then 1 else 0 end as inicio_real_sincronizado,`
`                case when lower(to_char(tmp.fin_real_sincronizado)) = ''true'' then 1 else 0 end  as fin_real_sincronizado,`
`                tmp.tiempo_por_compensar,`
`                tmp.tiempo_extra,`
`                tmp.tiempo_he_refrigerio,`
`                CASE WHEN tmp.inicio_lab_dso IS NULL THEN NULL ELSE tmp.inicio_lab_dso /*TO_TIMESTAMP(tmp.inicio_lab_dso,''0 HH24:MI:SS'')*/ END AS inicio_lab_dso,`
`                CASE WHEN tmp.fin_lab_dso IS NULL THEN NULL ELSE tmp.inicio_lab_dso/* TO_TIMESTAMP(tmp.fin_lab_dso,''0 HH24:MI:SS'') */ END AS fin_lab_dso,`
`                tmp.cortes,`
`                tmp.tareas`
`            FROM`
`            table( pljson_table.json_table(`
`                :p_json_agendas,`
`                pljson_varray(''[*].ID'',''[*].agenda_id'', ''[*].intervalo_id'', ''[*].persona_id'', ''[*].ticket_id'', ''[*].marcacion_inicio_habilitado'', ''[*].marcacion_fin_habilitado'',`
`                 ''[*].horario_id'', ''[*].inicio_real'', ''[*].fin_real'', ''[*].inicio_planificado'', ''[*].fin_planificado'', ''[*].inicio_registrado_por'', ''[*].fin_registrado_por'',`
`                 ''[*].inicio_real_sincronizado'', ''[*].fin_real_sincronizado'', ''[*].tiempo_por_compensar'', ''[*].tiempo_extra'', ''[*].tiempo_he_refrigerio'', ''[*].inicio_lab_dso'', ''[*].fin_lab_dso'',`
`                 ''[*].cortes'', ''[*].tareas''),`
`                pljson_varray(''id'',''agenda_id'', ''intervalo_id'', ''persona_id'', ''ticket_id'', ''marcacion_inicio_habilitado'', ''marcacion_fin_habilitado'',`
`                 ''horario_id'', ''inicio_real'', ''fin_real'', ''inicio_planificado'', ''fin_planificado'', ''inicio_registrado_por'', ''fin_registrado_por'',`
`                 ''inicio_real_sincronizado'', ''fin_real_sincronizado'', ''tiempo_por_compensar'', ''tiempo_extra'', ''tiempo_he_refrigerio'', ''inicio_lab_dso'', ''fin_lab_dso'',`
`                 ''cortes'', ''tareas''),`
`                table_mode => ''nested''`
`            )) tmp`
`            WHERE`
`                tmp.agenda_id IN (SELECT TO_NUMBER(tmp.val) FROM TABLE(CLOB_TO_TABLE(:p_agendas_ids, '','')) tmp ) OR isnumeric(tmp.agenda_id) = 0`
`            order by tmp.id`
`        ) tmp`
`    ';`
`EXECUTE IMMEDIATE`
`    p_sql`
`    BULK COLLECT INTO rd_agd_marc `
`    USING p_json_agendas,p_agendas_ids;`
`/*`
`	FOR i IN rd_agd_marc.FIRST..rd_agd_marc.LAST`
`	LOOP`
`	END LOOP;`
`*/`
`end;`


Gracias

**Comment by jsumners** [comment]
@daincabpu you need to post a _short_ description of your problem. Preferably in english. We are unable to dig through these large chunks of code to decipher whatever problem you have having.

**Comment by dsnz** [comment]
Hi,

As James said, it's good that you post the absolutely shortest code that demonstrates a problem.
This is the mandatory in posting an issue for support everywhere (Oracle for example will not accept this at all and will close the SR immediately :D).
In your case the error you get does not seem to be from PLJSON but rather from your code.
I suggest that you shorten the json text for example to the minimum essential, ie. keep the structure but reduce the text to single letters and numbers to single digit numbers and also remove all the case code and any processing you do and give us something small, standalone, and simple to understand.

Yet, I tried to run it (we are not Oracle, we are PLJSON :D) and still cannot compile because it misses

```
isnumeric
```

at line 90 !
