### ISSUE TITLE
PLJSON_TABLE Example Fails with "ORA-06530: Reference to uninitialized composite" Error

### ISSUE THREAD

**Issue by dracozombie19** [pljson/pljson#170]
I just installed branch develop_v3 into an 11.2.0.4.0 Oracle DB and tried to run this example from the readme:

```
select * from table(pljson_table.json_table(
  '[{ "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));
```

When I run that, I am getting the following error:

![image](https://user-images.githubusercontent.com/33298283/62396215-16799500-b562-11e9-88d7-44fee96cbfb1.png)

If I change the example to use a JSON object instead of an array at the root level, it works fine.

```
select * from table(pljson_table.json_table(
  '{ "data":[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]}',
  pljson_varray('data[*].id', 'data[*].displayname', 'data[*].qty', 'data[*].extras[*].xid', 'data[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));
```

Is this a bug with PL/JSON code, or a bug with the readme/example?  Or possibly something else?

**Comment by dsnz** [comment]
Hi,

Both run okay in v 2.0. I saw the error as you described in v 3.0. It gives the impression that it is a bug in PLJSON, but let me a few days to check this as I am working on another issue now.

**Comment by dsnz** [comment]
Hi,

It's a bug and now it's fixed and a test case to catch it was added in our testsuite.

Please, reinstall branch develop_v3 (I cannot make a new release now as I will be making some more commits next week and then there will be a new release),
and give feedback if the issue is solved.

**Comment by dsnz** [comment]
@dracozombie19  don't forget to give feedback here as soon as possible

**Comment by dracozombie19** [comment]
Apologies, I've had some higher priority stuff come in at work this week, so I haven't had a chance to try this.  I'm going to try and get to it this week.

**Comment by dracozombie19** [comment]
I finally got a chance to try this out.  I installed the newest version into our Dev database and tried that example again.  It worked!  Thanks for the quick turnaround on this.
