### ISSUE TITLE
Ignore Missing JSON lists

### ISSUE THREAD

**Issue by Roill** [pljson/pljson#173]
Hello,

I am trying to use pljson_table.json_table to parse some JSON and write it to a type. However, the JSON I am trying to parse has some issues when a list specified with a [*] is not present within the JSON.

For example, here is the query I am trying to execute (replace v_json with JSON below):

`SELECT *
 FROM TABLE(pljson_table.json_table(:v_json,
                                    pljson_varray('Acknowledge.Type',
                                                  'Acknowledge.Code',
                                                  'Acknowledge.Message',
                                                  'Acknowledge.SequenceNumber',
                                                  'FieldService.ServiceRequest.RequestNumber',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.StatusType',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.Status',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.CommitDate',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.NoAssignReasons',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.BillingOverrideReason',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.RemainingBlockOfHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.ActualStartDateTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.ActualTimeWorked',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.ActualEndDateTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.TravelHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.PatchHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.RegularHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.OvertimeHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.PremimumHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.BillableHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.BillMinimum',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.ServiceActivityResponse.TeamId',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.Status',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.EstimatedDuration',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.MissedAppointmentReason',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ReasonInComplete',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ScheduledStartTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActualStartDateTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ScheduledEndTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActualEndDateTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActualDuration',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActualTravelTime',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActionType',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.ActionId',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.AppointmentResponse.AssignedPersonnel.MemberId',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.Hours.TypeCategory',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.Hours.TypeHours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.Hours.Hours',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.Hours.Remarks',
                                                  'FieldService.ServiceRequest.ServiceActivities[*].ServiceActivity.Appointments[*].Appointment.Hours.BillMinimum'),
                                    pljson_varray('type',
                                                  'code',
                                                  'message',
                                                  'sequence_number',
                                                  'request_number',
                                                  'status_type',
                                                  'status',
                                                  'commit_date',
                                                  'no_assign_reasons',
                                                  'billing_override_reason',
                                                  'reason',
                                                  'remaining_block_of_hours',
                                                  'actual_start_time',
                                                  'actual_time_worked',
                                                  'actual_end_time',
                                                  'travel_hours',
                                                  'patch_hours',
                                                  'reg_hours',
                                                  'ot_hours',
                                                  'prem_hours',
                                                  'billable_hours',
                                                  'bill_minimum',
                                                  'team_id',
                                                  'appt_status',
                                                  'appt_est_duration',
                                                  'appt_comp_reason',
                                                  'appt_sch_start_time',
                                                  'appt_act_start_time',
                                                  'appt_sch_end_time',
                                                  'appt_act_end_time',
                                                  'appt_act_duration',
                                                  'appt_act_travel_time',
                                                  'appt_action_type',
                                                  'appt_action_id',
                                                  'appt_member_id',
                                                  'h_type_category',
                                                  'h_type_hours',
                                                  'h_hours',
                                                  'h_remarks',
                                                  'h_bill_minimum'),
                                    table_mode => 'nested')) j`

If I provide it the JSON below, it works, because the "ServiceActivities" and "Appointments" lists are present in the JSON. 

`{
	"Header": {
		"SequenceNumber": "89452336710345829",
		"RequestorId": "AvayaFieldService",
		"ResponseId": "AvayaProfessinalService",
		"Direction": "Response",
		"RequestType": "Update"
	},
	"FieldService": {
		"ServiceRequest": {
			"RequestNumber": "05KS1360",
			"Reference": "987654",
			"ServiceActivities": [{
					"ServiceActivity": {
						"ServiceActivityResponse": {
							"StatusType": "D",
							"Status": "NW",
							"CommitDate": "2019-08-26",
							"ActivityId": "<task number>"
						},
						"Appointments": [{
							"Appointment": {
								"AppointmentResponse": {
									"Status": "Worked"
								}
							}
						}]
					}
				},
				{
					"ServiceActivity": {
						"ServiceActivityResponse": {
							"StatusType": "D",
							"Status": "NW",
							"CommitDate": "2019-08-26",
							"ActivityId": "<task number>"
						},
						"Appointments": [{
							"Appointment": {
								"AppointmentResponse": {
									"Status": "Worked"
								}
							}
						}]
					}
				}
			]
		}
	},
	"Acknowledge": {
		"SequenceNumber": "2834623834632469",
		"response": {
			"Type": "S"
		}
	}
}`

However, if I omit those lists and provide the JSON below, it throws an error:

`{
	"Header": {
		"SequenceNumber": "89452336710345829",
		"RequestorId": "AvayaFieldService",
		"ResponseId": "AvayaProfessinalService",
		"Direction": "Response",
		"RequestType": "Update"
	},
	"FieldService": {
		"ServiceRequest": {
			"RequestNumber": "05KS1360",
			"Reference": "987654"
		}
	},
	"Acknowledge": {
		"SequenceNumber": "2834623834632469",
		"response": {
			"Type": "S"
		}
	}
}
`

`ORA-06502: PL/SQL: numeric or value error
ORA-06512: at "PLJSON_LIST", line 53
ORA-06512: at "PLJSON_TABLE_IMPL", line 362
ORA-06512: at "PLJSON_TABLE_IMPL", line 472
06502. 00000 -  "PL/SQL: numeric or value error%s"
*Cause:    An arithmetic, numeric, string, conversion, or constraint error
           occurred. For example, this error occurs if an attempt is made to
           assign the value NULL to a variable declared NOT NULL, or if an
           attempt is made to assign an integer larger than 99 to a variable
           declared NUMBER(2).
*Action:   Change the data, how it is manipulated, or how it is declared so
           that values do not violate constraints.`

Is it possible to keep my query intact, but if the specified list is not present in the json, return NULL? If I change the `[*]` to `[1]`. then it works fine. However, I won't know if my lists will be present or how large they will be beforehand, so I need to use `[*]`.

**Comment by dsnz** [comment]
Hi,

I wouldn't do this at this moment because

- it is a "nested" query and your case is simple in that you have just a list and display certain fields from the objects within the list as the last columns but another user could do more complicated nested queries and it's unclear to me now how to handle these
- I would not like to touch this code risking it's correct working without more examples of what should be done in more complex queries and why this would be really useful to the users

however you seem to have a need in your application to handle cases where part of the json document is missing and I would like to suggest an approach where you check with pl/sql if the lists are present and then run an appropriate sql

the example below demonstrates this approach 

```
declare
  json_c_yes varchar2(32767) := '{ "Header": { "SequenceNumber": "89452336710345829", "RequestorId": "AvayaFieldService", "ResponseId": "AvayaProfessinalService", "Direction": "Response", "RequestType": "Update" }, "FieldService": { "ServiceRequest": { "RequestNumber": "05KS1360", "Reference": "987654", "ServiceActivities": [{ "ServiceActivity": { "ServiceActivityResponse": { "StatusType": "D", "Status": "NW", "CommitDate": "2019-08-26", "ActivityId": "<task number>" }, "Appointments": [{ "Appointment": { "AppointmentResponse": { "Status": "Worked" } } }] } }, { "ServiceActivity": { "ServiceActivityResponse": { "StatusType": "D", "Status": "NW", "CommitDate": "2019-08-26", "ActivityId": "<task number>" }, "Appointments": [{ "Appointment": { "AppointmentResponse": { "Status": "Worked" } } }] } } ] } }, "Acknowledge": { "SequenceNumber": "2834623834632469", "response": { "Type": "S" } } }';
  json_c_no  varchar2(32767) := '{ "Header": { "SequenceNumber": "89452336710345829", "RequestorId": "AvayaFieldService", "ResponseId": "AvayaProfessinalService", "Direction": "Response", "RequestType": "Update" }, "FieldService": { "ServiceRequest": { "RequestNumber": "05KS1360", "Reference": "987654" } }, "Acknowledge": { "SequenceNumber": "2834623834632469", "response": { "Type": "S" } } }';
  json_obj pljson;
  json_v pljson_value;
begin
  json_obj := pljson(json_c_yes);
  json_obj.print();
  json_v := pljson_ext.get_json_value(json_obj, 'FieldService.ServiceRequest.ServiceActivities');
  dbms_output.put_line(json_v.typeval);
  
  json_obj := pljson(json_c_no);
  json_obj.print();
  json_v := pljson_ext.get_json_value(json_obj, 'FieldService.ServiceRequest.ServiceActivities');
  dbms_output.put_line(json_v.typeval);
  if (json_v.typeval is null) then
    dbms_output.put_line('no list: FieldService');
  end if;
end;
```

**Comment by Roill** [comment]
Not ideal, but I'll make it work. Thanks for the response.
