### ISSUE TITLE
Oracle 19c - pljson 2.5.0 install script and json_value synonym

### ISSUE THREAD

**Issue by yanko** [pljson/pljson#177]
Hi PLJSONers!
we upgraded to Oracle 19c and are experiencing an issue:

When running install.sql at the end I get this:

cmd window:
Synonym created
  2  /
/* */
ORA-00900: invalid SQL statement

I basically had to press "\" enter to get it to continue.

after that I get PLS-00488: 'JSON_VALUE' must be a type
in my source code that is referring to json_value, as if the synonym in 19c is not good.

any help is appreciated!!!
thx.

**Comment by dsnz** [comment]
Hi
please within sqlplus (only, no other tool) do

```
set echo on
@install.sql
```

then post what you get at the end

(I don't see any issue in 12c and I doubt 19c is different in sqlplus as it is basically a 12c renamed)

**Comment by yanko** [comment]
You are correct!
everything executed fine. I had to do it directly on the server. Seems there is some other issue on 
my network that prevents the communications with the oracle server.

thank you for fast response.

**Comment by yanko** [comment]
actually there are some issues...

-- Setting optimize level - 

Session altered.

-----------------------------------
-- Compiling objects for PL/JSON --
-----------------------------------

PL/SQL procedure successfully completed.

No errors.

Type created.

No errors.

Type created.

No errors.

Type created.

No errors.

Type created.


Type created.


Type created.

No errors.
create or replace type pljson_varray as table of varchar2(32767);
*
ERROR at line 1:
ORA-02303: cannot drop or replace a type with type or table dependents 



Type created.

No errors.

Package created.

No errors.

Package created.

No errors.

Package body created.

No errors.

Package created.

No errors.

Package body created.

No errors.

Package body created.

No errors.

Type body created.

No errors.

Type body created.

No errors.

Type body created.

No errors.

Package created.


Package body created.

------------------------------------------
-- Adding optional packages for PL/JSON --
------------------------------------------

Package created.

No errors.

Package body created.

No errors.

Package created.

No errors.

Package body created.

No errors.

Package created.

No errors.

Package body created.

No errors.

Package created.

No errors.

Package body created.

No errors.

Package created.

No errors.

Package body created.

No errors.
create or replace type pljson_varray as table of varchar2(32767);
*
ERROR at line 1:
ORA-02303: cannot drop or replace a type with type or table dependents 


create or replace type pljson_narray as table of number;
*
ERROR at line 1:
ORA-02303: cannot drop or replace a type with type or table dependents 



Type created.


Type created.

No errors.

Synonym created.


Type body created.

No errors.
drop table pljson_testsuite
           *
ERROR at line 1:
ORA-00942: table or view does not exist 



Table created.


Package created.


Package body created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.


Synonym created.

SQL> exit

**Comment by dsnz** [comment]
Hi,

They are not real issues. These errors are due to that we run twice a drop type and we drop a table that does not exist as the script should do uninstall of an old installation before installing the new one. These are expected messages and no cause of worry.

**Comment by dsnz** [comment]
Inside the scripts we have a **termout off** command at specific places so you don't see these errors when you run **@install.sql** within **sqlplus**.

**Comment by yanko** [comment]
true! I spooled into a file.
I have this code portion of the code:
....
declare
        l_test_jv           json_value;

        l_isValidJSONObject boolean := false;
      begin
        begin
...
and I get this for the l_test_jv variable:
Compilation errors for PACKAGE BODY SOME_USER.SOMEI_PK
Error: PLS-00488: 'JSON_VALUE' must be a type
Line: 448
Text: l_test_jv           json_value;
Error: PL/SQL: Item ignored
Line: 448
Text: l_test_jv           json_value;

any idea why?

**Comment by dsnz** [comment]
in Oracle 12 and above JSON_VALUE is a function in Oracle's JSON implementation
change your code to use **pljson_value**

**Comment by yanko** [comment]
ok so the synonyms for backwards compatibility are no longer valid?
if so than it makes sense. I was hoping we would not have to change code.

thank you so much for your time.

**Comment by yanko** [comment]
I am guessing we better change the rest of the code like json to pljson too?!?

**Comment by jsumners** [comment]
Yes. The breaking changes have been posted since December of 2017 — https://github.com/pljson/pljson/releases/tag/v2.0.0

**Comment by yanko** [comment]
thank you!

**Comment by dsnz** [comment]
json_value and some other type names starting from json_  sometimes worked because well that depends on how oracle **resolves** names and how the STANDARD package is coded
but there was never a guarantee for this and keeping to use json_ names is not good practice and that's why we changed naming to **pljson_**
it seems in your case in 19c the time has come for you to change the code :)

**Comment by yanko** [comment]
no choice! not a big change, there is less than 15 pkgs using it. 
should I upgrade to 3 while at it? what's your opinion on that?
currently at 2.0.0 but I was gonna use 2.5.0 with Oracle 19c

**Comment by dsnz** [comment]
I say you should !
but 3.0 may need some changes in code, not big ones, the main is that you must forget to use pljson_value 😄 , you'd better read the 3.0 README for details
