### ISSUE TITLE
NVARCHAR2 value support in PLJSON

### ISSUE THREAD

**Issue by RenaldasKalcas** [pljson/pljson#178]
I have problem putting NVARCHAR2 value to JSON object:
`jsonObject PLJSON; 
jsonObject.put('notes', unistr('\201Ehi, note\201C'));
`
Getting result like:
`{
  "notes" : "?hi, note?"
}
`
Desired result:
`{
  "notes" : "„hi, note“"
}`
I think, that problem are internal value storing format VARCHAR2 in PLJSON.
Can you suggest some workaround?

**Comment by dsnz** [comment]
Hi,

What's the Character Set and the National Character set of your db ?

**Comment by dsnz** [comment]
and what does

```
select unistr('\201Ehi, note\201C')
from dual;
```

return for you ?

**Comment by RenaldasKalcas** [comment]
![image](https://user-images.githubusercontent.com/35802202/64672116-3eb6b680-d473-11e9-9bb0-6d050e8b31ff.png)

**Comment by RenaldasKalcas** [comment]
Database character set:
![image](https://user-images.githubusercontent.com/35802202/64672405-167b8780-d474-11e9-912d-c213c025a3ac.png)
and national character set:
![image](https://user-images.githubusercontent.com/35802202/64672567-81c55980-d474-11e9-94ad-6483b5baa130.png)

**Comment by RenaldasKalcas** [comment]
There are all db parameters:
![image](https://user-images.githubusercontent.com/35802202/64672712-e2ed2d00-d474-11e9-8c12-fd9edd79dabe.png)

**Comment by dsnz** [comment]
hi,
allow me some days to have a look at it
this is the most unusual character set combination I have ever seen
especially the AL16UTF16 !!!
it can't be a pljson issue per se but rather a byproduct of pl/sql manipulation of strings considering this strange combination of charactersets
and I can't test this myself as definitely I cannot setup a database with these settings
maybe I ask you to do some experiments and report here

**Comment by RenaldasKalcas** [comment]
Hi,
I am ready to do some experiments. :)

**Comment by dsnz** [comment]
Hi,

My tests showed no problem in creating the json, your text is preserved. So, remains to see how you use the resulting pljson object. That is, having the ```jsonObject PLJSON;``` what code do you execute and you get the wrong result as you say ?

**Comment by RenaldasKalcas** [comment]
Can you send yours test for me? I try in my database.

**Comment by dsnz** [comment]
Hi
I examined the internal contents. There is no specific test. However you can do just ```jsonObject.print()```
and see the result.
I 'd like to know, after the ```jsonObject.put('notes', unistr('\201Ehi, note\201C'));``` what code do you execute that produces wrong results ?
Also in what tool/environment do you run the code ? It seems it's not sqlplus. Can you tell the session character set too ?

**Comment by RenaldasKalcas** [comment]
Hi
Session character set is UTF16.
![image](https://user-images.githubusercontent.com/35802202/64952488-2686d300-d889-11e9-8e92-e340f68a8418.png)

**Comment by boriborm** [comment]
It's a problem of Oracle DB?
```
declare
 str nvarchar2(100):=unistr('\201E');
 str2 varchar2(200);
begin
 str2:=str;
 dbms_output.put_line(asciistr(str)); 
 dbms_output.put_line(asciistr(str2)); 
end;
```

result:
```
\201E
?
```
Oracle convert `str2:=str` incorrect?

**Comment by dsnz** [comment]
Hi,

Sorry for being a bit late but I'm sick these days.

@RenaldasKalcas 
your problem is in the use of UNISTR
Oracle Documentation says specifically that UNISTR works only with national characterset one of AL16UTF16 or UTF8

@boriborm 
I get

```
\201E
\201E
```

really getting a "?" is weird, what are your nls parameters ?

**Comment by boriborm** [comment]
@dsnz 
```
PARAMETER             	VALUE       
----------------------	------------
NLS_NCHAR_CHARACTERSET	AL16UTF16
NLS_CHARACTERSET      	CL8ISO8859P5
NLS_ISO_CURRENCY	RUSSIA
NLS_TERRITORY   	RUSSIA
NLS_LANGUAGE    	AMERICAN
```

**Comment by dsnz** [comment]
@boriborm 
hi!
I think it's logical
you have a nice **nvarchar2 str** with unicode text
and then you assign it to **varchar2 str2** which uses your **database characterset (CL8ISO8859P5)**
and of course the character cannot be converted and so Oracle replaces it with "?"

**Comment by boriborm** [comment]
Yes, it's logical.
But PL/JSON everywhere operates with variables in `varchar2` and in this way unicode chars may be incorrect converted to 1, 2 bytes charsets of DB.

Partial workaround for short json data is store escaped `nvarchar2`:
```
declare
 j pljson:=pljson();
 s nvarchar2(100):=unistr('\201Etest\\test\\test'); -- <-- table column in nvarchar2
 s2 varchar2(100);
 s3 nvarchar2(100);
begin
 j.put('s',asciistr(s)); -- <-- place escaped value of nvarchar2
 s2:= replace(j.to_char(),'\\','\'); -- <-- correct result with doubled `\`. This char may be only in string values of json
 s3:= unistr(s2);
 dbms_output.put_line(s2);
 dbms_output.put_line(s3);
end;
```

**Comment by dsnz** [comment]
I agree with you.
It's obvious due to conversions that one cannot practically handle unicode data in a single byte database.
Even with your workaround the question is what can one do more ?
Can one compare values ? (the mainstream of programming)
Can one take substrings ? etc.

The best solution would be to have a unicode database rather than try workarounds.

**Comment by RenaldasKalcas** [comment]
Thanks, Maxim. Your workaround did the job.
