### ISSUE TITLE
parsing clob json fails, gives numeric or value error

### ISSUE THREAD

**Issue by pingstevendsouza** [pljson/pljson#180]
select pljson(clob_json_data) from dual;

ORA-06502: PL/SQL: numeric or value error
ORA-06512: at "<SCHEMA>.PLJSON_PARSER", line 127
ORA-06512: at "<SCHEMA>.PLJSON_PARSER", line 792
ORA-06512: at "<SCHEMA>.PLJSON", line 23
================================
at line 127 of PLJSON_PARSER : this is below code
 /* use of lengthc, so works correctly for 4-byte unicode characters (issue #169) */
    temp.len := lengthc(buf); --dbms_lob.getlength(buf);

but when I change the code to dbms_lob.getlength(buf); it works fine.
This is a straight forward scenario.

I had installed pljson 2.0 version -- faced same issue, so uninstalled and installed the latest version 3.10. still the same issue.

**Comment by dsnz** [comment]
hi,

a fix will be available very soon (it was about to be released just as you
created this issue :D)

**Comment by pingstevendsouza** [comment]
cool thanks 👍

**Comment by dsnz** [comment]
in the meantime
you can try the develop_v3 branch by downloading it, it should work
(the releases have not been updated yet)
