### ISSUE TITLE
PLS-00302: component 'PLJSON_TABLE_IMPL' must be declared

### ISSUE THREAD

**Issue by donghoangngu** [pljson/pljson#182]
When I run script ...\examples\ex_pljson_table.sql, I receive the error: "PLS-00302: component 'PLJSON_TABLE_IMPL' must be declared".

I did not find function json_table in script: src\addons\pljson_table_impl.type.impl.sql (body), but it exists in src\addons\pljson_table_impl.type.decl.sql (header) ! Is it the reason ?

**Comment by dsnz** [comment]
Hi,

The entire example script runs for me.
The code as you saw it (no function in body) is correct !

Give more information, like the version of pljson you installed, the exact sql script you run and the exact full error output.

**Comment by donghoangngu** [comment]
Hi dsnz,
Version is 2.5.1, I used  new schema JSON (not SYS) to install the scripts.
I ran any Select Statement in "\examples\ex_pljson_table.sql" is error, such as:

select num, name, map, count
from pljson_table_test,
table(
pljson_table.json_table(
col,
pljson_varray('data.name', 'data.extra', 'data.maps', 'data.shares.count', 'data.missing'),
pljson_varray('name', 'extra', 'map', 'count', 'whatelse'))
)
order by num

Thanks.

[ex_pljson_table.txt](https://github.com/pljson/pljson/files/3732742/ex_pljson_table.txt)

**Comment by dsnz** [comment]
Hi,

This is so strange. May be it's a bug of the tool you use (TOAD). I can run fine the sql you posted, both within Oracle SQL Developer and within sqlplus.

Try to run the examples within sqlplus.

**Comment by dsnz** [comment]
see also issue #139

**Comment by donghoangngu** [comment]
Hi,
I tried with PL/SQL Developer tool too.
It had still error with JSON schema (pic PLSQL_json.PNG)
But when I tried with SYS schema and add schema name in table and Function, It was worked  (pic PLSQL_sys.PNG)

I don't know how !!

![PLSQL_json](https://user-images.githubusercontent.com/56620195/66896624-60c9c880-f01f-11e9-963c-4565c165cd39.PNG)
![PLSQL_sys](https://user-images.githubusercontent.com/56620195/66896626-61625f00-f01f-11e9-9af1-7c4deb5b3d96.PNG)

**Comment by dsnz** [comment]
Hi,

You can't name your schema **json** !

Drop this schema. Create a new schema with normal name and not a reserved name (either database related as from 12c json is a word to be avoided or pljson related as we create a synonym named json too ...), reinstall and try again.

**Comment by donghoangngu** [comment]
Hi,
I created new Schema APPS and re-install & re-test, but I had a new error: ORA-22922: nonexistent LOB value

select * from table(pljson_table.json_table(
  '[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
))

![image](https://user-images.githubusercontent.com/56620195/66908136-c5435280-f034-11e9-9ef2-bc5e25d17ab5.png)

**Comment by dsnz** [comment]
and it took you 16 sec to get this response ?!

well right now I have no idea as I am busy at work
I will have a look at it much later

in the meantime ...
what about the other example sql(s) ? do they all fail (and with what error) or some run successfully ?

**Comment by donghoangngu** [comment]
Hi,
No problem, I can wait.
In examples sql, just 1 statement is success:

select num, name, map, count
from pljson_table_test,
table(
pljson_table.json_table(
col,
pljson_varray('data.name', 'data.extra', 'data.maps', 'data.shares.count', 'data.missing'),
pljson_varray('name', 'extra', 'map', 'count', 'whatelse'))
)
order by num

All most are failed.

Thanks for your supporting.

**Comment by dsnz** [comment]
one more thing please

run the whole **ex_pljson_table.sql** within sqlplus (as user APPS @ex_pljson_table.sql)
and post here (or provide a link) to the whole exact spool output

**Comment by donghoangngu** [comment]
My output below:

SQL> @ex_pljson_table.sql

Table dropped.
Table created.
1 row created.
1 row created.
1 row created.
Commit complete.

select *
*
ERROR at line 1:
ORA-22922: nonexistent LOB value



       NUM NAME       MAP        COUNT
---------- ---------- ---------- ----------
         1 name 3     true       100
         1 name 3     true       100
         1 name 3     false      100
         2 name 3     true       100
         2 name 3     true       100
         2 name 3     false      100
         3 name 3     true       100
         3 name 3     true       100
         3 name 3     false      100

9 rows selected.


       NUM NAME       MAP        COUNT
---------- ---------- ---------- ----------
         1 name 1     true       1
         2 name 2     true       5
         3 name 3     true       100
         3 name 3     false      100
         3 name 3     true       100

select * from table(pljson_table.json_table(
*
ERROR at line 1:
ORA-22922: nonexistent LOB value


select * from table(pljson_table.json_table('{
                    *
ERROR at line 1:
ORA-22922: nonexistent LOB value



ITEM_NUMBE DESCRIPTION          QUANTITY
---------- -------------------- ----------
1          One Magic Christmas  9
2          Lethal Weapon        5

**Comment by dsnz** [comment]
Thank you,

There is more interesting information now.
It seems that 3 sql(s) run without problem.

Tell me please, when you get error, isn't there any more stack trace ?

do you get only only this single line of error ?

ERROR at line 1:
ORA-22922: nonexistent LOB value

(I am asking because the full stack trace sometimes is getting lost in these copy-paste and formatting operations on github; if there is more no stack trace this indicates that the pljson_table code has not run at all)

**Comment by donghoangngu** [comment]
Hi Sarmas,
Just only single line of Error: ORA-22922: nonexistent LOB value.
I think stack trace is OK because when I run 1 statement, error is the same, such as the last query:

select * from table(pljson_table.json_table('{
  "PONumber" : 1600,
  "Reference" : "ABULL-20140421",
  "Requestor" : "Alexis Bull",
  "User" : "ABULL",
  "CostCenter" : "A50",
  "ShippingInstructions" : {"name" : "Alexis Bull",
                            "Address" : {"street" : "200 Sporting Green",
                                         "city" : "South San Francisco",
                                         "state" : "CA",
                                         "zipCode" : 99236,
                                         "country" : "United States of America"},
                            "Phone"   : [{"type" : "Office", "number" : "909-555-7307"},
                                         {"type" : "Mobile", "number" : "415-555-1234"}]},
  "Special Instructions" : null,
  "AllowPartialShipment" : true,
  "LineItems" : [{"ItemNumber" : 1,
                  "Part" : {"Description" : "One Magic Christmas",
                            "UnitPrice" : 19.95,
                            "UPCCode" : 13131092899},
                            "Quantity" : 9.0},
                 {"ItemNumber" : 2,
                  "Part" : {"Description" : "Lethal Weapon",
                            "UnitPrice" : 19.95,
                            "UPCCode" : 85391628927},
                            "Quantity" : 5.0}]
}',
  pljson_varray('LineItems[*].ItemNumber', 'LineItems[*].Part.Description', 'LineItems[*].Quantity'),
  pljson_varray('item_number', 'description', 'quantity'),
  table_mode => 'nested'
))

**Comment by dsnz** [comment]
Your tool (TOAD) may not give the full stack trace, that's why I wanted you to use sqlplus.
But with sqlplus you say there is still no stack trace. So, I will stick with that now.
Can I have tour database version and database character set ?

**Comment by donghoangngu** [comment]
My version: 12.2
Character set: AL32UTF8

![image](https://user-images.githubusercontent.com/56620195/66936175-7236c300-f067-11e9-9a92-1a230b67a6b1.png)

**Comment by dsnz** [comment]
please run just the following

```
select name, extra
from 
table(
pljson_table.json_table(
'{"data":
  {
   "name": "name 3",
   "description": "blah blah...",
   "type": "text",
   "created_time": "2015-12-21T19:23:29+0000",
   "shares": { "count": 100 },
   "extra": null,
   "maps" : [ true, true, false ]
  }
}',
pljson_varray('data.name', 'data.extra', 'data.maps', 'data.shares.count', 'data.missing'),
pljson_varray('name', 'extra', 'map', 'count', 'whatelse'))
)
/
```

**Comment by donghoangngu** [comment]
Still old Error Sarmas. I tried with TOAD & plsql.

![image](https://user-images.githubusercontent.com/56620195/66972484-f5373800-f0be-11e9-9517-e1d30b3af9de.png)

![image](https://user-images.githubusercontent.com/56620195/66972494-fc5e4600-f0be-11e9-9e01-8e437279b482.png)

And I had a new error, could I log it in this issue or create new issue ?

**Comment by dsnz** [comment]
now as dba (not normal user)
run the following

```
select *
from dba_tab_privs
where grantee = 'APPS'
or (grantee = 'PUBLIC' and table_name like '%JSON%');

select *
from dba_synonyms
where table_name like '%JSON%';

select *
from dba_users
where username like '%JSON%';
```

**Comment by donghoangngu** [comment]
Hi Sarmas, I give you information in attach file 

[grant_dba.xlsx](https://github.com/pljson/pljson/files/3737333/grant_dba.xlsx)

In last query, I use schema APPS, not JSON

**Comment by dsnz** [comment]
Hi,

I want the last as it is please !

**Comment by dsnz** [comment]
Drop user 'JSON' and try again.

**Comment by donghoangngu** [comment]
I dropped it, but got the same error >.<.
If this bug takes you a long time, we can pass it.

**Comment by dsnz** [comment]
Hi,

It's not a bug. It works for all other people.
It's an installation issue. You can try a new clean installation (dropping all JSON-like synonyms and grants too) or give me remote access to work on it and see what's your problem.

**Comment by donghoangngu** [comment]
Hi,
I will try in new instance and feed back to you.

Thank you.
