### ISSUE TITLE
[Err-ORA-22275]: PLJSON_LIST.TO_CLOB

### ISSUE THREAD

**Issue by donghoangngu** [pljson/pljson#183]
Scripts:
DECLARE 
  RET PLJSON_LIST:= PLJSON_LIST();
  P_CLOB CLOB;
BEGIN
  RET := JSON_DYN.EXECUTELIST('SELECT * FROM ALL_DIRECTORIES');
  RET.TO_CLOB(P_CLOB);
--  ret.TO_CHAR(p_clob);
--  ret.print;
END;

Error:
ORA-06502: PL/SQL: numeric or value error: invalid LOB locator specified: ORA-22275
ORA-06512: at "SYS.DBMS_LOB", line 1163
ORA-06512: at "APPS.PLJSON_PRINTER", line 139
ORA-06512: at "APPS.PLJSON_PRINTER", line 293
ORA-06512: at "APPS.PLJSON_LIST", line 356
ORA-06512: at line 6

![image](https://user-images.githubusercontent.com/56620195/66973690-eb173880-f0c2-11e9-9a5c-6e7cbca89409.png)

**Comment by dsnz** [comment]
This is a coding mistake on your part. Correct code is

```
DECLARE
RET PLJSON_LIST:= PLJSON_LIST();
P_CLOB CLOB;
BEGIN
RET := JSON_DYN.EXECUTELIST('SELECT * FROM ALL_DIRECTORIES');
dbms_lob.createtemporary(p_clob, true); -- <= CLOB must be created
RET.TO_CLOB(P_CLOB);
-- ret.TO_CHAR(p_clob);
-- ret.print;
END;
```

**Comment by donghoangngu** [comment]
Wao, its worked. Thanks Sarmas :D

**Comment by boriborm** [comment]
Don't forget run ```dbms_lob.close(p_clob);``` after run ```ret.to_clob(p_clob)``` for free reference to lob in system.
