### ISSUE TITLE
Process JSON file with PL/JSON

### ISSUE THREAD

**Issue by lopezanibal** [pljson/pljson#188]
Hello,

Need to parse and process the JSON structure below.

JSON structure:

{"Changes" : {"Count_Changes" : "2",
              "Changes" :
  [
    {"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:26:771", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
                       "MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "7015", "MBGP_KEY" : "ALL MEMBERS", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "70950", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
                          ,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
     ]
                          ,"Payr_Request" : { "MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
                          ,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "70950", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
                    }
}
   ,{"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:43:491", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
                           "MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
                          ,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
     ]
           ,"Payr_Request" : {"MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
   ,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "0", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
}} ] } };

The logic is as follow:
Changes are made on a Payload system.
So there will be a Payload request.
The Payload request has the field item "TYP_CD".
The TYPE_CD have to possible values "00" or "01".

Logic:
1] If the TYPE_CD has a value of "00" then i need to read the value of the "CHNG_TYP_CD" in the "MCase_Request" as this value describe which item in the MBRClient_Request structure i should use to update Client database table field.

2] If the TYPE_CD has a value of "01" then i need to read all item values of the Payr_Request structure to update c.q. insert the Client database table record.

How can i do this with Pl/JSON?

Any help or hint will be much appreciated.

Regards,
Anibal

**Comment by dsnz** [comment]
Hi,

We can't provide full programming help (no open source project does this). You can work the examples and also read the package and type specifications and see how to use PLJSON.

However just for this case only I spent some time to make a small demo on how to access the fields you need (a quick and dirty one which only prints the fields without the full conditional logic on TYPE_CD and with short variable names). This is enough to guide you to complete it and will also serve for any future such request.

```
declare
 a varchar2(32000) := q'^
{"Changes" : {"Count_Changes" : "2",
"Changes" :
[
{"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:26:771", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
"MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "7015", "MBGP_KEY" : "ALL MEMBERS", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "70950", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
]
,"Payr_Request" : { "MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "70950", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
}
}
,{"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:43:491", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
"MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
]
,"Payr_Request" : {"MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "0", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
}} ] } }^';
 js pljson;
 jl pljson_list;
 n integer;
 ji pljson;
 jpayr pljson;
 jmcase pljson;
begin
  js := pljson(a);
  jl := js.get_pljson('Changes').get_pljson_list('Changes');
  dbms_output.put_line(jl.count);
  ji := pljson(jl.get(2)).get_pljson('Payload_Request');
  dbms_output.put_line(ji.get_string('TYP_CD'));
  jpayr := ji.get_pljson('Payr_Request');
  dbms_output.put_line(jpayr.get_string('LASTNAME'));
  jmcase := ji.get_pljson('MCase_Request');
  dbms_output.put_line(jmcase.get_string('CHNG_TYP_CD'));
end;
```

**Comment by lopezanibal** [comment]
Thank you.Your help is much appreciated.Regards,AnibalOp 3 februari 2020 om 21:48 schreef "E.I.Sarmas" <notifications@github.com>:  Hi,We can't provide full programming help (no open source project does this). You can work the examples and also read the package and type specifications and see how to use PLJSON.However just for this case only I spent some time to make a small demo on how to access the fields you need (a quick and dirty one which only prints the fields without the full conditional logic on TYPE_CD and with short variable names). This is enough to guide you to complete it and will also serve for any future such request.declare
 a varchar2(32000) := q'^
{"Changes" : {"Count_Changes" : "2",
"Changes" :
[
{"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:26:771", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
"MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "7015", "MBGP_KEY" : "ALL MEMBERS", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "70950", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
]
,"Payr_Request" : { "MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145543", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "70950", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
}
}
,{"Payload_Request" : { "CASE_KEY" : "", "UPLOAD_DT" : "07-08-2019 15:13:43:491", "PYRL_CONTRIB_AMT" : "", "PYRL_CONTRIB_EFF_DT" : "", "PYRL_AUTH_DT" : "", "PAYROLL_BEG_DT" : "", "PAYROLL_END_DT" : "", "TYP_CD" : "00", "SAL_RENEW_CD" : "N",
"MBRClient_Request" : [ { "MBR_TYP_CD" : "00", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "0 %", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
,{"MBR_TYP_CD" : "01", "MBGC_KEY" : "", "MBGP_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "BIRTHDT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "0", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "2", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "0"}
]
,"Payr_Request" : {"MBR_TYP_CD" : "", "MBGC_KEY" : "", "PYRL_NO" : "", "CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "", "NATLIDNO" : "", "BIRTHDT" : "", "CHNG_DT" : "", "JOIN_SCH_DT" : "", "JOIN_COMP_DT" : "", "FIRSTNAME" : "", "LASTNAME" : "", "MIDNAME" : "", "NAMEPREFIX" : "", "NAMESUFFIX" : "", "ANN_SAL_AMT" : "", "SAL_EFF_DT" : "", "PART_TIME_PCT" : "", "SEXCD" : "", "SPOUSAL_CNT" : "", "DEPENDENT_CNT" : ""}
,"MCase_Request" : {"CASE_MBR_KEY" : "", "PEND_MBR_REF_ID" : "A145545", "NATLIDNO" : "", "PYRL_NO" : "", "CHNG_TYP_CD" : "", "CHNG_AMT" : "0", "CHNG_DT" : "", "CHNG_DATA" : "", "CHNG_PCT" : "0", "CHNG_EXIT_REAS_CD" : "", "CHNG_EXIT_DT" : "", "SPOUSAL_CNT" : "0", "DEPENDENT_CNT" : "", "BIRTH_COUNTRY_CD" : "", "ADDR_LINE1" : "", "ADDR_LINE2" : "", "ADDR_LINE3" : "", "ADDR_CITY" : "", "ADDR_POST_CD" : "", "ADDR_COUNTRY_CD" : "", "ADDR_EMAIL" : "", "PHONE" : "", "NATIONALITY_CD" : ""}
}} ] } }^';
 js pljson;
 jl pljson_list;
 n integer;
 ji pljson;
 jpayr pljson;
 jmcase pljson;
begin
  js := pljson(a);
  jl := js.get_pljson('Changes').get_pljson_list('Changes');
  dbms_output.put_line(jl.count);
  ji := pljson(jl.get(2)).get_pljson('Payload_Request');
  dbms_output.put_line(ji.get_string('TYP_CD'));
  jpayr := ji.get_pljson('Payr_Request');
  dbms_output.put_line(jpayr.get_string('LASTNAME'));
  jmcase := ji.get_pljson('MCase_Request');
  dbms_output.put_line(jmcase.get_string('CHNG_TYP_CD'));
end;
