### ISSUE TITLE
Double Quotes (") are missed in json_to_xml  conversion using pljson_xml API

### ISSUE THREAD

**Issue by ssarap** [pljson/pljson#194]
On converting json data to xml double quotes are not converted using latest pljson_xml.json_to_xml method. It works fine with json_xml.json_to_xml. Please find the test case below. Resolving this will be a great help for us as its a blocker.

```
declare
l_message  varchar2(4000);
l_res      xmltype;
begin
l_message := '{"MSG1":{"value":"<font class=\"color-assertive\">Sample Message.</font>"}}';

l_res := json_xml.json_to_xml(json(l_message));
dbms_output.put_line('json result  : '|| l_res.getstringval());

l_res := pljson_xml.json_to_xml(pljson(l_message));
dbms_output.put_line('pljson result: '|| l_res.getstringval());
end;
/

Output:
json result  : <?xml version="1.0"?><root><MSG1><value>&quot;&lt;font class=&quot;color-assertive&quot;&gt;Sample Message.&lt;/font&gt;&quot;</value></MSG1></root>
pljson result: <?xml version="1.0"?><root><MSG1><value>&lt;font class=&quot;color-assertive&quot;&gt;Sample Message.&lt;/font&gt;</value></MSG1></root>

```

**Comment by dsnz** [comment]
hi

1.  you should get the same results because json_xml is a synonym for pljson_xml,
if not then something is **terribly wrong** with your installation

2.  the correct result is **without quotes** :)
the quotes are needed in json to mark the text, they are **not** part of the the payload text and so it is not converted to xml
if you want the quotes then your example should be

```
declare
l_message  varchar2(4000);
l_res      xmltype;
begin
l_message := '{"MSG1":{"value":"\"<font class=\"color-assertive\">Sample Message.</font>\""}}';

l_res := json_xml.json_to_xml(json(l_message));
dbms_output.put_line('json result  : '|| l_res.getstringval());

l_res := pljson_xml.json_to_xml(pljson(l_message));
dbms_output.put_line('pljson result: '|| l_res.getstringval());
end;
/
```

**Comment by ssarap** [comment]
@dsnz Sure I will check it revert back. Thanks for a quick response.

**Comment by ssarap** [comment]
@dsnz we currently use conversion of XML to JSON extensively and after replacing json with pljson our application is giving some strange issues and the route being stated in above example.
json and pljson api's are not behaving the same in terms of ". 
If you are fine for a web conference it would be great. Please let us know your convenient time.

**Comment by dsnz** [comment]
Hi,

I don't have time for a web conference and it's not really necessary.
Please read the following carefully.

1. There is no json and pljson api !
There is a single api that started from version 1 (obsolete) and evolved to version 2.
In version 1 the api calls started with json_, and in version 2 the api calls start with pljson_ but synonyms starting with json_ for each pljson_ call are created (and so calling with json_ or pljson_ should have no difference). The api calls in version1 and version 2 are the same (version 2 has some more). In version 3 api calls start with pljson_ and there are no synonyms.

2. you should use version 3 ! (get latest release 3.2.0 from branch develop_v3)
Version 3 has a few api changes and so it is incompatible. But these are few changes and you should be able to convert easily.
If you really can't convert then use version 2 (get latest zip from master branch, don't get last release you see, it's not up to date, next month I will make a new release with more updates).
Read the Version 3 README (branch develop_v3) for more information regarding version 3 and 2 and proper installation too.
You should not use version 1 (or any pljson code not marked clearly as version 2 or 3). If you download and install a release then function **PLJSON_PARSER.get_version()** will return a version string.

3. It is certain that you have mixed installations.
I suggest that

a. you drop all public synonyms starting with JSON_  or PLJSON_
b. in your production schema, drop all synonyms, packages and types starting with JSON_ or PLJSON_
c. download the pljson version you choose, unzip it in a folder and cd in it,
then do **sqlplus \<schema\>/\<password\>** and at the prompt **@install.sql**
d. test using calls starting with pljson_ only !
