### ISSUE TITLE
ORA-22922: nonexistent LOB value

### ISSUE THREAD

**Issue by tantivy04** [pljson/pljson#196]
Hi Team, 
After i installed.
I select and a have the error: ORA-22922: nonexistent LOB value

Pls help me!
![Capture](https://user-images.githubusercontent.com/3865685/80333668-07b5d980-8879-11ea-83d1-9c054d2fd0bc.PNG)

```sql
select * from table(pljson_table.json_table(
  '[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));
```

**Comment by dsnz** [comment]
Hi,

It works for me. Are you using version 2 or version 3 ?
Give us the whole stack trace (if you can't get it within the GUI you use then run the sql statement in sqlplus).

**Comment by tantivy04** [comment]
That's oralce's Error. I fixed! 
Thanks for support

**Comment by WoodG0b1in** [comment]
How you could fix this? Can you explain?

**Comment by dsnz** [comment]
Hi,

you caught me in the desert almost literally without my laptop 😂
I will be back to civilization in 3 days

since it's an issue with a new release of Oracle and definitely I can't
install all oracle versions for troubleshooting I will depend on your help
to diagnose what's happening (once we understand the reason then the we can
fix it)
so, please until I return post the full/complete error stack trace with
version 3.4.1

**Comment by WoodG0b1in** [comment]
`declare 
  -- Local variables here
  i integer;
begin
  for r$r in (
      select *
        from table(
        dev_core.pljson_table.json_table(
        '{"data":
          {
           "name": "name 3",
           "description": "blah blah...",
           "type": "text",
           "created_time": "2015-12-21T19:23:29+0000",
           "shares": { "count": 100 },
           "extra": null,
           "maps" : [ true, true, false ]
          }
        }',
        dev_core.pljson_varray('data.name', 'data.extra', 'data.maps', 'data.shares.count', 'data.missing'),
        dev_core.pljson_varray('name', 'extra', 'map', 'count', 'whatelse'))
        ))
  loop
    null;
  end loop;
  
exception
  when others then
    dbms_output.put_line(DBMS_UTILITY.format_call_stack);
    dbms_output.put_line(DBMS_UTILITY.format_error_stack);

end;`

`----- PL/SQL Call Stack -----
  object      line  object
  handle    number  name
0x73bea098        30  anonymous block

ORA-22922: nonexistent LOB value
ORA-06512: at line 7`


for the third time

**Comment by dsnz** [comment]
@WoodG0b1in 
let's stick at your issue #220, unless @tantivy04 provides new clues here

@tantivy04 
please post here what was the Oracle error you encountered and how you fixed it

**Comment by ayu96847** [comment]
> That's oralce's Error. I fixed!
> Thanks for support

@tantivy04 could you send us the fix for the above issue. I am facing a similar issue. 

Thanks

**Comment by sferris** [comment]
Hi @dsnz .. I hope you don't mind me posting to this ticket.. I received the same issue, and traced it back to DBA privileges. (or at least that's how I've been able to consistently get it to break)

I presume it's less about DBA and more about un-restricted access to other objects. (I'm guessing 'select any'/'execute any' would likely cause the same issue??) This is a 19c database. (it's my lab and I'm helping someone else with a package that doesn't have native JSON)

I haven't spent a lot of time looking, maybe I'll have time later.. but basically there's a type created when using pljson_table (I presume it's the pljson_object_cache?), and when those are created when the user has DBA privs, this error occurs. If I drop those types, and revoke DBA privs, it works consistently. If I re-grant DBA and re-connect (w/o dropping the types), it'll work for a period of time, but eventually the errors comes back.

Anyway, thought I'd at least mention what I'd found, in case you have a clue.. It's generally not an issue, I just happened to be testing, immediately after installation.. and that's when I triggered it. Normally I wouldn't be using a DBA account.

**Comment by dsnz** [comment]
Hi @sferris and thank you for your report,

However, **nowhere during development here or in the installation scripts do we use "DBA privileges"**.

Also, this error has been reported by users even before "pljson_object_cache" was introduced in code.

My belief is that it has something to do with clob locator management in the user code and across commits. Clob locators must be managed carefully in code and most users do not know this or are not careful enough.

Since you say that you have done experiments indicating a relation with "DBA privileges", then please post here

* what are exactly these "DBA privileges" ?
* a self-sufficient demo code demonstrating the error in absence of these privileges and demonstrating no-error if these privileges are granted

I can run this code in all databases from 11 and above and verify the result

**Comment by sferris** [comment]
Here's a test case.. there's one difference here.. Those 2 types that I observed before, I didn't observe this time.

>>> session 1
```
SQL> create user test5 identified by test5;

User created.

SQL> grant create session to test5;

Grant succeeded.
```

>>> session 2
```
SQL@NOWHERE> connect "test5"@labfs01d
Connected.

test5@labfs01d_01> select count(1) from table(pljson_table.json_table(
  '[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));

  COUNT(1)
----------
         6

1 row selected.
```

>>> session 1
```
SQL> grant DBA to test5;

Grant succeeded.
```

>>> session 2
```
test5@labfs01d_01> connect "test5"@labfs01d
Connected.

test5@labfs01d_01> select count(1) from table(pljson_table.json_table(
  '[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));

  COUNT(1)
----------
         6

1 row selected.

test5@labfs01d_01> /

  COUNT(1)
----------
         6

1 row selected.

test5@labfs01d_01> /
select count(1) from table(pljson_table.json_table(
                           *
ERROR at line 1:
ORA-22922: nonexistent LOB value

test5@labfs01d_01> select object_name from user_objects;

no rows selected
```

>>> session 1
```
SQL> revoke DBA from test5;

Revoke succeeded.
```

>>> session 2
```
test5@labfs01d_01> connect "test5"@labfs01d
Connected.

test5@labfs01d_01> select count(1) from table(pljson_table.json_table(
  '[
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]',
  pljson_varray('[*].id', '[*].displayname', '[*].qty', '[*].extras[*].xid', '[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));

  COUNT(1)
----------
         6

1 row selected.
```
