### ISSUE TITLE
ORA-30186: '\' 的后面必须是四个十六进制字符或另一个 '\'

### ISSUE THREAD

**Issue by Encina5009313** [pljson/pljson#198]
【Oracle 11.2.0.2.0 】

cl;
set serveroutput on format wrapped;
declare
  obj json;
begin
  obj := json('{"a": "荺" }');
  obj.print;
end;
/

ORA-30186: '\' 的后面必须是四个十六进制字符或另一个 '\'
ORA-06512: 在 "U00.PLJSON_PARSER", line 478
ORA-06512: 在 "U00.PLJSON_PARSER", line 747
ORA-06512: 在 "U00.PLJSON", line 16
ORA-06512: 在 line 5

**Comment by dsnz** [comment]
```
-- 11.2.0.4
-- PLJSON 3.2.0
declare
obj json;
begin
obj := json('{"a": "荺" }');
obj.print;
end;
/
```

{
  "a" : "\u837A"
}

**Comment by Encina5009313** [comment]
Oracle 11.2.0.2
PLJSON 3.2.0
NLS_CHARACTERSET   ZHS16GBK
nls_language  SIMPLIFIED CHINESE

**Comment by dsnz** [comment]
1.

```
ORA-30186: '' 的后面必须是四个十六进制字符或另一个 ''
ORA-06512: 在 "U00.PLJSON_PARSER", line 478
ORA-06512: 在 "U00.PLJSON_PARSER", line 747
ORA-06512: 在 "U00.PLJSON", line 16
ORA-06512: 在 line 5
```
is incomplete

send full stack trace

2. set NLS_LANG=AMERICAN_AMERICA.UTF8 and try again

**Comment by jtimmmmmm** [comment]
I have same problem, Encina5009313 do you have solution to fix issue ?

**Comment by Encina5009313** [comment]
pljson_parser L407 *
&nbsp; &nbsp; &nbsp; BEGIN
&nbsp; &nbsp; &nbsp; &nbsp; tok.data := unistr(varbuf);
&nbsp; &nbsp; &nbsp; EXCEPTION WHEN OTHERS THEN
&nbsp; &nbsp; &nbsp; &nbsp; tok.data := unistr(ASCIISTR(varbuf));
&nbsp; &nbsp; &nbsp; END;
