### ISSUE TITLE
PL/JSON Types and Packages are invalid in R12.2

### ISSUE THREAD

**Issue by barozkok** [pljson/pljson#207]
Hi,

Is there a way to make all  PL/JSON Types and Packages valid in PL/JSON in a 12.2 version Oracle DB?

Thanks in advance.

**Comment by dsnz** [comment]
Hi

Which pljson version you use ? Which package/type is invalid and what message you get when you try to compile it ? (please post full stack trace)

**Comment by barozkok** [comment]
Hi,
Thanks for the update.

PL/JSON had been installed in 2013. The version is PL/JSON v1.0.4. 
The following objects are invalid in 12.2 version Oracle DB.
Package Bodies: JSON_DYN, JSON_EXT, JSON_HELPER, JSON_PARSER
Type Bodies: JSON_VALUE, JSON_LIST, JSON

I have attached the splplus log file for the detailed errors.

Regards
[Sqlplus_error_logs.txt](https://github.com/pljson/pljson/files/5081218/Sqlplus_error_logs.txt)

**Comment by dsnz** [comment]
Hi,

We are in 2020 ! This version v1.0.4 is so old and obsolete.
Download the latest release v3.3.2 and install it (you will find it by clicking Code -> tags -> Releases).
It has a ton of bugs squashed and compatibility with Oracle 12.
Also check now and then for updates (within 1-2 weeks we will have a new release v3.4.0).

**Comment by barozkok** [comment]
Thank you very much.
