### ISSUE TITLE
could be installed pljson in oracle 12.2.0.1

### ISSUE THREAD

**Issue by geridmiguel** [pljson/pljson#211]
can be installer in oracle 12? if yes how install Pljson in oracle 12.2.0.1,
It may present some conflict with the native handling of the json in oracle 12 ?

regards

**Comment by geridmiguel** [comment]
I forgot something, I am using pljson in oracle 11

**Comment by dsnz** [comment]
just install it !
no conflicts

**Comment by jsumners** [comment]
A gentler answer: the most recent releases do not conflict with Oracle 12. Simple download the latest release and install it as the instructions indicate.

**Comment by geridmiguel** [comment]
Thanks for your recommendations
