### ISSUE TITLE
ORA-01704: string literal too long Issue

### ISSUE THREAD

**Issue by afsurhussain** [pljson/pljson#212]
Hi Team

I am getting the below error in the 

select * from table(pljson_table.json_table('{xxx - char count > 4000}',
  pljson_varray('columnname'),
  pljson_varray('columnname'),
  table_mode => 'nested'
));

Please check and let me know the solution.

**Comment by dsnz** [comment]
please post the entire and complete stacktrace

**Comment by dsnz** [comment]
the stack trace is always needed when you post an issue and will also serve as a guide to check the whole thing and possibly propose some kind of workaround (you sql text would be good to know too in order to help you !)

your problem as you already know is that string literals in Oracle max at 4000 bytes (not even characters), so you hit a Oracle SQL/PLSQL limitation and we can definitely do nothing for this
besides that you can replace the literal with a clob field from another table that you will join with in the from clause

**Comment by afsurhussain** [comment]
Hi Team,

The below is my query which returns in error.

select * from table(pljson_table.json_table(
  '{"Phone"   : [
    { "id": 0, "displayname": "Back",  "qty": 5, "extras": [ { "xid": 1, "xtra": "extra_1" }, { "xid": 21, "xtra": "extra_21" } ] },
    { "id": 2, "displayname": "Front", "qty": 2, "extras": [ { "xid": 9, "xtra": "extra_9" }, { "xid": 90, "xtra": "extra_90" } ] },
    { "id": 3, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 4, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 5, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 6, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 7, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 8, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 9, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 10, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 11, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 12, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 13, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 14, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 15, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 16, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 17, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 18, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 19, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 20, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 21, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 22, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 23, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 24, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 25, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 26, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 27, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 28, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 29, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] },
    { "id": 30, "displayname": "Middle", "qty": 9, "extras": [ { "xid": 5, "xtra": "extra_5" }, { "xid": 20, "xtra": "extra_20" } ] }
  ]}',
  pljson_varray('Phone[*].id', 'Phone[*].displayname', 'Phone[*].qty', 'Phone[*].extras[*].xid', 'Phone[*].extras[*].xtra'),
  pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
  table_mode => 'nested'
));

**Comment by dsnz** [comment]
thanks for using an expanded version of our example which also happens to run without error (!)

for longer sql text, try this workaround

```
select *
from table(pljson_table.json_table(
(select sql_text from sql_clob where id  = <id>),
pljson_varray('Phone[*].id', 'Phone[*].displayname', 'Phone[*].qty', 'Phone[*].extras[*].xid', 'Phone[*].extras[*].xtra'),
pljson_varray('id', 'displayname', 'qty', 'xid', 'xtra'),
table_mode => 'nested'
));
```

where in table sql_clob and column sql_text (of clob type) enter your sql text
