### ISSUE TITLE
Which version can support Oracle 10g

### ISSUE THREAD

**Issue by Vision-Ma** [pljson/pljson#214]
Unsupported syntax will appear in Oracle 10g installation.
11.2 add the create or replace type statement and add the force option,
So is there a pljson version to support Oracle 10g version
thks
![企业微信截图_16012771574958](https://user-images.githubusercontent.com/46484173/94408559-82c44880-01a7-11eb-8b1d-63efe0ff41ad.png)

**Comment by dsnz** [comment]
Hi
PLJSON should install without errors in 10g. Try with some tool (eg. SQL Developer) to recompile the type PLJSON_ELEMENT and get all the compilation error messages (ie. the exact compilation error and the line where it appears) and post here

**Comment by Vision-Ma** [comment]
Thank you for your answer.
Risk comparison for two solutions， I will upgrade the database to 11.2
