### ISSUE TITLE
Elegent way to convert pljson to CLOB with pretty-print (human-readable)

### ISSUE THREAD

**Issue by adamovski1970** [pljson/pljson#221]
Dear PLJSON team,

Currently print of pljson object is printing arrays "names" and "data" to dbms_out buffer.

Please kindly suggest elegant way of printing (for debug) and converting to CLOB  both with  pretty-print (human-readable).

regards,

Bad.

**Comment by dsnz** [comment]
Hi,

both are available
see this example

```
declare
 p pljson;
 buf clob;
begin
  p := pljson('{"items":[{"item":"EMPLOYEE_ID", "val":"1", "lbl":"employee nr", "type":"number"}]}');

  -- pretty print to dbms_output
  p.print;

  dbms_lob.createtemporary(buf, cache => false);

  -- pretty print to clob
  p.to_clob(buf, spaces => true);

  dbms_output.put_line(buf);
end;
```

**Comment by adamovski1970** [comment]
Thanks for super-quick answer. Again, many open-source projects are better supported than many commercial products.

**Now clarification:**

PLJSON is created dynamically from select statement using pljson_dyn.executeObject. Output printed to dbms_output contains 2 arrays "names" and "data". How to print/to_clob with pretty print please ?

DECLARE
    RET      PLJSON;
    P_CLOB   CLOB;
BEGIN
    RET :=
        pljson_dyn.executeObject(
            'SELECT OWNER,TABLE_NAME FROM ALL_TABLES WHERE OWNER=''SYS'' AND ROWNUM<=3' );
    DBMS_LOB.createtemporary( p_clob, TRUE );       -- <= CLOB must be created
    ret.PRINT;
END;

dbms output printed:

{
"names" : ["OWNER", "TABLE_NAME"],
"data" : [["SYS", "WRR$_REPLAY_CALL_FILTER"], ["SYS", "DUAL"], ["SYS", "SYSTEM_PRIVILEGE_MAP"]]
}

**Comment by dsnz** [comment]
first let's clarify if you want the format of executeObject() output (which is rather special) or you want classic json in which case you better try this variation of your example code

```
DECLARE
    RET      PLJSON_LIST; -- CHANGE: different type
    P_CLOB   CLOB;
BEGIN
    RET :=
        --pljson_dyn.executeObject(
        -- CHANGE: different call
        pljson_dyn.executeList(
            'SELECT OWNER,TABLE_NAME FROM ALL_TABLES WHERE OWNER=''SYS'' AND ROWNUM<=3' );
    DBMS_LOB.createtemporary( p_clob, TRUE );       -- <= CLOB must be created
    -- CHANGE: code to convert to clob and process (as in example in previous post)
    -- ...
    ret.PRINT;
END;
```

**Comment by adamovski1970** [comment]
OK thanks for explanation.
