### ISSUE TITLE
PL/JSON 3.4.1 - ORA-31011: using pljson_util_pkg.sql_to_json( sql_query ) where sql_query selects column with two ampersand or two less-than characters or mixed

### ISSUE THREAD

**Issue by rune139** [pljson/pljson#222]

**Comment by rune139** [comment]
sorry missed the description:
I am now using PL/JSON Version 3.4.1. 

These both rules added to the XSL on lines 158 and following like:
...
      
      <xsl:when test="contains($s,'&amp;')">
        <xsl:value-of select="substring-before($s,'&amp;')"/><![CDATA[&amp;]]><xsl:value-of select="substring-after( $s, '&amp;' )"/>   
      </xsl:when>
      
      <xsl:when test="contains($s,'&lt;')">
        <xsl:value-of select="substring-before($s,'&lt;')"/><![CDATA[&lt;]]><xsl:value-of select="substring-after( $s, '&lt;' )"/>   
      </xsl:when>
...
cannot be combined!

That means, if a selected column contains 
- 2 ampersand characters OR 
- 2 less-than characters OR 
- an ampersand and a lt character 
following error occurs also in version PL/JSON 3.4.1

select sql_query
, pljson_parser.get_version
, pljson_util_pkg.sql_to_json( sql_query )
--from ( SELECT 'SELECT ''a''||'''||chr(38)||'''||''b'' from dual' sql_query from dual );   --Ok 1)
--from ( SELECT 'SELECT ''a''||'''||chr(60)||'''||''b'' from dual' sql_query from dual );   --Ok 2)
from ( SELECT 'SELECT ''a''||'''||chr(38)||'''||''b''||'''||chr(60)||'''||''d'' from dual' sql_query from dual );     --NOT OK! 3)
--from ( SELECT 'SELECT ''a''||'''||chr(38)||'''||''b''||'''||chr(60)||'''||''d'' from dual' sql_query from dual );     --NOT OK! 4)

result 1):   SELECT 'a'||'&'||'b' from dual	PL/JSON 3.4.1	[SPED.PLJSON_LIST]
result 2):   SELECT 'a'||'<'||'b' from dual	PL/JSON 3.4.1	[SPED.PLJSON_LIST]

BUT ERROR with 3) and 4)

ORA-31011: XML-Parsing nicht erfolgreich
ORA-19202: Fehler bei XML-Verarbeitung 
LPX-00241: entity reference is not well formed
Error at line 1
 aufgetreten
ORA-06512: in "SPED.PLJSON_UTIL_PKG", Zeile 315
ORA-06512: in "SPED.PLJSON_UTIL_PKG", Zeile 325
ORA-06512: in Zeile 1
31011. 00000 -  "XML parsing failed"
*Cause:    XML parser returned an error while trying to parse the document.
*Action:   Check if the document to be parsed is valid.

**Comment by d-javu** [comment]
This seems to be a problem with XMLType, not the stylesheet.
I have a solution using DBMS_XSLPROCESSOR that works correctly.
Will polish and publish in a bit.

**Comment by dsnz** [comment]
@rune139 
there is a fix merged into the branch
download the current source code (not any release file as there is no new release yet)
and do any experiments you like with &. <. etc and report here if all is ok

**Comment by d-javu** [comment]
I went down the Oracle rabbit-hole and found an XMLTYPE bug in MOS, see (Doc ID 1141935.1)
Their suggested workaround is simpler and less code than going the DBMS_XSLPROCESSOR route as I indicated above.

Since I ended up undoing the XSL changes from #215, I looked at issue #213 and tested that this version also fixes the case from @rune139 with all the special characters.

Tested like this:
```
set define off;

CREATE TABLE test (
        id      INTEGER,
        data    VARCHAR2(64)
);

INSERT INTO test VALUES(1, 'a&b');
INSERT INTO test VALUES(2, 'a&&b');
INSERT INTO test VALUES(3, 'a&<''"''>&b');
INSERT INTO test VALUES(4, 'a&lt;&amp;&gt;b');
COMMIT;

select sql_query
, pljson_util_pkg.sql_to_json( sql_query )
from ( SELECT 'SELECT * from test' sql_query from dual );

select sql_query
, pljson_util_pkg.sql_to_json( sql_query )
from ( SELECT 'SELECT ''a&<"''''">&b'' xyz from dual' sql_query from dual );
```

**Comment by d-javu** [comment]
Damn, you're quick, can't even make a proper comment on the bug befor the fix is merged. :+1:

**Comment by dsnz** [comment]
@d-javu 
your comment stays here, the full issue discussion is linked with the pull request
and you can still (if you like) go back to the pull request and add an extra comment ;)

**Comment by rune139** [comment]
@dsnz
sorry, don't know how to download the current source Code..

**Comment by dsnz** [comment]
go to https://github.com/pljson/pljson/tree/develop_v3
middle-right-top you will see a big green button "Code"
click on it then choose bottom selection "Download ZIP"

**Comment by rune139** [comment]
@dsnz
thank's for the download tip…
That looks very good for me!
Tested with mulitple Special characters w/o any Problem.
Are there any other changes beside of ./src/addons/pljson_util_pkg.package.sql ?
Thank you.

**Comment by dsnz** [comment]
there are no other changes
I will leave this issue open one more day just in case
and then I will make a new release

**Comment by dsnz** [comment]
@d-javu 
please post here if you are going to produce further pull requests or you are finished with testing all examples
so that I know when to produce a new release and update version 2 as well with the new fixes

**Comment by d-javu** [comment]
I've tested all examples, and I think this is it for now.
See PR #227 that was just created.
