### ISSUE TITLE
about  number format of pljson_util_pkg.sql_to_json

### ISSUE THREAD

**Issue by Dark-Athena** [pljson/pljson#237]
if the code like this 
` 
  <xsl:template match="text()[not(string(number())='NaN' or
                      (starts-with(.,'0' ) and . != '0' and
not(starts-with(.,'0.' ))) or
                      (starts-with(.,'-0' ) and . != '-0' and
not(starts-with(.,'-0.' )))
                      )]">
    <xsl:value-of select="."/>
  </xsl:template>`,
then run 
`select pljson_util_pkg.sql_to_json(p_sql       => 'select 0.1 a from dual',
                                   p_max_rows  => 1,
                                   p_skip_rows => 0)  from dual;` 
,return
 `ORA-20100: JSON Scanner exception @ line: 1 column: 23 - Unexpected char: .
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 506
ORA-06512: 在 "****.PLJSON_PARSER", line 176
ORA-06512: 在 "****.PLJSON_PARSER", line 538
ORA-06512: 在 "****.PLJSON_PARSER", line 814
ORA-06512: 在 "****.PLJSON", line 24
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 490
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 521
ORA-06512: 在 line 1`.

because , the number like `0.***` in oracle , is `.***` actually. 

I founded a solution from a blog（https://blog.csdn.net/gear1023/article/details/51064842） ,
`<xsl:template match="text()[not (string(number())='NaN')]">
    <xsl:choose>
      <xsl:when test="starts-with(., '.')">
          <xsl:value-of select="concat('0', .)"/>
      </xsl:when>
      <xsl:otherwise><xsl:value-of select="."/></xsl:otherwise>
    </xsl:choose>
  </xsl:template> `

but it's caused another issues when running 
`select pljson_util_pkg.sql_to_json(p_sql       => q'{select '01' a from dual}',
                                   p_max_rows  => 1,
                                   p_skip_rows => 0)  from dual;`

`ORA-20101: JSON Parser exception @ line: 1 column: 25 - A comma seperator is probably missing
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 509
ORA-06512: 在 "****.PLJSON_PARSER", line 552
ORA-06512: 在 "****.PLJSON_PARSER", line 722
ORA-06512: 在 "****.PLJSON_PARSER", line 639
ORA-06512: 在 "****.PLJSON_PARSER", line 703
ORA-06512: 在 "****.PLJSON_PARSER", line 639
ORA-06512: 在 "****.PLJSON_PARSER", line 703
ORA-06512: 在 "****.PLJSON_PARSER", line 817
ORA-06512: 在 "****.PLJSON", line 24
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 489
ORA-06512: 在 "****.PLJSON_UTIL_PKG", line 520
ORA-06512: 在 line 1`

finally,I fixed these issues like this 
`
  <xsl:template match="text()[not(string(number())='NaN' or
                      (starts-with(.,'0' ) and . != '0' and
not(starts-with(.,'0.' ))) or
                      (starts-with(.,'-0' ) and . != '-0' and
not(starts-with(.,'-0.' )))
                      )]">
 <xsl:choose>
      <xsl:when test="starts-with(., '.')">
          <xsl:value-of select="concat('0', .)"/>
      </xsl:when>
      <xsl:otherwise><xsl:value-of select="."/></xsl:otherwise>
    </xsl:choose>
    <xsl:value-of select="."/>
  </xsl:template>`

**Comment by dsnz** [comment]
Hi,

your change (formatted properly)

```
  <!-- number (no support for javascript mantissa) -->
  <xsl:template match="text()[not(string(number())='NaN' or
                      (starts-with(.,'0' ) and . != '0' and
not(starts-with(.,'0.' ))) or
                      (starts-with(.,'-0' ) and . != '-0' and
not(starts-with(.,'-0.' )))
                      )]">
    <xsl:choose>
      <xsl:when test="starts-with(., '.')">
        <xsl:value-of select="concat('0', .)"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="."/>
      </xsl:otherwise>
    </xsl:choose>
    <xsl:value-of select="."/>
  </xsl:template>
```

does not fix the problem you mentioned
I still get the same error

but I saw ```<xsl:value-of select="."/>``` appear both inside and outside the "when" statement and it seemed to me not okay (something I verified from the dbms_output message)
so I removed it and it seems okay now

the final code is

```
  <!-- number (no support for javascript mantissa) -->
  <xsl:template match="text()[not(string(number())='NaN' or
                      (starts-with(.,'0' ) and . != '0' and
not(starts-with(.,'0.' ))) or
                      (starts-with(.,'-0' ) and . != '-0' and
not(starts-with(.,'-0.' )))
                      )]">
    <xsl:choose>
      <xsl:when test="starts-with(., '.')">
        <xsl:value-of select="concat('0', .)"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="."/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
```

please verify that this is the code you had in mind

**Comment by dsnz** [comment]
Hi,

I think the final code is ok. I have just committed the fix.
Since there is nothing else, I will close this issue.
You can still update here if necessary.

Thank you for the contribution.

**Comment by Dark-Athena** [comment]
sorry，i made a mistake when I copy the code ,my final code is
 `
  <xsl:template match="text()[not(string(number())='NaN' or
                      (starts-with(.,'0' ) and . != '0' and
not(starts-with(.,'0.' ))) or
                      (starts-with(.,'-0' ) and . != '-0' and
not(starts-with(.,'-0.' )))
                      )]">
 <xsl:choose>
      <xsl:when test="starts-with(., '.')">
          <xsl:value-of select="concat('0', .)"/>
      </xsl:when>
      <xsl:otherwise><xsl:value-of select="."/></xsl:otherwise>
    </xsl:choose>
  </xsl:template> `

**Comment by dsnz** [comment]
it's ok, we got the correct code anyway
please when you post code include it inside a pair of "```" (3 back-quotes) so that the formatting is kept intact

**Comment by rudolf-neubauer** [comment]
Unfortunately this applies only to 
alter session set NLS_NUMERIC_CHARACTERS='.,'; --AMERICAN
within sessions where e.g.
alter session set NLS_NUMERIC_CHARACTERS=',.'; --GERMAN
is set, this Change will not work..
sorry.

**Comment by rudolf-neubauer** [comment]
Unfortunately this applies only to sessions where NLS_NUMERIC_CHARACTERS is set to AMERICAN Format like:
alter session set NLS_NUMERIC_CHARACTERS='.,'; 

Within sessions where e.g.
alter session set NLS_NUMERIC_CHARACTERS=',.'; --GERMAN
is set, this Change will not work..
sorry.
You may test with this query:
select pljson_util_pkg.sql_to_json('select 1/2 as nr from dual').to_char() from dual;
sorry,

**Comment by dsnz** [comment]
Hi,

this is an interesting localization issue
thanks for bringing to attention

you have given me an idea for a fix that will work for all cases of NLS_NUMERIC_CHARACTERS and will be ready by this weekend

**Comment by dsnz** [comment]
@rudolf-neubauer 
Hi,
I have made a fix in both v2 and v3.
Please run your tests and comment if everything is okay.

**Comment by rudolf-neubauer** [comment]
@dsnz
Hi, 
sorry, when I take latest version pljson-3.5.0.zip from https://github.com/pljson/pljson/releases/tag/v3.5.0  I cannot see any changes

**Comment by dsnz** [comment]
Hi,

There is no new release yet (there will be one once all changes in this issue and other issues are verified).
To get the latest updates go to tab "Code", select branch "develop_v3" and further right to the branch selection drop-down there is a big green "Code" drop-down, click on the little triangle at the right pointing down and a window with some options will open, select the last one "Download ZIP".

![GitHub_Download ZIP](https://user-images.githubusercontent.com/9822496/103205217-c2fbaa00-4901-11eb-8ab0-33b607605f84.jpg)

**Comment by rudolf-neubauer** [comment]
Thanks,
now I found your changes in
./src/pljson_parser.impl.sql and
./src/addons/pljson_util_pkg.package.sql
and tested for GERMAN and AMERICAN Settings of NLS_NUMERIC_CHARACTERS .
That all looks OK now!

**Comment by dsnz** [comment]
thank you
