### ISSUE TITLE
pljson_util_pkg.sql_to_json - string with leading zero returns exception 

### ISSUE THREAD

**Issue by alexander-semerik** [pljson/pljson#245]
Hello could you please check the following samples:
correct one:
select pljson_util_pkg.sql_to_json('select ''a003'' from dual') from dual;

with exception:
select pljson_util_pkg.sql_to_json('select ''003'' from dual') from dual;

ORA-20101: JSON Parser exception @ line: 1 column: 27 - A comma seperator is probably missing:

thank you!

**Comment by dsnz** [comment]
thank you for bringing to attention

it's all due to a piece of xsl stylesheet code that I commented in a previous update
(since I am not usually working with xsl stylesheets and so I thought that this code was superfluous)

a fix will be committed soon

**Comment by dsnz** [comment]
Hi,
it's fixed in both versions 2 and 3

**Comment by alexander-semerik** [comment]
Hi, thanks a lot!
