### ISSUE TITLE
pljson getstring with special character

### ISSUE THREAD

**Issue by NiltonMaganha** [pljson/pljson#252]
Hi, I saw in Issues already posted in past, that some other people also faced with problems related to special character.
The solutions or alternatives that I found didn't gave me an idea of how to get string from an external webservice that is transferring Latin characters, accentuation, like the ones that we have in Brazil, France etc.

The database configuration of the company is:
NLS_NCHAR_CHARACTERSET	AL16UTF16	NCHAR Character set
NLS_CHARACTERSET	WE8MSWIN1252	Character set

When I execute the command:

     l_results_list := arr_;

     for i in 1..l_results_list.count  loop

          v_location_code          := pljson_ext.get_number(pljson(l_results_list.GET(i)), 'CodigoLotacao');
          v_name                       := pljson_ext.get_string(pljson(l_results_list.GET(i)), 'Nome');
          v_occupation               := pljson_ext.get_string(pljson(l_results_list.GET(i)), 'Cargo');
          v_located                     := pljson_ext.get_string(pljson(l_results_list.GET(i)), 'Lotacao');
          v_hierarchical group    := pljson_ext.get_string(pljson(l_results_list.GET(i)), 'GrupoHierarquico');           

      end loop;

I'm receiving

 {
  "CodigoLotacao" : 49772,
  "CodigoEmpresa" : 1,
  "Matricula" : 102664,
  "ExibicaoMatricula" : "005269",
  "Nome" : "FUNCIONARIO 78351",
  "Cargo" : "ANALISTA DE RECURSOS HUMANOS S\u00C3\u0160NIOR",
  "Lotacao" : "SE\u00C3\u2021\u00C3\u0192O 01.01.02.01.01.01",
  "CentroCusto" : null,
  "GrupoHierarquico" : "SE\u00C3\u2021\u00C3\u0192O 01.01.02.01.01.01"
}

where in Occupation (Cargo) is appearing : Analista de Recursos Humanos Sênior

(human resource Analyst Senior),

but in Portuguese, Senior has an accentuation Sênior that is being converted to \u00C3\u0160

Does anyone have a tip to allow me convert this special characters without change anything in database configuration?

Thanks

Nilton Maganha

**Comment by dsnz** [comment]
Hi,

your db is single byte
how you expect get_string to return Unicode ?

on the other hand your problem description is not good and is confusing
you posted some code with get_string and then as a output a json text !!

please make clear what is your input json, what you get from get_string for "Cargo" and what you expect to get

and preferably post a single pl/sql annonymous package that demonstrates your issue
(your json text can be in a varchar2 variable)

**Comment by NiltonMaganha** [comment]
In case you live in a Country of America or West Europe, and is receiving a webservice from an external company that also belong to this area; according to the origin of the data, for example France or Brazil, some words receive accentuation (déjà-vu, sênior etc).
If you work in a company that still has Oracle Database configured with WE8MSWIN125 and need to convert information that is being transferred in utf8 (from one of the countries already mentioned), you have how to do it using the attached example.
Of course it wouldn't work if you are receiving UTF-8 from a country that doesn't use Roman Alphabet (e.g. China, Thailand, Japan).

procedure get_employee(company_id) is

v_name            varchar2(255);
url                    varchar2(4000);
arr_                   json_list;
l_results_list      json_list;

.....

begin

url := 'http:// .... external company url .../company_id/employee';

-- routine to establish connection , transfer bearer and execute the above url
my_connection_routine;

l_results_list := arr_;

 for i in 1..l_results_list.count  loop

      v_location_code          := pljson_ext.get_number(pljson(l_results_list.GET(i)), 'CodigoLotacao');
 
     -- wrong way because you will receive content like : S\u00C3\u0160NIOR instead of Sênior
     --v_occupation             := pljson_ext.get_string(pljson(l_results_list.GET(i)), 'Cargo');

     -- right way to convert UTF8 to WE8MSWIN1252
       v_occupation               := convert(pljson_ext.get_string(pljson(l_results_list.GET(i)), 'Cargo'),'WE8MSWIN1252','AL32UTF8');
       dbms_output.put_line('occupation WE8MSWIN125:'||v_occupation);
  end loop;
end;

>>
occupation WE8MSWIN125:ANALISTA DE RECURSOS HUMANOS SÊNIOR

**I really expect that this answer will help someone else that is facing with the same problem!!!**

**Comment by dsnz** [comment]
Hi,

I think I understood your issue now.
Unfortunately people use JSON in ways against standards (ie not in UTF8) and this has become established and so we don't try to convert charactersets and instead leave this to the programmer. An extra reason is that not all of Unicode can be converted to single byte characterset of course, and since we can't do miracles it's again only the programmer who can decide what's best to do.

In your case I am not sure that convert will work if the string you get contains unicode escape sequences with **\u** and I cannot test this since I only use Unicode database. I also do not know **if your JSON text was indeed encoded in utf8 bytes or contained \u escape sequences from start**.

However I propose that you try also my example code below and see if it suits you

```
declare
  text varchar2(32767) := 'S\u00C3\u0160NIOR';
  var varchar2(32767);
begin
  -- := convert(text, 'WE8MSWIN1252', 'AL32UTF8');
  text := replace(text, '\u', '\');
  --dbms_output.put_line(text);
  var := unistr(text);
  dbms_output.put_line(var);
  dbms_output.put_line(compose(var)); -- this should help in case of composing chars with accents
end;
```

**Comment by NiltonMaganha** [comment]
Ok, but the example that I gave worked properly, at least to receive data from another Brazilian company that is transferring in UTF-8 and convert to WE8MSWIN125, because this is the character set used by the company where I'm working for, and I don't have how to change anything related to database configuration.

Answering the doubt, Yes, Convert is receiving unicode \u (e.g. S\u00C3\u0160NIOR  ) and changing it to Sênior (WE8MSWIN1252)
