### ISSUE TITLE
Extracted details not able to insert or unable use this for cursor loop 

### ISSUE THREAD

**Issue by ajsenthil** [pljson/pljson#254]
Hi 
I tried to insert json extracted details into a table, but throws an error. Find the below details for your reference.

Error(5,5): PL/SQL: ORA-22905: cannot access rows from a non-nested table item

declare
begin
insert into temp_json_job
    select receivedDate, job,lineNo,cinType,mcinPcin 
    from pljson_table_test pljtt,
    table(
    pljson_table.json_table(
    pljtt.col,
    pljson_varray('headerField.date', 'master.decRef.jobNo','master.mastrCnsgmtDec[*].MCRef.lineNo','master.mastrCnsgmtDec[*].mcResponse.cinType', 'master.mastrCnsgmtDec[*].mcResponse.mcinPcin' ),
    pljson_varray( 'receivedDate','job','lineNo', 'cinType','mcinPcin'),    
     table_mode => 'nested')
    );
end;

**Comment by ajsenthil** [comment]
Tried another way also but getting error 
error:     PLS-00497: cannot mix between single row and multi-row (BULK) in INTO list

create or replace type id_json_job_type as object (
RECEIVEDDATE       VARCHAR2(10),  
JOB                VARCHAR2(10) , 
LINENO             NUMBER(5)    , 
CINTYPE            VARCHAR2(10)  ,
MCINPCIN           VARCHAR2(100));
/

CREATE OR REPLACE FUNCTION id_json_insert RETURN id_json_job_type AS
lv_return id_json_job_type;
lv_query varchar2(1000);
begin
lv_query :='
    select receivedDate, job,lineNo,cinType,mcinPcin 
    from pljson_table_test pljtt,
    table(
    pljson_table.json_table(
    pljtt.col,
    pljson_varray(''headerField.date'', ''master.decRef.jobNo'',''master.mastrCnsgmtDec[*].MCRef.lineNo'',''master.mastrCnsgmtDec[*].mcResponse.cinType'', ''master.mastrCnsgmtDec[*].mcResponse.mcinPcin'' ),
    pljson_varray( ''receivedDate'',''job'',''lineNo'', ''cinType'',''mcinPcin''),    
     table_mode => ''nested'')
    );';
    execute immediate lv_query bulk collect into lv_return;
    return lv_return;
end;

**Comment by dsnz** [comment]
hi
please provide example data for table pljson_table_test 
so we can try your code

**Comment by ajsenthil** [comment]
Please find the below data
{
  "headerField" : {
    "senderID" : "TSLINENSA123",
    "receiverID" : "INNSA1",
    "messageID" : "SACHM22",
    "sequenceOrControlNumber" : 537,
    "date" : "20210619",
    "reportingEvent" : "SCE"
  },
  "master" : {
    "decRef" : {
      "msgTyp" : "F",
      "prtofRptng" : "INNSA1",
      "jobNo" : 537,
      "jobDt" : "20210618",
      "rptngEvent" : "SCE",
      "csn_no" : 1001806,
      "csn_dt" : "20210619",
      "errorCode" : [ {
        "errorCode" : "00",
        "errorMessage" : "Successful"
      } ]
    },
    "authPrsn" : {
      "errorCode" : [ {
        "errorCode" : "00",
        "errorMessage" : "Successful"
      } ]
    },
    "vesselDtls" : {
      "errorCode" : [ {
        "errorCode" : "00",
        "errorMessage" : "Successful"
      } ]
    },
    "voyageDtls" : {
      "errorCode" : [ {
        "errorCode" : "00",
        "errorMessage" : "Successful"
      } ]
    },
    "mastrCnsgmtDec" : [ {
      "MCRef" : {
        "lineNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932263600"
      }
    }, {
      "MCRef" : {
        "lineNo" : 2,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 2,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 3,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 4,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 5,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 6,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 7,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 8,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 9,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 10,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932265000"
      }
    }, {
      "MCRef" : {
        "lineNo" : 3,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 2,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932263800"
      }
    }, {
      "MCRef" : {
        "lineNo" : 4,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932263900"
      }
    }, {
      "MCRef" : {
        "lineNo" : 5,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264000"
      }
    }, {
      "MCRef" : {
        "lineNo" : 6,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264100"
      }
    }, {
      "MCRef" : {
        "lineNo" : 7,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 2,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 3,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 4,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 5,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 6,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 7,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264200"
      }
    }, {
      "MCRef" : {
        "lineNo" : 8,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264300"
      }
    }, {
      "MCRef" : {
        "lineNo" : 9,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264400"
      }
    }, {
      "MCRef" : {
        "lineNo" : 10,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264500"
      }
    }, {
      "MCRef" : {
        "lineNo" : 11,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 2,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      }, {
        "eqmtSeqNo" : 3,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264600"
      }
    }, {
      "MCRef" : {
        "lineNo" : 12,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264700"
      }
    }, {
      "MCRef" : {
        "lineNo" : 13,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264800"
      }
    }, {
      "MCRef" : {
        "lineNo" : 14,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932264900"
      }
    }, {
      "MCRef" : {
        "lineNo" : 15,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "prevRef" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "locCstm" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnshpr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDoc" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "trnsprtDocMsr" : {
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      },
      "itemDtls" : [ {
        "crgoItemSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "trnsprtEqmt" : [ {
        "eqmtSeqNo" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "itnry" : [ {
        "prtOfCallSeqNmbr" : 1,
        "errorCode" : [ {
          "errorCode" : "00",
          "errorMessage" : "Successful"
        } ]
      } ],
      "mcResponse" : {
        "cinType" : "PCIN",
        "mcinPcin" : "21PC10061932263700"
      }
    } ]
  }
}

**Comment by dsnz** [comment]
ok, if I understand this is a single row in the table
allow 1-2 hours to take the time to try your example and see what's happening

**Comment by dsnz** [comment]
this

```
insert into temp_json_job
select receivedDate, job,lineNo,cinType,mcinPcin
from pljson_table_test pljtt,
table(
pljson_table.json_table(
pljtt.col,
pljson_varray('headerField.date',
'master.decRef.jobNo',
'master.mastrCnsgmtDec[*].MCRef.lineNo',
'master.mastrCnsgmtDec[*].mcResponse.cinType',
'master.mastrCnsgmtDec[*].mcResponse.mcinPcin' ),
pljson_varray( 'receivedDate', 'job', 'lineNo', 'cinType', 'mcinPcin'),
table_mode => 'nested')
)
```

works within sql

but not within plsql (your 1st example, slightly rewritten to be easier to understand and formatted as code)
and as you may have found it's a plsql limitation

my attempt with execute immediate

```
declare
var_sql varchar2(32767) := q'{
insert into temp_json_job
select receivedDate, job,lineNo,cinType,mcinPcin
from pljson_table_test pljtt,
table(
pljson_table.json_table(
pljtt.col,
pljson_varray('headerField.date',
'master.decRef.jobNo',
'master.mastrCnsgmtDec[*].MCRef.lineNo',
'master.mastrCnsgmtDec[*].mcResponse.cinType',
'master.mastrCnsgmtDec[*].mcResponse.mcinPcin' ),
pljson_varray( 'receivedDate', 'job', 'lineNo', 'cinType', 'mcinPcin'),
table_mode => 'nested')
)
}';
begin
  execute immediate var_sql;
end;
```

works fine ;)

finally your 2nd example does not work because you bulk collect into ID_JSON_JOB_TYPE
when you should bulk collect into a new type "table of ID_JSON_JOB_TYPE"
however the execute immediate above is simpler and faster

**Comment by ajsenthil** [comment]
Thanks. It is working Fine
