### ISSUE TITLE
Getting numeric or value error error in case of very large input json

### ISSUE THREAD

**Issue by kinju4374** [pljson/pljson#255]
Hi,

I am getting an error on the following line of code when the JSON is very large.

`V_RESULT_JSON := JSON(V_JSON_CLOB);`

Can you suggest any solution or workaround available? It's working fine when the JSON is not large but in one case when we got a large JSON then we got numeric or value error PLJSON_PARSER and ISERVICES.PLJSON

Thanks

**Comment by jsumners** [comment]
What is the type of `V_RESULT_JSON`? I'm guessing it is a `varchar2`. In that case, a `clob` will very easily exceed the size boundary of `varchar2`.

**Comment by dsnz** [comment]
I agree with @jsumners and you should also give more information,

1. what version of pljson you use (if you don't know, tell us when and from where you downloaded it)
2. the whole error stack trace you get
