### ISSUE TITLE
Error with data type json_value in oracle 19

### ISSUE THREAD

**Issue by nzambrano** [pljson/pljson#258]
good day

the problem was caused by updating the database to Oracle Database 19c Enterprise Edition Release 19

when trying to declare a variable of type json_value

example:

begin
declare v_json_value json_value;
begin
    null;
end;
end;

PLS-00488: 'JSON_VALUE' must be a type

I have many packages that use that type of data, there is a solution other than change: json_value -> pljson_value

thank you very much for all the help

**Comment by jsumners** [comment]
What version of PL/JSON are you using? We have not conflicted with the native Oracle implementation for quite some time.

**Comment by nzambrano** [comment]
estoy usando la ultima version ( 2.5.3)

**Comment by nzambrano** [comment]
> What version of PL/JSON are you using? We have not conflicted with the native Oracle implementation for quite some time.

I am using the latest version (2.5.3)

**Comment by jsumners** [comment]
The latest release is https://github.com/pljson/pljson/releases/tag/v3.5.2

**Comment by nzambrano** [comment]
> The latest release is https://github.com/pljson/pljson/releases/tag/v3.5.2

sorry for the confusion but the package.json is not updated and shows 2.5.3, but actually the version was a clone made two weeks ago that I understand must be the last one (3.5.2), run a git log and show that the last change was
Merge: e318f5a b018f4a
Author: E.I.Sarmas <dsnz@users.noreply.github.com>
Date: Sat Mar 6 18:37:59 2021 +0200
    Merge pull request # 248 from dsnz / master
    README for release 2.5.3

**Comment by jsumners** [comment]
Sorry, but you should be using the `pljson_value` type if you are working with this library.

**Comment by nzambrano** [comment]
> Sorry, but you should be using the `pljson_value` type if you are working with this library.

I understand, in the same way, thank you very much for all the help provided and this library so useful, greetings
