### ISSUE TITLE
Pass plsjon_list into cursor

### ISSUE THREAD

**Issue by carlosen14** [pljson/pljson#262]
I might be trying to achieve similar to #58 and #161, but just wanted to know if I can get any help, even my case could be more related to #164.

I have a `pljson_list` filled with `pljson` objects. But as the example on those issues, i can't put the whole `pljson_list` inside a `varchar2`, because it can get greater than `varchar2` size and throws an overflow. Wanted to put it inside a cursor with this, modifying your examples but I get this error. 

This is just a small example where I want to convert the `pljson_list` into a char (using `.tochar()`), and pass it to `pljson_table.json_table()`, and into a table and put it inside the `SYS_REFCURSOR`, as my real case is a procedure which has an argument  `OUT SYS_REFCURSOR`.  I tried other of your examples, assign it to a CLOB, but I got an error on the client (python using cx_Oracle) `ODPI [4249840] 2021-10-13 17:30:26.373: internal error DPI-1002: invalid OCI handle (dpiLob_getSize / get length)`, I think is DB error, but I have no privileges to modify.

```
DECLARE
p_cursor SYS_REFCURSOR;
BEGIN
	OPEN p_cursor FOR 
	select * from table(pljson_table.json_table(     -- <<< error on this line
	'[
        {
            "periodo": "20206",
            "pidm": 331,
            "matricula": "00331"
        },
        {
            "periodo": "20206",
            "pidm": 339,
            "matricula": "00339"
        },
        {
            "periodo": "20212",
            "pidm": 643,
            "matricula": "00123"
        }
	]',
	  pljson_varray('[*].periodo', '[*].pidm', '[*].matricula'),
	  pljson_varray('periodo', 'pidm', 'matricula'),
	  table_mode => 'nested'
	));
	  FOR r_product IN p_cursor
	  LOOP
	    dbms_output.put_line( r_product.periodo || ': $' ||  r_product.pidm); 
	  END LOOP;
END;
```

SQL Error [6550] [65000]: ORA-06550: line 5, column 16:
PL/SQL: ORA-22905: cannot access rows from a non-nested table item

**Comment by carlosen14** [comment]
I cannot init v_stat this way because my pljson_list.tochar is larger than 32767.

```sql
v_stat varchar2(32767) := q'#
	select * from table(pljson_table.json_table(
	'[
        {
            "periodo": "20206",
            "pidm": 331,
            "matricula": "00331"
        },
        {
            "periodo": "20206",
            "pidm": 339,
            "matricula": "00339"
        },
        {
            "periodo": "20212",
            "pidm": 643,
            "matricula": "00123"
        }
	]',
	  pljson_varray('[*].periodo', '[*].pidm', '[*].matricula'),
	  pljson_varray('periodo', 'pidm', 'matricula'),
	  table_mode => 'nested'
	))
#';
```


is it viable that i can assemble the `open v_cur for v_stat;` using concatenation?. 
For example: (i know this actually does not compile)

```sql
v_stat := q'#
select * from table(pljson_table.json_table(
' || p_list.tochar ||'
)) 
#';  
```

**Comment by dsnz** [comment]
another solution is to save the whole json text in a clob column in a text so that you don't need to assign to a variable

**Comment by carlosen14** [comment]
Sorry to bother you, i was just asking for some help since this is no a basic pl/sql case.
