### ISSUE TITLE
Migrating from 1.0.5

### ISSUE THREAD

**Issue by hmmftg** [pljson/pljson#265]
Hello
first of all thank you for your great work in this project
we have have used this project years ago at version 1.0.5 in oracle 10g
now we want to use our old code in new server for another project which is currently on 11g and is told to be upgraded to 12c :) 
my question is: do you recommend us to update pljson to latest and rename all usages and be up to date
or it will be better for us to dont touch any thing about json objects and forget new versions?
one other thing to mention is we have the use for get_boolean method and we have changed some of your codes to achieve it, does new version have get_boolean in itself?
thanks for your help

**Comment by dsnz** [comment]
Hi,

you can definitely download the latest **2.xx.yy** release and use it without any change in your code (of course uninstall completely the old version first and then install the new version)
for peace of mind you can test first by installing the new release in a new schema and running your code
(default install script does not run the global grants and synonyms script and so this is safe) 

I strongly suggest that you try also the latest **3.xx.yy** release which needs only some minor renames in your code, ie. some package calls and types must be renamed from json_<xxx> to pljson_<xxx>
you can find more information in the README of the **develop_v3** branch

both version 2 and version 3 have a get_bool method (not get_boolean !) which should do your job (in fact I wonder what for you changed the code yourself to get the boolean value of a field, unless you have some specialized need)

**Comment by hmmftg** [comment]
hi
thanks for your reply
I struggled a lot with v3 and after rename pljsons, I couldn't validate all of our codes, it fails on json_value types
latest v2 could compile with get_bool renames
but couldn't test functionality yet

it seems our new version has to be faster, should I struggle on v3?

**Comment by dsnz** [comment]
latest version 2 is much faster then the version you have
however if you want top speed then your choice is version 3 (of course top speed for pljson, considering also that pljson is a pure plsql software)

indeed version 3 has no json_value type, instead there is a json_element type that is roughly equivalent to it
but if you look carefully at the api calls (ie. the methods that the types support plus the package calls) you will see that there is much less need to use variables of type json_element in your code
don't expect that you can blindly rename some calls or change some variable types and you are finished
you must know what your code is doing and change it like you are writing it right now (but of course with much less effort)

you can also post here a self-contained example that causes trouble to you with version 3 so I may give you ideas/guidance on how to upgrade

**Comment by hmmftg** [comment]
we plan to migrate to v3 later
I've found two bugs in v2:
in oracle 11g, if we don't fill an string tag and try to get_string, Error dispatch on null self occurs
for our time limit I fix pljson type with this:
         IF elem IS NULL THEN 
	 	RETURN NULL;
	 END IF;
there was a comment in get_string which seems better fit, but I prefer to ask here.
this error is also happening in get_bool

**Comment by dsnz** [comment]
Hi,

I don't understand well what the bug is.
Please post here a short working code that demonstrates the bug.

**Comment by hmmftg** [comment]
Based on ex1.sql, if we had this:
`declare
  obj json;
  obj2 json;
  sub json_value;
begin
  obj := json('{"a": true }');
  obj.print;
  --more complex json:
  obj := json('
{
  "a": null,
  "b": 12.243,
  "c": 2e-3,
  "d": [true, false, "abdc", [1,2,3]],
  "e": [3, {"e2":3}],
  "f": {
    "f2":true
  }
}');
  dbms_output.put_line('g tag: '|| obj.get_string('g'));
  sub := obj.get('f');
  obj2 := json(sub);
  IF obj2.get_bool('g') THEN 
      dbms_output.put_line('g tag: true');
  END IF;
  obj.print;
  obj.print(false); --compact way
end;`
we get:
`SQL Error [30625] [99999]: ORA-30625: method dispatch on NULL SELF argument is disallowed`

**Comment by dsnz** [comment]
yes indeed, some code stayed in comments when it should have been uncommented (with some changes)
big oversight, good you caught this
in the next hours there will be a new release to download
