### ISSUE TITLE
Errors using Oracle characterset  IW8MSWIN1255

### ISSUE THREAD

**Issue by mpniel** [pljson/pljson#269]
Hello,

My problem is that when the  table's data values are in hebrew language from characterset  IW8MSWIN1255 then the fetched data is not displayed correctly as hebrew data. Instead I get numbers like :  \u05DC\u05D0    etc
I am using pljson  3..6.1.
Oracle 12.1.0.2. No upgrade planned for now.
The code is:
list12 :== pljson_dyn.executelist(' select * from table');
list12.print;

How to use the pljson with  characterset IW8MSWIN1255 ?

**Comment by dsnz** [comment]
Hi,

the codes   \u05DC\u05D0  are unicode codes 

since you say that the table holds single-byte text
have you checked the obvious that the query tool you use (eg. sqlplus) runs with NLS_LANG that is unicode ?

if you do a plain 'select * from table;' what do you get ?

**Comment by mpniel** [comment]
I am using TOAD for Oracle.
The nls_lang I use is defined in registry as:   AMERICAN_AMERICA.IW8MSWIN1255 .
A plain select works OK.

**Comment by dsnz** [comment]
okay, had to check the very basic  :)

well in your code and before the list12.print add the following
```
pljson_printer.ascii_output  := false;
```

and then try again

**Comment by mpniel** [comment]
Great!
It solve the problem.
Thanks very much!
What is the explanation?

**Comment by dsnz** [comment]
welcome,

the explanation is that the print code by default prints single byte characters in ascii as escaped byte sequences
(the escaping method has the curious and useful property that it shows the unicode byte sequence and not the original byte :D)
the flag ```ascii_output := false;``` disables this escaping and you get your plain 8-bit characters

**Comment by mpniel** [comment]
Hi,

I don't need the unicode display at all.
How can I do a global change thus all the developers won't need to set the  statement ascii_output := false; ?

**Comment by dsnz** [comment]
hi,

in package **pljson_printer**
change line 24 to

```  ascii_output boolean    not null := false;```

compile and you ar ok

**Comment by mpniel** [comment]
Hi,

I don't need the unicode display at all.
How can I do a global change thus all the developers won't need to set the
statement ascii_output := false; ?



בתאריך יום ב׳, 11 באפר׳ 2022, 23:21, מאת E.I.Sarmas ‏<
***@***.***>:

**Comment by dsnz** [comment]
what do you mean by global change ?
if you modify the package source code (package **pljson_printer**), then it affects all developers
no developer should need to include code to set the **ascii_output** variable himself/herself
if you need to reinstall PLJSON at times then you should also modify the source in your repos or wherever else it is stored

**Comment by boriborm** [comment]
You can change this in session logon trigger.

вт, 11 окт. 2022 г., 12:21 E.I.Sarmas ***@***.***>:
