### ISSUE TITLE
Get Number

### ISSUE THREAD

**Issue by SELLAM** [pljson/pljson#271]
Hi All,

how can i get the value of a column number that set between two ' 

```
declare
    obj pljson := pljson();
begin

    obj.put('number', 12);
    obj.put('number2', '12');
  
    DBMS_OUTPUT.PUT_LINE('number: '||obj.get_number('number')||', number2: '||obj.get_number('number2'));
end;
```

result ==> ``` number: 12, number2: ```

expectedresult: ``` number: 12, number2: 12 ```

**Comment by jsumners** [comment]
You set a string, not a number, in your second `obj.put`.

**Comment by SELLAM** [comment]
yes, but sometime we have a json like that:
```
{
   "num": "12"
}
```

in fact the column is the number

**Comment by jsumners** [comment]
https://www.rfc-editor.org/rfc/rfc8259#section-7

It's a string. Use `get_string`.
