### ISSUE TITLE
Performance issue converting CLOB to PLJSON in Oracle

### ISSUE THREAD

**Issue by lagerlofm** [pljson/pljson#272]
Hi,
Just started to use this nice feature. However, we will receive rather large input, and parsing works well, except for the conversion from a clob input to PLJSON. Below there is a runnable example, the test gives that 28sec is used for the CLOB to PLJSON conversion. My example is for 10 row, but we have customers with +100 rows. As the CLOB is sent from a UI and should update/insert into the database and result should be returned to the UI. We are currently running a Oracle 11g DB for development, but if this issue could be solved, it would be interesting to compare it to Oracle native JSON functionality in more resent releases of Oracle DB.

You find example below:
Regards,
Michael

declare 
v_value clob := '                                                                                  
  {
    DOCUMENT_TYPE: ''idac_ap_invoice'',
    DOCUMENT_ID: ''DF1E34F42BC822B9E053680A10AC1516'',
    LINE_ID: ''42647'',
    LINK_MOA_ID: ''42643'',
    PROCESS: ''AP_INVOICE'',
    PROCESS_ID: ''962'',
    PROCESS_ACTION: ''FIRST_APPROVAL'',
    SELECTED: ''N'',
    DISABLED: ''NNY'',
    STATUS: ''N'',
    ORIGINAL_LINE_ID: "xxnulxxl",
    PARENT_ID: "xxnulxxl",
    CREATED_BY: ''ANONYMOUS'',
    UPDATED_BY: ''ANONYMOUS'',
    ENABLED_FLAG: ''Y'',
    PARENT_GUID: "xxnulxxl",
    GUID: "xxnulxxl",
    IMPORT_STATUS: "xxnulxxl",
    COL001: ''1.1'',
    COL002: ''ITEM'',
    COL003: ''ACCT'',
    COL004: "xxnulxxl",
    COL005: "xxnulxxl",
    COL006: "xxnulxxl",
    COL007: "xxnulxxl",
    COL008: "xxnulxxl",
    COL009: "xxnulxxl",
    COL010: "xxnulxxl",
    COL011: "xxnulxxl",
    COL012: "xxnulxxl",
    COL013: "xxnulxxl",
    COL014: "xxnulxxl",
    COL015: "xxnulxxl",
    COL016: "xxnulxxl",
    COL017: "xxnulxxl",
    COL018: "xxnulxxl",
    COL019: "xxnulxxl",
    COL020: "xxnulxxl",
    COL021: ''LAGERLOFM'',
    COL022: "xxnulxxl",
    COL023: '' '',
    COL024: "xxnulxxl",
    COL025: "xxnulxxl",
    COL026: "xxnulxxl",
    COL027: "xxnulxxl",
    COL028: "xxnulxxl",
    COL029: "xxnulxxl",
    COL030: "xxnulxxl",
    COL031: ''DF1E34F42BCA22B9E053680A10AC1516'',
    COL032: ''DF1E34F42BC922B9E053680A10AC1516'',
    COL033: ''EA1E7A144D7D59EBE053680A10AC1E87'',
    COL034: ''DF1E34F42BC922B9E053680A10AC1516'',
    COL035: ''DF1E34F42BC822B9E053680A10AC1516'',
    COL036: ''6926442'',
    COL037: ''1'',
    COL038: ''ANONYMOUS'',
    COL039: ''ANONYMOUS'',
    COL040: ''6926442'',
    COL041: ''1'',
    COL042: ''Y'',
    COL043: ''ACTIVE'',
    COL044: ''ACTIVE'',
    COL045: "xxnulxxl",
    COL046: "xxnulxxl",
    COL047: "xxnulxxl",
    COL048: "xxnulxxl",
    COL049: "xxnulxxl",
    COL050: "xxnulxxl",
    COL051: "xxnulxxl",
    COL052: "xxnulxxl",
    COL053: "xxnulxxl",
    COL054: "xxnulxxl",
    COL055: "xxnulxxl",
    COL056: "xxnulxxl",
    COL057: "xxnulxxl",
    COL058: "xxnulxxl",
    COL059: "xxnulxxl",
    COL060: "xxnulxxl",
    CUST_COL001: "xxnulxxl",
    CUST_COL002: "xxnulxxl",
    CUST_COL003: "xxnulxxl",
    CUST_COL004: "xxnulxxl",
    CUST_COL005: "xxnulxxl",
    CUST_COL006: "xxnulxxl",
    CUST_COL007: "xxnulxxl",
    CUST_COL008: "xxnulxxl",
    CUST_COL009: "xxnulxxl",
    CUST_COL010: "xxnulxxl",
    CUST_COL011: "xxnulxxl",
    CUST_COL012: "xxnulxxl",
    CUST_COL013: "xxnulxxl",
    CUST_COL014: "xxnulxxl",
    CUST_COL015: "xxnulxxl",
    CUST_COL016: "xxnulxxl",
    CUST_COL017: "xxnulxxl",
    CUST_COL018: "xxnulxxl",
    CUST_COL019: "xxnulxxl",
    CUST_COL020: "xxnulxxl",
    ROW_NUM: "xxnulxxl",
    NUM001: 1000000,
    NUM002: 1000000,
    NUM003: "xxnulxxl",
    NUM004: 1,
    NUM005: "xxnulxxl",
    NUM006: 1,
    NUM007: "xxnulxxl",
    NUM008: "xxnulxxl",
    NUM009: "xxnulxxl",
    NUM010: "xxnulxxl",
    NUM011: "xxnulxxl",
    NUM012: "xxnulxxl",
    NUM013: "xxnulxxl",
    NUM014: "xxnulxxl",
    NUM015: "xxnulxxl",
    NUM016: "xxnulxxl",
    NUM017: "xxnulxxl",
    NUM018: "xxnulxxl",
    NUM019: "xxnulxxl",
    NUM020: "xxnulxxl",
    CUST_NUM001: "xxnulxxl",
    CUST_NUM002: "xxnulxxl",
    CUST_NUM003: "xxnulxxl",
    CUST_NUM004: "xxnulxxl",
    CUST_NUM005: "xxnulxxl",
    CUST_NUM006: "xxnulxxl",
    CUST_NUM007: "xxnulxxl",
    CUST_NUM008: "xxnulxxl",
    CUST_NUM009: "xxnulxxl",
    CUST_NUM010: "xxnulxxl",
    CREATION_DATE: ''2022-05-16T00:00:00.000Z'',
    UPDATE_DATE: ''2022-06-21T13:16:13.000Z'',
    START_DATE: "xxnulxxl",
    END_DATE: "xxnulxxl",
    DAT001: "xxnulxxl",
    DAT002: "xxnulxxl",
    DAT003: ''2022-10-04T00:00:00.000Z'',
    DAT004: ''2022-05-16T00:00:00.000Z'',
    DAT005: ''2022-05-16T00:00:00.000Z'',
    DAT006: "xxnulxxl",
    DAT007: "xxnulxxl",
    DAT008: "xxnulxxl",
    DAT009: "xxnulxxl",
    DAT010: "xxnulxxl",
    CUST_DAT001: "xxnulxxl",
    CUST_DAT002: "xxnulxxl",
    CUST_DAT003: "xxnulxxl",
    CUST_DAT004: "xxnulxxl",
    CUST_DAT005: "xxnulxxl",
    CUST_DAT006: "xxnulxxl",
    CUST_DAT007: "xxnulxxl",
    CUST_DAT008: "xxnulxxl",
    CUST_DAT009: "xxnulxxl",
    CUST_DAT010: "xxnulxxl",
    ACCOUNT01: ''02'',
    ACCOUNT02: ''5220'',
    ACCOUNT03: ''120'',
    ACCOUNT04: ''00000'',
    ACCOUNT05: ''000'',
    ACCOUNT06: ''000'',
    ACCOUNT07: ''000'',
    ACCOUNT08: "xxnulxxl",
    ACCOUNT09: "xxnulxxl",
    ACCOUNT10: "xxnulxxl",
    ACCOUNT11: "xxnulxxl",
    ACCOUNT12: "xxnulxxl",
    ACCOUNT13: "xxnulxxl",
    ACCOUNT14: "xxnulxxl",
    ACCOUNT15: "xxnulxxl",
    ACCOUNT16: "xxnulxxl",
    ACCOUNT17: "xxnulxxl",
    ACCOUNT18: "xxnulxxl",
    ACCOUNT19: "xxnulxxl",
    ACCOUNT20: "xxnulxxl",
    ACCOUNT21: "xxnulxxl",
    ACCOUNT22: "xxnulxxl",
    ACCOUNT23: "xxnulxxl",
    ACCOUNT24: "xxnulxxl",
    ACCOUNT25: "xxnulxxl",
    ACCOUNT26: "xxnulxxl",
    ACCOUNT27: "xxnulxxl",
    ACCOUNT28: "xxnulxxl",
    ACCOUNT29: "xxnulxxl",
    ACCOUNT30: "xxnulxxl",
    ACCOUNT_DESCR01: "xxnulxxl",
    ACCOUNT_DESCR02: "xxnulxxl",
    ACCOUNT_DESCR03: "xxnulxxl",
    ACCOUNT_DESCR04: "xxnulxxl",
    ACCOUNT_DESCR05: "xxnulxxl",
    ACCOUNT_DESCR06: "xxnulxxl",
    ACCOUNT_DESCR07: "xxnulxxl",
    ACCOUNT_DESCR08: "xxnulxxl",
    ACCOUNT_DESCR09: "xxnulxxl",
    ACCOUNT_DESCR10: "xxnulxxl",
    ACCOUNT_DESCR11: "xxnulxxl",
    ACCOUNT_DESCR12: "xxnulxxl",
    ACCOUNT_DESCR13: "xxnulxxl",
    ACCOUNT_DESCR14: "xxnulxxl",
    ACCOUNT_DESCR15: "xxnulxxl",
    ACCOUNT_DESCR16: "xxnulxxl",
    ACCOUNT_DESCR17: "xxnulxxl",
    ACCOUNT_DESCR18: "xxnulxxl",
    ACCOUNT_DESCR19: "xxnulxxl",
    ACCOUNT_DESCR20: "xxnulxxl",
    ACCOUNT_DESCR21: "xxnulxxl",
    ACCOUNT_DESCR22: "xxnulxxl",
    ACCOUNT_DESCR23: "xxnulxxl",
    ACCOUNT_DESCR24: "xxnulxxl",
    ACCOUNT_DESCR25: "xxnulxxl",
    ACCOUNT_DESCR26: "xxnulxxl",
    ACCOUNT_DESCR27: "xxnulxxl",
    ACCOUNT_DESCR28: "xxnulxxl",
    ACCOUNT_DESCR29: "xxnulxxl",
    ACCOUNT_DESCR30: "xxnullxx"
  }';
v_chr Varchar2(100);
v_json        pljson; -- := json(v_value);
v_json_list   pljson_list;
v_json_record pljson;
begin
dbms_output.put_line('Start creating data ' || to_char(systimestamp, 'HH24:MI:SSxFF'));
For i In 1..10 Loop
  v_value := v_value || ', ' || v_value;
  End Loop;
v_value := '{"datafromcloud": [ ' || v_value ||'
]}';
dbms_output.put_line('Start creating JSON ' || to_char(systimestamp, 'HH24:MI:SSxFF'));
v_json := pljson(v_value);
dbms_output.put_line('Start create JSON LIST ' || to_char(systimestamp, 'HH24:MI:SSxFF'));
v_json_list :=  pljson_list(v_json.get('datafromcloud'));
for i in 1..v_json_list.count Loop 
dbms_output.put_line('GET LINE ' || to_char(systimestamp, 'HH24:MI:SSxFF'));
   v_json_record := pljson(v_json_list.get(i));
dbms_output.put_line('GET_VALUES ' || to_char(systimestamp, 'HH24:MI:SSxFF'));   
   v_chr := v_json_record.get('DOCUMENT_TYPE').get_string();
   v_chr := v_json_record.get('COL001').get_string();
   v_chr := v_json_record.get('COL002').get_string();
   v_chr := v_json_record.get('COL003').get_string();
   v_chr := v_json_record.get('COL004').get_string();
   v_chr := v_json_record.get('COL005').get_string();
   v_chr := v_json_record.get('COL006').get_string();
   v_chr := v_json_record.get('COL007').get_string();
   v_chr := v_json_record.get('COL008').get_string();
   v_chr := v_json_record.get('COL009').get_string();
   v_chr := v_json_record.get('COL010').get_string();
   v_chr := v_json_record.get('COL011').get_string();
   v_chr := v_json_record.get('COL012').get_string();
   v_chr := v_json_record.get('COL013').get_string();
   v_chr := v_json_record.get('COL014').get_string();
   v_chr := v_json_record.get('COL015').get_string();
   v_chr := v_json_record.get('COL016').get_string();
   v_chr := v_json_record.get('COL017').get_string();
   v_chr := v_json_record.get('COL018').get_string();
   v_chr := v_json_record.get('COL019').get_string();
   v_chr := v_json_record.get('COL020').get_string();
   v_chr := v_json_record.get('COL021').get_string();
   v_chr := v_json_record.get('COL022').get_string();
   v_chr := v_json_record.get('COL023').get_string();
   v_chr := v_json_record.get('COL024').get_string();
   v_chr := v_json_record.get('COL025').get_string();
   v_chr := v_json_record.get('COL026').get_string();
   v_chr := v_json_record.get('COL027').get_string();
   v_chr := v_json_record.get('COL028').get_string();
   v_chr := v_json_record.get('COL029').get_string();
   v_chr := v_json_record.get('COL030').get_string();   
  End Loop;
dbms_output.put_line('END JSON PARSING ' || to_char(systimestamp, 'HH24:MI:SSxFF'));  
End;

**Comment by dsnz** [comment]
hi,
right as some speed enhancements for clob processing are in development right now,
in about a few weeks to a month there will be an update 😃 (only for v3 in branch develop_v3)

in the meantime, I must remind in case you have not searched the issues that|
there is an Oracle bug which severely slows clob processing if your db characterset is AL32UTF8
and which Oracle has not fixed and for which we can do nothing as a workaround 😞

**Comment by lagerlofm** [comment]
Hi,
and thanks for your prompt reply!
 
Right, we have UTF8, but as our data in the CLOB is rather basic, so if I would parse the CLOB myself to get each "record" and add the "record" to the PLJSON, do you think that would improve performance?

**Comment by boriborm** [comment]
I have some problem with performance too.
I have 3 test copies of production database. They are on the same server.
ISB, TEST1, TEST2.
ISB is old copy (more than 6 month) and have more older version of pl/json
TEST1 production copy of last day
TEST2 production copy of last some days

I run some HTTP request of json data and then parse this. Size of json data +- 2-3K
Parsing time on ISB is 0,02 second
TEST1 and TEST2 - 5,3-5,7 seconds!
Production database give time 5,3-5,7 too.

I copied PLJSON, PLJSON_LIST, PLJSON_VALUE, PLJSON_PARSER from ISB to TEST1, but that didn't help.

All copies has same charset.

Amazing!

**Comment by boriborm** [comment]
When i run parse on TEST1, TEST2, i see pga_used_mem value of this session. Value up to 700-900MB!
On ISB i can't see for 0,02 sec, but pga_max_mem not more then 20-30-50MB

**Comment by dsnz** [comment]
@lagerlofm 

if you could parse each record separately (if it's a possible scenario in your application)
then of course it would be faster and much much faster if each record fits in a varchar2 variable

**Comment by dsnz** [comment]
@boriborm 

please provide  OS version, db version, character set and pljson version for each of the 3 databases
also provide the json_data to test myself (unless it's the same json you sent in private communication)

**Comment by dsnz** [comment]
@boriborm 

I can't replicate the issue

with test code you gave me, and latest pljson v3, and on my old low-end laptop
parsing is in 0.03 - 0.06 sec (the variability is expected for such low elapsed time)
pga max memory use is 765 KB
the results are the same using varchar2 or clob variable for the json text
(except the minor difference that with clob variable pga max memory is 850 KB)

if you see MB(s) of pga memory used then perhaps your app is running long time and there is memory leak

**Comment by dsnz** [comment]
UPDATE:

upon further testing and private communication with @boriborm 
the real issue is with a small json (about 3 KB) which has an array at the beginning of a nested object
and for which parse time is about 3.5 sec (6 sec for my environment) and pga max memory can reach 900 MB
but when the array is moved to the end of the nested object then parse time is 0.3 sec (0.6 sec for my environment)
and pga max memory is about 60 MB

this happens only with version 2 pljson

even though version 2 pljson is not supported, this will be investigated

**Comment by dsnz** [comment]
after extensive tracing it has been found that the issue is due to
**Oracle bug 29499245** which was first discovered in issue #165 
it just happens that in this case the database does not get to the point of exhausting all memory and getting to error ORA-04030

the huge memory usage when the array is at the beginning is because in that case Oracle starts making earlier complex deep object copies when extending the array of objects inside an object/list and so by the time the end of the json text is reached memory usage gets very high by that time

since there is no workaround and no Oracle bugfix(*) the only resolution is to use PLJSON v3

(*) according to Oracle it is not solved even in later releases (eg. 19)
but they may have not updated the bug status for later releases,
I plan to check sometime what happens with Oracle 19c but in any case the best resolution remains to use PLJSON v3
