### ISSUE TITLE
pljson_dyn.bind_json not works correctly

### ISSUE THREAD

**Issue by boriborm** [pljson/pljson#281]
Hi,

if i have binding param value = null, then `value_of()` in `bind_json` returns 'null' string value

```
declare
 params pljson:=pljson('{param: null}');
 jl pljson_list;
begin
 jl:=pljson_dyn.executeList('select :param as param from dual', params);
 jl.print();
end;
```
Result:
```
[
 { "param":"null"}
]
```
when `bindvar.get(i).is_null()` then we must bind `''` value.
In array values too.

**Comment by dsnz** [comment]
Hi,

I guess you mean that the result should be

```
[
 { "param": null }
]
```
correct ?

what do you mean by "In array values too." ? please give an example

**Comment by boriborm** [comment]
I mean result should be

```
[
 { "param":""}
]
```
When `plson_dyn.null_as_empty_string` is `false`, then result should be
```
[
 { "param":false}
]
```

It worked so in v2.

In binding array parameter `null` (it is pljson_null) values should be set to `""` too.

```
...
elsif (bind_elem.is_array()) then
        declare
          v_bind dbms_sql.varchar2_table;
          v_arr  pljson_list := pljson_list(bind_elem);
        begin
          for j in 1 .. v_arr.count loop
            v_bind(j) := v_arr.get(j).value_of();
          end loop;
          dbms_sql.bind_array(l_cur, ':'||key_str, v_bind);
        end;
      else
...
```

**Comment by dsnz** [comment]
ok, I got it
but again I think there must be a small correction and please verify it

When ```plson_dyn.null_as_empty_string``` is ```false```, then result should be

[
 { "param": null }
]

(ie. ```null``` instead of ```false```)

**Comment by boriborm** [comment]
Oh, yes. It's my mistake :)

**Comment by dsnz** [comment]
okay, I will do the necessary fixes in the next days
