### ISSUE TITLE
Not compiling when add "list.append(pljson('{"lazy construction": true}'));" to a function.

### ISSUE THREAD

**Issue by cbalmeida** [pljson/pljson#283]
When I try to add the following code (I have copied exactly like shown in the examples), it is no compiling;

```
list := pljson_list(); --fresh list;
list.append(pljson('{"lazy construction": true}'));
```

I get PLS-00306: wrong number or types of arguments in call to 'APPEND'

**Comment by dsnz** [comment]
Hi,

I just tried the piece of code you posted and it works fine for me, no errors at all.
Perhaps you should check your pljson installation ?
Also, how have you declared variable 'list' ?

**Comment by cbalmeida** [comment]
I have re-run @install.sql at sqlplus and after that the error has disapeared. Probably something went wrong the first time I installed it few weeks ago and now it seems to be working. Thank you very much for your response and for all the work up you've put to make this package.
