### ISSUE TITLE
error in installation in oracle 10g

### ISSUE THREAD

**Issue by mudhaffer1** [pljson/pljson#288]
Dears,
Thank you for your efforts.
The error as the following.

Error(1,13): PLS-00103: Encountered the symbol "FORCE" when expecting one of the following: ; is authid as compress compiled wrapped under The symbol "authid" was substituted for "FORCE" to continue.

**Comment by mudhaffer1** [comment]
VERSION 10.2.0.3.0

**Comment by dsnz** [comment]
Hi,

I tested on 11 and it works, and it should work on 10 or any Oracle version.
Where/How did you get the PLJSON source code ? Did you run from sqlplus ? The error you got was for which sql file ? (or alternatively post here the entire installation script output)

**Comment by mudhaffer1** [comment]
hi
Where/How did you get the PLJSON source code ? from here in github from your profile.
Did you run from sqlplus ? yes



attached script putput


SQL> @install.sql
-- Setting optimize level - 

Session altered.

-----------------------------------
-- Compiling objects for PL/JSON --
-----------------------------------

PL/SQL procedure successfully completed.

No errors.

Type created.


Type created.


Warning: Type created with compilation errors.

Errors for TYPE PLJSON_ELEMENT:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/21     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type created with compilation errors.


Type created.


Type created.


Warning: Type created with compilation errors.

Errors for TYPE PLJSON_LIST:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/18     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Type created.


Warning: Type created with compilation errors.

Errors for TYPE PLJSON:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/13     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type created with compilation errors.

Errors for TYPE PLJSON_STRING:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/20     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_STRING:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_STRING' without its          
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_STRING is invalid                      

Warning: Type created with compilation errors.

Errors for TYPE PLJSON_NUMBER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/20     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_NUMBER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_NUMBER' without its          
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_NUMBER is invalid                      

Warning: Type created with compilation errors.

Errors for TYPE PLJSON_BOOL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/18     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_BOOL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_BOOL' without its            
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_BOOL is invalid                        

Warning: Type created with compilation errors.

Errors for TYPE PLJSON_NULL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
1/18     PLS-00103: Encountered the symbol "FORCE" when expecting one of        
         the following:                                                         
         ; is authid as compress compiled wrapped under                         
         The symbol "authid" was substituted for "FORCE" to continue.           
                                                                                

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_NULL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_NULL' without its            
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_NULL is invalid                        

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_EXT:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
26/3     PL/SQL: Declaration ignored                                            
26/72    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
29/3     PL/SQL: Declaration ignored                                            
29/33    PLS-00905: object PRESTO.PLJSON is invalid                             
30/3     PL/SQL: Declaration ignored                                            
30/27    PLS-00905: object PRESTO.PLJSON is invalid                             
31/3     PL/SQL: Declaration ignored                                            
31/27    PLS-00905: object PRESTO.PLJSON is invalid                             
32/3     PL/SQL: Declaration ignored                                            
32/27    PLS-00905: object PRESTO.PLJSON is invalid                             
33/3     PL/SQL: Declaration ignored                                            

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
33/25    PLS-00905: object PRESTO.PLJSON is invalid                             
34/3     PL/SQL: Declaration ignored                                            
34/30    PLS-00905: object PRESTO.PLJSON is invalid                             
35/3     PL/SQL: Declaration ignored                                            
35/25    PLS-00905: object PRESTO.PLJSON is invalid                             
36/3     PL/SQL: Declaration ignored                                            
36/25    PLS-00905: object PRESTO.PLJSON is invalid                             
39/3     PL/SQL: Declaration ignored                                            
39/42    PLS-00905: object PRESTO.PLJSON is invalid                             

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_PARSER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
50/3     PL/SQL: Declaration ignored                                            
50/76    PLS-00905: object PRESTO.PLJSON is invalid                             
64/3     PL/SQL: Declaration ignored                                            
64/40    PLS-00905: object PRESTO.PLJSON is invalid                             
65/3     PL/SQL: Declaration ignored                                            
65/44    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
66/3     PL/SQL: Declaration ignored                                            
66/43    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
67/3     PL/SQL: Declaration ignored                                            
67/36    PLS-00905: object PRESTO.PLJSON is invalid                             
68/3     PL/SQL: Declaration ignored                                            

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
68/40    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
69/3     PL/SQL: Declaration ignored                                            
69/39    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
70/3     PL/SQL: Declaration ignored                                            
70/49    PLS-00905: object PRESTO.PLJSON is invalid                             

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_PARSER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_PARSER' without its          
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_PARSER is invalid                      

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_PRINTER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
28/3     PL/SQL: Declaration ignored                                            
28/29    PLS-00905: object PRESTO.PLJSON is invalid                             
29/3     PL/SQL: Declaration ignored                                            
29/34    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
30/3     PL/SQL: Declaration ignored                                            
30/39    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
31/3     PL/SQL: Declaration ignored                                            
31/30    PLS-00905: object PRESTO.PLJSON is invalid                             
32/3     PL/SQL: Declaration ignored                                            
32/35    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
33/3     PL/SQL: Declaration ignored                                            

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
33/40    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_PRINTER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_PRINTER' without its         
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_PRINTER is invalid                     

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_EXT:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_EXT' without its             
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_EXT is invalid                         

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_ELEMENT:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_ELEMENT' without its         
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_LIST:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_LIST' without its            
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_LIST is invalid                        

Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON' without its                 
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON is invalid                             
------------------------------------------
-- Adding optional packages for PL/JSON --
------------------------------------------

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_DYN:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
31/3     PL/SQL: Declaration ignored                                            
31/47    PLS-00905: object PRESTO.PLJSON is invalid                             
37/3     PL/SQL: Declaration ignored                                            
37/49    PLS-00905: object PRESTO.PLJSON is invalid                             

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_DYN:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_DYN' without its             
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_DYN is invalid                         

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_ML:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
29/3     PL/SQL: Declaration ignored                                            
29/44    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
30/3     PL/SQL: Declaration ignored                                            
30/51    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_ML:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_ML' without its              
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_ML is invalid                          

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_XML:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
35/3     PL/SQL: Declaration ignored                                            
35/28    PLS-00905: object PRESTO.PLJSON is invalid                             

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_XML:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_XML' without its             
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_XML is invalid                         

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_UTIL_PKG:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
19/3     PL/SQL: Declaration ignored                                            
21/70    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
24/3     PL/SQL: Declaration ignored                                            
26/63    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_UTIL_PKG:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_UTIL_PKG' without its        
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_UTIL_PKG is invalid                    

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_HELPER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
17/3     PL/SQL: Declaration ignored                                            
17/27    PLS-00905: object PRESTO.PLJSON is invalid                             
21/3     PL/SQL: Declaration ignored                                            
21/26    PLS-00905: object PRESTO.PLJSON_LIST is invalid                        
25/3     PL/SQL: Declaration ignored                                            
25/24    PLS-00905: object PRESTO.PLJSON is invalid                             
29/3     PL/SQL: Declaration ignored                                            
29/26    PLS-00905: object PRESTO.PLJSON is invalid                             
32/3     PL/SQL: Declaration ignored                                            
32/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
33/3     PL/SQL: Declaration ignored                                            

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
33/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
34/3     PL/SQL: Declaration ignored                                            
34/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
35/3     PL/SQL: Declaration ignored                                            
35/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
37/3     PL/SQL: Declaration ignored                                            
37/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
38/3     PL/SQL: Declaration ignored                                            
38/24    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_HELPER:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_HELPER' without its          
         specification                                                          
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_HELPER is invalid                      

Warning: Package created with compilation errors.

Errors for PACKAGE PLJSON_OBJECT_CACHE:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
8/3      PL/SQL: Declaration ignored                                            
8/39     PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
26/3     PL/SQL: Declaration ignored                                            
26/28    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
27/3     PL/SQL: Declaration ignored                                            
27/37    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     
28/3     PL/SQL: Declaration ignored                                            
28/35    PLS-00905: object PRESTO.PLJSON_ELEMENT is invalid                     

Warning: Package Body created with compilation errors.

Errors for PACKAGE BODY PLJSON_OBJECT_CACHE:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/14     PLS-00304: cannot compile body of 'PLJSON_OBJECT_CACHE' without        
         its specification                                                      
                                                                                
1/14     PLS-00905: object PRESTO.PLJSON_OBJECT_CACHE is invalid                

Type created.


Type created.


Type created.


Warning: Type created with compilation errors.

Errors for TYPE PLJSON_TABLE_IMPL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
112/12   PLS-00905: object PRESTO.PLJSON is invalid                             

Synonym created.


Warning: Type Body created with compilation errors.

Errors for TYPE BODY PLJSON_TABLE_IMPL:

LINE/COL ERROR                                                                  
-------- -----------------------------------------------------------------      
0/0      PL/SQL: Compilation unit analysis terminated                           
1/11     PLS-00304: cannot compile body of 'PLJSON_TABLE_IMPL' without its      
         specification                                                          
                                                                                
1/11     PLS-00905: object PRESTO.PLJSON_TABLE_IMPL is invalid                  

Table dropped.


Table created.


Package created.


Package body created.

SQL> SPOOL OFF

**Comment by dsnz** [comment]
Hi,

the whole output is not normal
but I think I sense a pattern.. it seems the statements inside the sql files are executed twice (!) and the second time there is a syntax error

so.. first thing to do is

1. are you on Windows or Linux ?
2. if you are on Linux, then use **dos2unix** to convert all files to unix line endings (just LF instead of CR-LF)
and try again the installation
else (if on Windows), then post here the **install.sql** file that you run (but as a file attachment, not a copy-paste)

**Comment by mudhaffer1** [comment]
Hi sir,
Its windows,
[install.txt](https://github.com/pljson/pljson/files/10529162/install.txt)
sorry i change it to txt because the sit not uploading sql

**Comment by dsnz** [comment]
Hi,

Unfortunately I could not find anything and I am very puzzled with this and worse .. it's so difficult to diagnose your issue without access on the real system.

I will ask you one last thing before giving up.

On sqlplus and just after you login as the user where PLJSON will be installed, do the following

```
SQL> set echo on
SQL> spool install.txt
SQL> @install.sql
... many lines of output ..
SQL> spool off
SQL> exit
```

and then post again the new **install.txt** file

so I can examine the full installation trace

**Comment by mudhaffer1** [comment]
Thank you for your kind patient and support
kindly find the attached the log file

[install.txt](https://github.com/pljson/pljson/files/10544413/install.txt)

**Comment by mudhaffer1** [comment]
If you want to access on the real system let us arrange appointment and will connect with anydesk

**Comment by dsnz** [comment]
ah it's so simple and so easily overlooked

well it's all due to your Oracle version 10

as the years passed we have not done development on Oracle 10 and so we became accustomed to the use
of "FORCE" in the create type statement
but "FORCE" was introduced in 11g

so let's first try to make PLJSON to be Oracle 10 compatible
and from your experience I will modify the installation scripts

so.. wherever you see "FORCE" in an installation file, just remove it
FORCE was needed against circular references, but I think it's not necessary anymore with the code improvements of the last years

finally run install.sql and tell us what happens

**Comment by mudhaffer1** [comment]
Thank you very much... remove force solve the problem.

**Comment by dsnz** [comment]
great
I will leave this issue a few more days open in case anything new related to Oracle 10 arises
