### ISSUE TITLE
Oracle 10g Error PLS-00302: component 'DESC_TAB3' must be declared

### ISSUE THREAD

**Issue by SuAder** [pljson/pljson#293]
Dears,
Thank you for your efforts.
The error as the following.
Oracle 10g

Package Body PLJSON_DYN 已編譯

LINE/COL  ERROR
--------- -------------------------------------------------------------
53/12     PL/SQL: Item ignored
53/21     PLS-00302: component 'DESC_TAB3' must be declared
75/5      PL/SQL: Statement ignored
75/46     PLS-00320: the declaration of the type of this expression is incomplete or malformed
77/7      PL/SQL: Statement ignored
77/19     PLS-00320: the declaration of the type of this expression is incomplete or malformed
79/7      PL/SQL: Statement ignored
88/33     PLS-00320: the declaration of the type of this expression is incomplete or malformed
107/9     PL/SQL: Statement ignored
109/14    PLS-00320: the declaration of the type of this expression is incomplete or malformed
錯誤: 查看編譯器日誌

**Comment by dsnz** [comment]
Hi,

many years ago in order to enhance the capability of **pljson_dyn** package (admittedly for rather obscure cases)
we broke compatibility with Oracle 10g

if you just installed pljson and you don't need to use pljson_dyn then ignore this error
if you intend to use pljson_dyn then tell me so that I give you instructions for a few changes in source code that will make the package able to work with Oracle 10g

**Comment by SuAder** [comment]
Thank you so much for the response!
I want to convert the result of "Select * From Table" to JSON.
Is there any other method I can use?
Thank you!!!

I see the following example:
-- create json objects and lists from sql statements
  list := pljson_dyn.executeList('select * from tab');
  list.print;
  obj := pljson_dyn.executeObject('select * from tab');
  obj.print;

**Comment by dsnz** [comment]
Hi,

in file **src/addons/pljson_dyn.package.sql** do the following changes

1. change any **desc_tab3** to **desc_tab**
2. comment out lines **188 to 192**
3. comment out lines **272 to 282**
4. comment out lines **341 to 345**
5. comment out lines **442 to 452**

finally run the file and the package **pljson_dyn** should compile ok 
and you can run the examples you posted

**Comment by SuAder** [comment]
The other error show up
Thank you so much for your help!


Package Body PLJSON_DYN 已編譯

LINE/COL  ERROR
--------- -------------------------------------------------------------
75/5      PL/SQL: Statement ignored
75/14     PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7      PL/SQL: Statement ignored
88/43     PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9     PL/SQL: Statement ignored
148/53    PLS-00302: component 'COL_TYPE_NAME' must be declared
錯誤: 查看編譯器日誌

PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package PLJSON_ML 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package Body PLJSON_ML 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package PLJSON_XML 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package Body PLJSON_XML 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package PLJSON_UTIL_PKG 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package Body PLJSON_UTIL_PKG 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package PLJSON_HELPER 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package Body PLJSON_HELPER 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Type PLJSON_VTAB 已編譯


Type PLJSON_TABLE_IMPL 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Synonym PLJSON_TABLE 已建立.


Type Body PLJSON_TABLE_IMPL 已編譯


PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
75/5     PL/SQL: Statement ignored
75/14    PLS-00302: component 'DESCRIBE_COLUMNS3' must be declared
79/7     PL/SQL: Statement ignored
88/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
107/9    PL/SQL: Statement ignored
148/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

**Comment by dsnz** [comment]
Hi,

I forgot the following

6. change any **describe_columns3** to **describe_columns**

from the stack trace you sent I can see that you downloaded/cloned from branch master which is pljson v2
you must download/clone from branch **develop_v3** which is **pljson v3**, the version we currently maintain and the version for which my instructions in this and the previous post apply (my instructions do not apply for your version)|

**Comment by SuAder** [comment]
It's work!!!
I am sorry for bothering you so many times
I change to _【pljson-develop_v3】_
And the last error message left
**PLS-00302: component 'COL_TYPE_NAME' must be declared**
I tried to find some useful information, but too fool to get the right way

![image](https://github.com/pljson/pljson/assets/108334004/b9dcf9de-bb27-4180-87e3-df8065ce52ea)


Package PLJSON_DYN 已編譯


Package Body PLJSON_DYN 已編譯

LINE/COL  ERROR
--------- -------------------------------------------------------------
117/7     PL/SQL: Statement ignored
126/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
147/9     PL/SQL: Statement ignored
210/53    PLS-00302: component 'COL_TYPE_NAME' must be declared
270/7     PL/SQL: Statement ignored
279/43    PLS-00302: component 'COL_TYPE_NAME' must be declared
318/9     PL/SQL: Statement ignored
380/53    PLS-00302: component 'COL_TYPE_NAME' must be declared
錯誤: 查看編譯器日誌

PACKAGE BODY SYSTEM.PLJSON_DYN 發生錯誤:

LINE/COL ERROR
-------- -----------------------------------------------------------------
117/7    PL/SQL: Statement ignored
126/43   PLS-00302: component 'COL_TYPE_NAME' must be declared
147/9    PL/SQL: Statement ignored
210/53   PLS-00302: component 'COL_TYPE_NAME' must be declared
270/7    PL/SQL: Statement ignored
279/43   PLS-00302: component 'COL_TYPE_NAME' must be declared
318/9    PL/SQL: Statement ignored
380/53   PLS-00302: component 'COL_TYPE_NAME' must be declared

Package PLJSON_ML 已編譯

**Comment by dsnz** [comment]
Hi,

The line numbers I gave you are for the original file &nbsp; **src/addons/pljson_dyn.package.sql**
and not for the package body

please do exactly as instructed

I repeat the instructions below

1. change any **desc_tab3** to **desc_tab**
2. comment out lines **188 to 192**
3. comment out lines **272 to 282**
4. comment out lines **341 to 345**
5. comment out lines **442 to 452**
6. change any **describe_columns3** to **describe_columns**

**Comment by dsnz** [comment]
furthermore

- we assume you are on **Oracle 10g**
- I noticed that you installed in **system** schema which is wrong, you should install in a **new schema** where you are going to use **pljson** together with your application
- the installation schema should have execute grant for **sys.dbms_sql** package (usually allowed by default but good to check anyway)

**Comment by SuAder** [comment]
I'm sorry...
I was too stupid to see 2~4 need to comment out...
After comment out these lines, it's work.
Thank you so much for helping!!!

There's only one problem left to solve and I'll look for a solution

It seems that Chinese can't be displayed.
{
  "names" : ["ORG_ID", "STK_ID", "NAME", "MODEL"],
  "data" : [["B071", "20050000877", "PET\u900F\u660E\u65E0\u83CC\u74F6\uFF08\u7687\u54C1\u7528\uFF09\u00A0\u00A0\u00A0", "28HR500ML,1881-22.28g"]]
}

**Comment by dsnz** [comment]
Great that it works for you finally.

To display Chinese characters, at the beginning of your code put this

**pljson_printer.ascii_output := false;**

(see also issue #269)
