### ISSUE TITLE
ORA-22922: nonexistent LOB value

### ISSUE THREAD

**Issue by akmangukiya** [pljson/pljson#294]
Hello Team,

I'm creating JSON using the JSON_OBJECT and JSON_ARRAYAGG from the one table.
That table contains  different types of column like NUMBER, VARCHAR2, RAW, CLOB and TIMESTAMP.

I have written one procedure and that procedure will return the JSON of that table data. Please find below source code for your reference.

`    PROCEDURE get_global_change_log (
        p_from_datetime       IN    VARCHAR2,
        p_to_datetime         IN    VARCHAR2,
        p_changeLogDTO      OUT   CLOB
    )
    IS
        l_changeLogDTO CLOB;
    BEGIN
        dbms_output.put_line('1.....');
        
        SELECT
            JSON_OBJECT (             
                KEY 'GlobalChangeLogData' VALUE JSON_ARRAYAGG(JSON_OBJECT(
                KEY 'globalChangeLogId' VALUE GLOBAL_CHANGE_LOG_ID,
                KEY 'jusGUID' VALUE JUS_GUID,
                KEY 'tranType' VALUE TRANTYPE,
                KEY 'operation' VALUE OPERATION,
                KEY 'message' VALUE json_serialize(MESSAGE),
                KEY 'description' VALUE DESCRIPTION,
                KEY 'ori' VALUE ORI,
                KEY 'createdById' VALUE CREATED_BY_ID,
                KEY 'createdByEmail' VALUE CREATED_BY_EMAIL,
                KEY 'createdDate' VALUE CREATED_DATE,
                KEY 'status' VALUE STATUS,
                KEY 'statusTS' VALUE STATUS_TS,
                KEY 'transaction' VALUE TRANSACTION
                RETURNING CLOB)
                RETURNING CLOB) 
            RETURNING CLOB) 
        INTO l_changeLogDTO
        FROM  global_change_log 
        where 
            1=1
            AND ROWNUM = 1
            AND MESSAGE IS NOT NULL;
        
        dbms_output.put_line(l_changeLogDTO);
        
        p_changeLogDTO := l_changeLogDTO;
    EXCEPTION
        WHEN OTHERS THEN
            exception_pkg.writetoeventlog('justis_api_pkg.get_global_change_log exception errorDesc: ' || substr(sqlerrm, 1, 200), 'ERROR');
            dbms_output.put_line(sqlerrm);
    END get_global_change_log;`

Whatever SELECT statement I have used in procedure which I'm running standalone then it's working fine anf getting restult as expected but while runing above procedure that time getting "**ORA-22922: nonexistent LOB value**" error.

Team your response will be helpful me to complete my task.

Thank you in adavnce!!

Regards,
Ashish

**Comment by dsnz** [comment]
Hello,

your request has nothing to do with our project and we can't help

you should try on stackoverflow, with Google search or creating a SR at Oracle's https://support.oracle.com/
