### ISSUE TITLE
How to find pljson 2.5.5 is compatible with Oracle DB version 11.2.0.4

### ISSUE THREAD

**Issue by UK503** [pljson/pljson#295]
Hi,
I want to install pljson version 2.5.5 in our oracle db 11.2.0.4
Can I get to know is it compatible.
Any help would be appreciated.
Thanks is advance :)

**Comment by dsnz** [comment]
PLJSON 2.5.5  does work  with Oracle 11.2.0.4

**Comment by UK503** [comment]
Many thanks for the confirmation.
It would be nice if that is mentioned somewhere so that it helps in future.
