### ISSUE TITLE
json_dyn.executeList escaping content of column which is already JSON

### ISSUE THREAD

**Issue by Kodlik** [pljson/pljson#296]
Hello,
I use json_dyn.executeList to generate JSON from a SQL SELECT. The select list includes a varchar2-column which is already in JSON format. The JSON in this column is being escaped, e.g., quotation marks. 
Is there a way how to instruct json_dyn.executeList that the content of some column should not be escaped, because it is already in JSON format? Something like the convention used by ORDS, where aliasing the column instructs the ORDS to treat the column as JSON : "SELECT id, jsons "{}jsons" FROM table_with_json"? (https://www.thatjeffsmith.com/archive/2017/09/ords-returning-raw-json/)
Thanks

**Comment by dsnz** [comment]
Hi,

please post a short piece of self-contained code (the shortest possible),
along with the output you get and the output you would like to see

**Comment by Kodlik** [comment]
Hi,
in the attachment you will find a test case with comments.
Thank you
[PLJSON_DYN-EXECUTELIST-nested_json_escaped.sql.txt](https://github.com/pljson/pljson/files/14098119/PLJSON_DYN-EXECUTELIST-nested_json_escaped.sql.txt)

**Comment by dsnz** [comment]
Hi,

I have solution with ORDS-like syntax almost ready,
however it raises some compatibility issues with existing PLJSON code
and I would like to refine it and test it more thoroughly
hopefully I will publish it next week (on Chinese New Year :))

**Comment by FlavioBarbosa-MYP7** [comment]
[heart]         Flavio Barbosa reacted to your message:
________________________________

**Comment by dsnz** [comment]
feature implemented in PR #297 
and in latest release v3.7.0

**Comment by Kodlik** [comment]
Hi,
Thank you, but I've identified an issue with v3.7.0. The json_dyn.executeList does not automatically remove the artificially added prefix "{}" from the element name in the JSON output. 
As per my testcase
```
select PLJSON_DYN.EXECUTELIST(q'(
  select
    vehicles.*
  from (
    select 601 as id, 'MM TECHNOLOGY TEAM' as name, '{"crew": [{"id":1, "name": "MARTIN MACIK"},{"id":2, "name": "FRANTISEK TOMASEK"},{"id":3, "name": "DAVID SVANDA"}]}' as "{}crew_json" from dual 
    union all
    select 602 as id, 'INSTAFOREX LOPRAIS PRAGA' as name, '{"crew": [{"id":4, "name": "ALES LOPRAIS"},{"id":5, "name": "JAROSLAV VALTR JR"},{"id":6, "name": "JIRI STROSS"}]}' as "{}crew_json" from dual
  ) vehicles
)'
).TO_CHAR () as vehicles_json
from dual
/
``` 
the column aliased as "{}crew_json" is outputted as : "{}crew_json", but should be "crew_json".
Thank you

**Comment by dsnz** [comment]
Hi,
this was not immediately apparent, but it's logical
I will update  this in the next days

**Comment by dsnz** [comment]
feature updated in PR #299
and in latest release v3.7.1

**Comment by Kodlik** [comment]
Thank you very much!
