### ISSUE TITLE
Can't extract sub json object

### ISSUE THREAD

**Issue by yanko** [pljson/pljson#36]
Hi there,
Can't convert the Result into a json object so I can further parse it.

```
{
  "$httpStatus" : 200,
  "$descriptor" : "",
  "request" : null,
  "response" : {
    "Result" : "{totalresults: 187, startindex: 1, count: 5, success: True, data: [{\"ContactId\":\"C00610027045\",\"CustomerId\":\"900610027045\",\"FirstName\":\"Alex\",\"LastName\":\"btton\",\"Email\":\"\",\"HomePhone\":\"2506193424\",\"CityStatePostal\":\",  \"},{\"ContactId\":\"C00600091423\",\"CustomerId\":\"900600091423\",\"FirstName\":\"Barbara \",\"LastName\":\"bton\",\"Email\":\"\",\"HomePhone\":\"\",\"CityStatePostal\":\",  \"},{\"ContactId\":\"C00600009119\",\"CustomerId\":\"900600009119\",\"FirstName\":\"Brad\",\"LastName\":\"bton\",\"Email\":\"\",\"HomePhone\":\"6049860822\",\"CityStatePostal\":\"NORTH VANCOUVER, BC V7L4V7\"},{\"ContactId\":\"C6UJ9A004QYQ\",\"CustomerId\":\"63003621\",\"FirstName\":\"Brent\",\"LastName\":\"btton\",\"Email\":\"btton@b.com\",\"HomePhone\":\"\",\"CityStatePostal\":\"West Vancouver, BC V7S2J5\"},{\"ContactId\":\"C00610006434\",\"CustomerId\":\"900610006434\",\"FirstName\":\"Daniel\",\"LastName\":\"bton\",\"Email\":\"daton@thm1.com\",\"HomePhone\":\"6016707\",\"CityStatePostal\":\"VANCOUVER, BC V6K1f4\"}]}"
  }
}


  responseContentJson json;
  results json_value := json_value();
  resultjson json := json();

    responseContentJson := json(l_clob);
    log_output('responseContentJson', p_clob => responseContentJson.to_char);
    
    --dbms_output.put_line();
    --json_ext.get_json_value(responseContentJson, 'response.Result.totalresults').print;
    results := responseContentJson.path('response.Result');
    --results.print;
    DBMS_LOB.freetemporary(l_clob);
    DBMS_LOB.createtemporary(l_clob, FALSE);
    results.to_clob(l_clob);
    
    log_output('results.to_clob(l_clob)', p_clob => l_clob);
    resultjson := json(l_clob);
```
`err:{exception}ORA-20101: JSON Parser exception - no { start found::-20101
as if json('"{}"')` and does not remove the double quotes.

what am I doing wrong?

thank you!

**Comment by jsumners** [comment]
`Result` is a string, not JSON. Since the `"` are escaped, it is invalid and the parser cannot parse it.

**Comment by yanko** [comment]
Thank you so much for fast response, will get them to validate it.
another question. I was able to get what is in data attribute within json_value object and it's type is telling me that it's an array. How would you go about and loop with it?
tempdata := responseContentJson.get('response');
    tempobj := json(tempdata);
    tempobj.get_keys().print;
    temval :=  tempobj.get('Result');
        
    DBMS_LOB.createtemporary(l_clob, FALSE);
    temval.get_string(l_clob);
    obj := json(l_clob);
    DBMS_LOB.freetemporary(l_clob);
    
    obj.get_keys().print;
    tempdata := obj.get('data');
    
    dbms_output.put_line(tempdata);
    
    log_output(tempdata.get_type, p_clob => tempdata.to_char);

tempdata.get_type returns array...

tx.

**Comment by jsumners** [comment]
Just like you would loop over any other pl/sql array.

**Comment by yanko** [comment]
awesome. thank you.

**Comment by yanko** [comment]
One of the last things...
what would be the simplest way to return json_list into a refcursor?
right now I am planing to use custom object...type..table and populate them and return them as cursor... but thought that you may have something in place?

thank you.

**Comment by boriborm** [comment]
Hi, maybe it help?

`FUNCTION get_json_table_from_json_list(jList in json_list) return json_array
as
 l_index PLS_Integer:=1;
 l_tab json_array:=json_array();
begin
 if jList is null then return l_tab; end if;
 for l_index in 1..jList.count loop
    l_tab.EXTEND;
    l_tab(l_tab.COUNT):=json(jList.get(l_index));
 end loop;
 return l_tab;
end;`

json

{
 jlist:[
    {t1:'123',t2:123}
 ]
}
usage

`
select 
js.get('t1').get_string(),
js.get('t2').get_number()
from table(get_json_table_from_json_list(json_ext.get_json_list(<json_object_with_json_list>,  'jlist'))) js`

**Comment by yanko** [comment]
Thank you.
