### ISSUE TITLE
Case Not Found pljson_table_imp

### ISSUE THREAD

**Issue by intermotions** [pljson/pljson#44]
Hello,

I was just using the new pljson_table for some parsing and mapping. However, sometimes, I have missing elements in the json object and the "SELECT" statement fails with case not found.

I suggest, that if the user of the packages know that there are possibly missing elements, then to just added null elements with the name. As per suggestion that output is all VARCHAR as its easier to handle the necessary conversion.

BUG:

ORA-06592: CASE not found while executing CASE statement
ORA-06512: at "PLJSON_TABLE_IMPL", line 100
ORA-06512: at line 1
06592. 00000 -  "CASE not found while executing CASE statement"
*Cause:    A CASE statement must either list all possible cases or have an
           else clause.
*Action:   Add all missing cases or an else clause.

FIX:
        when 6 then -- 'null';
          buf := null; 
          --dbms_output.put_line('res='||buf);
          sctx.data_tab.extend(); sctx.data_tab(sctx.data_tab.LAST) := pljson_varray(buf);
        else
          -- if object doesn't exist add new elements of type null
          buf := null; 
          --dbms_output.put_line('res='||buf);
          sctx.data_tab.extend(); sctx.data_tab(sctx.data_tab.LAST) := pljson_varray(buf);

**Comment by dsnz** [comment]
Hi,

I have verified the issue you found. It's not so a bug but my oversight for this case, especially
when it is common for missing objects to be mapped to null and when Oracle 12c does the same thing.
The appropriate fix will be made available within one day.

Thank you :smile:

**Comment by intermotions** [comment]
Thank you for the prompt update.

JS

**Comment by jsumners** [comment]
This should remain open until the fix is committed.
