### ISSUE TITLE
Installation script not updated for new src directory

### ISSUE THREAD

**Issue by colinphill** [pljson/pljson#5]
The installation script still reads, e.g.,

    @@json_value.typ
    @@json_list.typ

rather than

    @@src/json_value.typ
    @@src/json_list.typ

**Comment by jsumners** [comment]
Thank you for pointing out my oversight. I have committed the fix.

**Comment by colinphill** [comment]
Actually, I'm not sure this was the issue. [Orafaq states](http://www.orafaq.com/wiki/SQL*Plus_FAQ#What_is_the_difference_between_.40_and_.40.40.3F) that relative paths are not supported by the double-at command, and my own difficulties (after fixing it locally) seem to corroborate that.

**Comment by jsumners** [comment]
Then I'll have to investigate it when I'm near an Oracle database I can run it against. It may be some time before that happens. If you have a real fix, please note it here or submit a pull request.

**Comment by shakerlxxv** [comment]
I've used the `@@` with a subdirectory path previously without problem. I think the Orafaq reference might be a bit confusing. 

I was able to run the current `install.sql` and `uninstall.sql` using both *sqlplus* and *SQL Developer*.

**Comment by jsumners** [comment]
@shakerlxxv so you're confirming that I can close this issue?

**Comment by shakerlxxv** [comment]
Yes. That's correct.

**Comment by jsumners** [comment]
Thank you @shakerlxxv .
