### ISSUE TITLE
12c friendly version; rename of packages and types to 'pljson_

### ISSUE THREAD

**Issue by dsnz** [pljson/pljson#51]
this version is already on the develop branch, but not associated with any pull request !
strangely github complained for merge conflicts when pulling the develop branch on my pc and merging  on it had no conflicts !
so I had to do some git magic (with --no-ff and push) and pushed directly to develop branch
hope all is fine now ...

**Comment by jsumners** [comment]
No worries. I fully understand the Git pain. Be glad I'm not one of those people that believe in the "rebase" feature 😄

**Comment by dsnz** [comment]
I should not even need rebase ! It's a problem with github, its is not git 100% ..
I did

```
git fetch pljson      # pljson is remote for pljson repository, not my repository
git checkout -b pljson-develop pljson/develop
git merge develop     # merge with my develop, no conflicts !!!
                      # pull-request should work but it does not !!!
                      # now the following steps update github
git checkout develop
git merge --no-ff pljson-develop
git push pljson develop
```
