### ISSUE TITLE
does pljson support curie namespace or aliases in json 

### ISSUE THREAD

**Issue by gauravbrills** [pljson/pljson#55]
I have the following json where I have curie namespace as per HAL terminology in json .Seems pljson has difficulty parsing the same 

Example

```
{
    "_links": {
        "self": { "href": "/orders" },
        "curies": [{ "name": "ea", "href": "http://example.com/docs/rels/{rel}", "templated": true }],
        "next": { "href": "/orders?page=2" },
        "ea:find": {
            "href": "/orders{?id}",
            "templated": true
        },
        "ea:admin": [{
            "href": "/admins/2",
            "title": "Fred"
        }, {
            "href": "/admins/5",
            "title": "Kate"
        }]
    },
    "currentlyProcessing": 14,
    "shippedToday": 20,
    "_embedded": {
        "ea:order": [{
            "_links": {
                "self": { "href": "/orders/123" },
                "ea:basket": { "href": "/baskets/98712" },
                "ea:customer": { "href": "/customers/7809" }
            },
            "total": 30.00,
            "currency": "USD",
            "status": "shipped"
        }, {
            "_links": {
                "self": { "href": "/orders/124" },
                "ea:basket": { "href": "/baskets/97213" },
                "ea:customer": { "href": "/customers/12369" }
            },
            "total": 20.00,
            "currency": "USD",
            "status": "processing"
        }]
    }
}
```

and do a xpath 
```
snc_app.json_ext.get_json_list(obj, '_embedded.ea:order');

```

This gives me an error JSON path parse error ORA-20110 .aplha-numeric character or space expected at position 12

**Comment by jsumners** [comment]
Looks like it's the regular expression at https://github.com/pljson/pljson/blob/master/src/json_ext.sql#L158
and
https://github.com/pljson/pljson/blob/master/src/json_ext.sql#L164
that is causing the problem.

**Comment by gauravbrills** [comment]
@dsnz thanks that does work :+1:

**Comment by dsnz** [comment]
@gauravbrills   thank you too

@jsumners 
I think this should not be considered a bug, the original jsonpath was of the dot form where supposedly the names are identifiers which in javascript are restricted to alphanumerics plus '_'
if a user wants to access an object named using other characters then the array notation should be used
