### ISSUE TITLE
 ORA-00904 error when using pljson in merge statement

### ISSUE THREAD

**Issue by zero2lin** [pljson/pljson#57]
```sql
-- Create table
create table pljson_test
(
  c1 varchar2(100)
)
;

DECLARE
  jl json;
BEGIN
  jl := json(json_list('[{"a":"1"}]').get(1));
  MERGE INTO pljson_test t1
  USING (SELECT jl.get('a').get_string() a FROM dual) t2      -- error in this line
  ON (1 = 2)
  WHEN NOT MATCHED THEN
    INSERT (c1) VALUES (t2.a);
END;
/
```

This program will throw an ORA-00904 error: "JSON"."GET_STRING": invalid identifier
I don't know whats wrong

**Comment by jsumners** [comment]
The following is working for me:

```sql
DECLARE
  jl pljson;
  out varchar2(255);
BEGIN
  jl := pljson(pljson_list('[{"a":"1"}]').get(1));
  
  SELECT jl.get('a').get_string() a into out FROM dual;
  dbms_output.put_line(out);
END;
/
```

Do you get an error when running this script?

**Comment by zero2lin** [comment]
No.
The error only occurs in merge statement.

**Comment by jsumners** [comment]
I think this has to do with the way merge works. It is expecting a table in the `using` clause -- http://www.dba-oracle.com/oracle_tips_rittman_merge.htm

I would suggest using the `pljson_table_impl` @dsnz created, but it's giving me issues as well -- https://github.com/pljson/pljson/issues/58

**Comment by jsumners** [comment]
@zero2lin, @dsnz posted an example showing how to make the `json_table_impl` feature work in this case in issue #58. Will that solve your issue?

**Comment by zero2lin** [comment]
Thanks.
I have used a temporary variable to solve my problem, like this:
```
SELECT jl.get('a').get_string() into a FROM dual;
MERGE INTO pljson_test t1
  USING (SELECT a FROM dual) t2 
  ON (1 = 2)
  WHEN NOT MATCHED THEN
    INSERT (c1) VALUES (t2.a);
```
It seems like an Oracle bug.

**Comment by dsnz** [comment]
After some experiments I can say that It has to do with the number of dots and name resolution within pl/sql. Somehow it gets confused and considers the dots as separating table_names from columns etc. and does not understand that there are chained object function calls. Even with two dots only there is still problem (with different error message indicating type mismatch). Strangely this happens only in the MERGE statement and not in a single SELECT. I believe this issue will happen with any oracle object in the USING select statement.

The workaround by @zero2lin is the best if it is possible to use in the application. In other circumstances one could use the package PLJSON_EXT like in the modified example below

```
DECLARE
  jl json;
BEGIN
  jl := json(json_list('[{"a":"1"}]').get(1));
  MERGE INTO pljson_test t1
  USING (SELECT pljson_ext.get_string(jl, 'a') a FROM dual) t2      -- error in this line
  ON (1 = 2)
  WHEN NOT MATCHED THEN
    INSERT (c1) VALUES (t2.a);
END;
/
```
