### ISSUE TITLE
Handling of properties including a "." (point) are not supported

### ISSUE THREAD

**Issue by LeonardGC** [pljson/pljson#6]
When you have a json with a property that have a point, the library returns an error : "ora-30625 method dispatch on null self argument is disallowed".

From the samples (modified to show my point):

    set serveroutput on;
    declare
      obj json := json(
    '{
      "_source":{"type":"elasticsearch"},
      "highlight" : {
        "type.ngram" : [ "<Highlight>elasticsearch</Highlight>" ]
      }
    }');

    begin
       
      obj.print;

      declare 
        printme varchar2(400 char) := null;
        temp json_list;
        tempdata json_value;
        tempobj json;
      begin
        if(obj.exist('highlight')) then
          tempdata := obj.get('highlight');
          if(tempdata.is_object) then
            tempobj := json(tempdata);
            if(tempobj.exist('type.ngram')) then
              tempdata := obj.get('type.ngram');
              if(tempdata.is_array) then
                temp := json_list(tempdata);
                tempdata := temp.get(1);
                if(tempdata.is_string) then
                  printme := tempdata.get_string;
                end if;
              else
                printme := '"type.ngram" is not an array';
              end if;
            else
              printme := '"type.ngram" don''t exist';
            end if;
          end if; 
        end if;

        if(printme is not null) then dbms_output.put_line(printme); end if;
      end;

      dbms_output.put_line('---------------------');
      --now the JSON Path way:
      declare 
        printme varchar2(4000 char) := null;
      begin
        printme := json_ext.get_string(obj, 'highlight.type.ngram[1]');
        if(printme is null) then
          dbms_output.put_line('NULL');
        else
          dbms_output.put_line(printme);
        end if;
      end;

    end;
    /

**Comment by jsumners** [comment]
My suspicion is that the call to 'get' is interpreting the attribute as a
JSON Path -- http://pljson.github.io/pljson/ex8.html

In fact, I know it is. I'm not sure how we can avoid this for your use
case.  If you have any suggestions I'd love to see them.

On Tuesday, January 27, 2015, LeonardGC <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> When you have a json with a property that have a point, the library
> returns an error : "ora-30625 method dispatch on null self argument is
> disallowed".
>
> From the samples (modified to show my point):
>
> set serveroutput on;
> declare
>   obj json := json(
> '{
>   "_source":{"type":"elasticsearch"},
>   "highlight" : {
>     "type.ngram" : [ "<Highlight>elasticsearch</Highlight>" ]
>   }
> }');
>
> begin
>
>   obj.print;
>
>   declare
>     printme varchar2(400 char) := null;
>     temp json_list;
>     tempdata json_value;
>     tempobj json;
>   begin
>     if(obj.exist('highlight')) then
>       tempdata := obj.get('highlight');
>       if(tempdata.is_object) then
>         tempobj := json(tempdata);
>         if(tempobj.exist('type.ngram')) then
>           tempdata := obj.get('type.ngram');
>           if(tempdata.is_array) then
>             temp := json_list(tempdata);
>             tempdata := temp.get(1);
>             if(tempdata.is_string) then
>               printme := tempdata.get_string;
>             end if;
>           else
>             printme := '"type.ngram" is not an array';
>           end if;
>         else
>           printme := '"type.ngram" don''t exist';
>         end if;
>       end if;
>     end if;
>
>     if(printme is not null) then dbms_output.put_line(printme); end if;
>   end;
>
>   dbms_output.put_line('---------------------');
>   --now the JSON Path way:
>   declare
>     printme varchar2(4000 char) := null;
>   begin
>     printme := json_ext.get_string(obj, 'highlight.type.ngram[1]');
>     if(printme is null) then
>       dbms_output.put_line('NULL');
>     else
>       dbms_output.put_line(printme);
>     end if;
>   end;
>
> end;
> /
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pljson/pljson/issues/6>.
>


-- 
James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (band page)

**Comment by LeonardGC** [comment]
I was thinking that we could use double quotes to separate them explicitly.

For example:

    printme := json_ext.get_string(obj, 'highlight."type.ngram"[1]');

This way we could handle this situation in all cases. What do you think?
Op 27 jan. 2015 17:52 schreef "James Sumners" <notifications@github.com>:

> My suspicion is that the call to 'get' is interpreting the attribute as a
> JSON Path -- http://pljson.github.io/pljson/ex8.html
>
> In fact, I know it is. I'm not sure how we can avoid this for your use
> case. If you have any suggestions I'd love to see them.
>
> On Tuesday, January 27, 2015, LeonardGC <notifications@github.com

**Comment by jsumners** [comment]
I could live that or backticks. Can you submit a pull request that
implements it?

On Tue, Jan 27, 2015 at 2:15 PM, LeonardGC <notifications@github.com> wrote:

> I was thinking that we could use double quotes to separate them
> explicitly.
>
> For example:
>
> printme := json_ext.get_string(obj, 'highlight."type.ngram"[1]');
>
> This way we could handle this situation in all cases. What do you think?
> Op 27 jan. 2015 17:52 schreef "James Sumners" <notifications@github.com>:
>
> > My suspicion is that the call to 'get' is interpreting the attribute as
> a
> > JSON Path -- http://pljson.github.io/pljson/ex8.html
> >
> > In fact, I know it is. I'm not sure how we can avoid this for your use
> > case. If you have any suggestions I'd love to see them.
> >
> > On Tuesday, January 27, 2015, LeonardGC <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > When you have a json with a property that have a point, the library
> > > returns an error : "ora-30625 method dispatch on null self argument is
> > > disallowed".
> > >
> > > From the samples (modified to show my point):
> > >
> > > set serveroutput on;
> > > declare
> > > obj json := json(
> > > '{
> > > "_source":{"type":"elasticsearch"},
> > > "highlight" : {
> > > "type.ngram" : [ "<Highlight>elasticsearch</Highlight>" ]
> > > }
> > > }');
> > >
> > > begin
> > >
> > > obj.print;
> > >
> > > declare
> > > printme varchar2(400 char) := null;
> > > temp json_list;
> > > tempdata json_value;
> > > tempobj json;
> > > begin
> > > if(obj.exist('highlight')) then
> > > tempdata := obj.get('highlight');
> > > if(tempdata.is_object) then
> > > tempobj := json(tempdata);
> > > if(tempobj.exist('type.ngram')) then
> > > tempdata := obj.get('type.ngram');
> > > if(tempdata.is_array) then
> > > temp := json_list(tempdata);
> > > tempdata := temp.get(1);
> > > if(tempdata.is_string) then
> > > printme := tempdata.get_string;
> > > end if;
> > > else
> > > printme := '"type.ngram" is not an array';
> > > end if;
> > > else
> > > printme := '"type.ngram" don''t exist';
> > > end if;
> > > end if;
> > > end if;
> > >
> > > if(printme is not null) then dbms_output.put_line(printme); end if;
> > > end;
> > >
> > > dbms_output.put_line('---------------------');
> > > --now the JSON Path way:
> > > declare
> > > printme varchar2(4000 char) := null;
> > > begin
> > > printme := json_ext.get_string(obj, 'highlight.type.ngram[1]');
> > > if(printme is null) then
> > > dbms_output.put_line('NULL');
> > > else
> > > dbms_output.put_line(printme);
> > > end if;
> > > end;
> > >
> > > end;
> > > /
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pljson/pljson/issues/6>.
> > >
> >
> >
> > --
> > James Sumners
> > http://james.sumners.info/ (technical profile)
> > http://jrfom.com/ (personal site)
> > http://haplo.bandcamp.com/ (band page)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pljson/pljson/issues/6#issuecomment-71682543>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pljson/pljson/issues/6#issuecomment-71708720>.
>



-- 
James Sumners
http://james.sumners.info/ (technical profile)
http://jrfom.com/ (personal site)
http://haplo.bandcamp.com/ (band page)

**Comment by LeonardGC** [comment]
After some extra searching I have found that this works: (following the javascript way of handling json path)

```
declare
  obj json := json(
'{
  "_source":{"type":"elasticsearch"},
  "highlight" : {
    "type.ngram" : [ "<Highlight>elasticsearch</Highlight>" ]
  }
}');

begin
       
  obj.print;

  --now the JSON Path way:
  declare 
    printme varchar2(4000 char) := null;
  begin
    printme := json_ext.get_string(obj, 'highlight["type.ngram"][1]');
    if(printme is null) then
      dbms_output.put_line('NULL');
    else
      dbms_output.put_line(printme);
    end if;
  end;

end;
```

I was not able to rework it to the old way of doing it. Any ideas?

**Comment by jsumners** [comment]
I'm confused. Are you saying that your code snippet works with PL/JSON as-is, or is it showing a new problem?

**Comment by LeonardGC** [comment]
I'm saying that my latest code snippet works with PL/JSON as-is, but that I couldn't convert it to the more elaborate older way of doing it. Maybe I'm still doing something wrong though.

New way:
First example (didn't work):
````
printme := json_ext.get_string(obj, 'highlight.type.ngram[1]');
````

Second example (works):
````
printme := json_ext.get_string(obj, 'highlight["type.ngram"][1]');
````

Old way:
First example (didn't work):
````
        if(tempobj.exist('type.ngram')) then
          tempdata := obj.get('type.ngram');
````

Second example (didn't work):
````
        if(tempobj.exist('["type.ngram"]')) then
          tempdata := obj.get('["type.ngram"]');
````

I hope I explained it a bit better now.

**Comment by jsumners** [comment]
I think you've found the solution, you just need to re-work your code to use it. JSON Path used to be an extension to PL/JSON, but has long since become an integral requirement. Since your attribute names use dots within the name, you're going to have to use `'highlight["type.ngram"]`. Additionally, unless you assign the result of that path access to a new object, you'll have to specify the full path every time you access it.

I agree that it isn't fun. But when has PL/SQL ever been fun? Or you can upgrade to Oracle 12.1.0.2 (12c) -- http://www.liberidu.com/blog/2013/09/26/oracle-openworld-json-support-in-the-oracle-12c-database-upcoming-new-feature/ -- and use their native JSON support. I have no idea if their implementation is worth a damn.
