### ISSUE TITLE
Parsing exception

### ISSUE THREAD

**Issue by boriborm** [pljson/pljson#63]
When tag name without quots and begin with "true", "false", "null", then parser raise exception

```
declare
    j pljson;
begin
    j:=pljson_parser.parser('{nullable:true}');
end;
```

ORA-20101: JSON Parser exception @ line: 1 column: 2 - Expected string or }

**Comment by jsumners** [comment]
Because a property name must be enclosed by the quote (`"`) character. That is defined in the RFC.

**Comment by boriborm** [comment]
pljson_parser.json_strict is false. I think it must work without quotes :)

Other situation
```
declare
 j pljson;
begin
 pljson_parser.json_strict:=true;
 j:=pljson_parser.parser('{nullable:true}');
 j.print; 
end;
```
Exeption write incorrect error
ORA-20100: JSON Scanner exception @ line: 1 column: 6 - Unexpected char: a
```
declare
 j pljson;
begin
 pljson_parser.json_strict:=true;
 j:=pljson_parser.parser('{nue:true}');
 j.print; 
end;
```

ORA-20100: JSON Scanner exception @ line: 1 column: 2 - Expected: 'null'

It must write about incorrect name of tag...

**Comment by jsumners** [comment]
https://github.com/pljson/pljson/blob/develop/src/pljson_parser.package.sql#L405

**Comment by boriborm** [comment]
I know :)

I'm trying to increase the speed of parsing. I'm write other parse function and optimize old existing functions (next_char, lexName, lexString and other), used in my function. When i analyze old code, i have seen this situation with "null", "false", "true" words :)

New function work much faster, but not as much as I would like :(
This code https://gist.github.com/libliflin/ea90fdf001124d5e4fe0715ad5ce64a5 with 1000 passes
have execution time with old parsing function ~15.5 seconds,
new parsing function ~13,5 seconds.

I'm try loop with use only one function next_char (read clob char by char) for json from link. It has executed ~3,5 seconds.

I think, to significantly increase the speed of parsing in Pl/SQL will not succeed.

**Comment by dsnz** [comment]
replaced by #105
