### ISSUE TITLE
Base64 decoding problem

### ISSUE THREAD

**Issue by lolekthegreat** [pljson/pljson#64]
Hi,
files over 32K were not decoded properly.
I've attached corrected version of json_ext object.
[json_ext.zip](https://github.com/pljson/pljson/files/360988/json_ext.zip)

Thanks for your good work.
Aleš

**Comment by jsumners** [comment]
Would you be so kind as to submit your changes in a pull request, please?

**Comment by lolekthegreat** [comment]
Sorry, but I didn't pull your project through git. I've made and test my
changes directly in database (we still use CVS for our version control of
database objects).
Will do as soon i have time to do that.

Thanks, Aleš

2016-07-13 14:24 GMT+02:00 James Sumners <notifications@github.com>:
