### ISSUE TITLE
- character is not supported in path_put operation

### ISSUE THREAD

**Issue by tomvanderduin** [pljson/pljson#67]
currently, you can't create keys using json.path_put, that containts a -

```
declare
  lv_json json := json();
begin
  lv_json.put('test','test value');
  lv_json.path_put('testKeyWithMinus.sub-key','test value2');
  lv_json.print;
end;
/
ORA-20110: JSON Path parse error: expected . or [ found - at position 22
ORA-06512: at "PLJSON.JSON_EXT", line 141
ORA-06512: at "PLJSON.JSON_EXT", line 282
ORA-06512: at "PLJSON.JSON_EXT", line 411
ORA-06512: at "PLJSON.JSON", line 308
ORA-06512: at line 5
```

in json_ext, there are a couple of places where a regexp is used like `regexp_like(buf, '^[[:alnum:]\_ ]+', 'c')`, I think a - has to be added to that pattern: `regexp_like(buf, '^[[:alnum:]-\_ ]+', 'c')`

**Comment by dsnz** [comment]
Please see issue #55 and try using array notation ie.

 lv_json.path_put('["testKeyWithMinus.sub-key"]','test value2');

(I'm on vacation and cannot test unfortunately)

**Comment by jsumners** [comment]
@tomvanderduin I am closing this issue since I believe @dsnz has accurately answered your question. If not, feel free to re-open with more information.
