### ISSUE TITLE
BD for consumption Clob

### ISSUE THREAD

**Issue by ARCHAMO** [pljson/pljson#68]
Good afternoon.

I am using this great library and so far everything perfect. Complete and easy to use, but I have a question at the level of resource utilization database.

From the JAVA layer where I created my services Restful, I invoke stored procedures in oracle which have as input and output parameter of type CLOB.

The question is how is the memory consumption or pagination of those CLOB that they would be instantiated whenever incoco my stored procedures.

**Comment by jsumners** [comment]
That would be subject to the amount of data you're storing.

**Comment by ARCHAMO** [comment]
As handles the pagination of the CLOB fields. My scenario is that on a normal day 60 users can consume the service that invokes the procedure BD, and what I want is to make sure my BD is not saturated or fall.

Thanks.

**Comment by jsumners** [comment]
I don't understand what you want us to do. That's completely dependent upon your environment and data. You'll have to do your own testing and make your own determination.

**Comment by boriborm** [comment]
I wrote myself web server on Java (use Netty). It translate json requests from client (Ext JS Framework) to database procedures with clob parameters.

Example of one procedure

```sql
procedure get_clients(filter in clob, clobResult in out nocopy clob, usr_login in varchar2)
    is
      jIn json:=json(filter);
      jOut json;
begin
    ...
    jOut:=json('{success:true, data:[], results:0}');
    jOut.to_clob(clobResult);
end;
```

GET url for request
http://server/json/scheme.package.get_clients?p1=1&p2=2

Currently with service work 22 people (22 opened sessions) and it is not highest load.
Each session can create more than one ajax request at once. 
Length of responses not big, more often less than 5-10kBytes.

This database is master and used primarily for banking information system. With BIS work more then 350 people.

All work fine.

**Comment by Pazus** [comment]
I have a DB based web server through mod_plsql accepting clob json and responding with json also. Implementation is based on 1.0.0 version of pljson (yes, we should update!)

We have dozens of requests every seconds with thousands of users and company clients.

In a single case we have a performance problems when construction large json and creating clob from it (300+ KB), but the rest is fine. Shortly we'll recompile it with optimization level 3 and native compilation and take a look at the performance change.

**Comment by ARCHAMO** [comment]
Thanks for your answers. I am helping me a lot for my analysis. But my concern goes is part of Web services, but the pagination level database that is done by using type parameters and variables json (CLOB) of plsql.
Given that you can have more than 200 requests for services consuming java stored procedures with json and CLOB, that risk would have to saturate my BD.

**Comment by jsumners** [comment]
@ARCHAMO I am closing this since I believe we have answered your question. If not, feel free to re-open it with more information.
