### ISSUE TITLE
UTF-8 and Unicode Support.

### ISSUE THREAD

**Issue by databasesystems** [pljson/pljson#7]
Does this library give any unicode support.  I just can't get json_list to return anything else apart from Latin Character Set. Thanks!

**Comment by jsumners** [comment]
What character set is your database configured for? The actual backing data type for PL/JSON is the ANYDATA type (http://oracle-base.com/articles/misc/anydata.php). When you use `to_char` on a PL/JSON type then the data is converted to VARCHAR2.

**Comment by databasesystems** [comment]
Hi J Sumners

Thank you for your prompt reply, I appreciate it. I am using Oracle Apex doing a REST API call and then loading the response to form PLJSON to a JSON_LIST structure. The database character set is AL32UTF8

Many thanks

Kubilay

**Comment by jsumners** [comment]
I am unable to assist with Apex. I have never used it, and I don't know how it will integrate with PL/JSON. It's likely that your character corruption is happening prior to storing the data in a PL/JSON type.

This bug report seems to be more of a usage question than an actual but, so I'm closing it. Please use StackOverflow for questions. Also, see this SO question for more information on the same sort of problem -- http://stackoverflow.com/questions/27370260/does-pl-json-software-support-utf-8-characters
