### ISSUE TITLE
description for: major overhaul to support binary_double and issue #70 fix

### ISSUE THREAD

**Issue by dsnz** [pljson/pljson#78]
**Summary**

this commit was inspired by issue #70 and the need to support floating point double numbers as is usually expected for json ie.

- positive numbers in the range ~  2.2 e-308 ..  1.8 e+308 with up to 15 significant digits
- negative numbers in the range ~ -2.2 e-308 .. -1.8 e+308 with up to 15 significant digits

and which are equivalent to the Oracle type **BINARY_DOUBLE**

when originally the support was only for the Oracle type **NUMBER** ie.

- positive numbers in the range  1 e-130 to  9.99...9 e+125 with up to 38 significant digits
- negative numbers in the range -1 e-130 to -9.99...9 e+125 with up to 38 significant digits

none of these types (NUMBER and BINARY_DOUBLE) is a proper subtype of the other so internally both number representations are stored

there is code in parsing and toString of json numbers that detects which type is best representation (or can be both types too)
the user can use **get_number()** as in the past that will return the Oracle NUMBER representation
there is a new **get_double()** that will return the BINARY_DOUBLE representation
if the user is unsure which one to use, the new boolean functions

**is_number_repr_number()** and
**is_number_repr_double()**

return true if the respective representation matches best the json number

extra notes
- if the number is infinity (e.g. 1.23456789 e999) then it's character representation will be 1e309 or -1e309
- if the number is very small and not representable really (e.g. 1.23456789 e-999) then it becomes 0 (zero)
- in both above cases (infinity or very small numbers) the number is considered to be representable by both types (new functions **is_number_repr_number()** and **is_number_double()** will return true as both types can represent zero and infinity)
- if the user builds a json document on the fly and
  - uses the constructor with 'number' argument then the 'number' representation is considered to be correct; the 'binary_double' representation will be correct if it can represent the same number too (which may not be possible since floating point cannot represent most decimal numbers)
  - uses the constructor with 'binary_double' argument then the 'binary_double' representation is considered to be correct; the 'number' representation will be correct if it can represent the same number too

**Commit content**

**pljson value** added internal extra attributes to support binary_double,
changed (internally) the *constructor function pljson_value(num number) return self*
and added new overloads and new functions/procedures

  *constructor function pljson_value(num_double binary_double) return self*
  *member function get_double return binary_double*

  *member function is_number_repr_number return boolean* -- true if representable by 'number'
  *member function is_number_repr_double return boolean* -- true if representable by 'binary_double'

  -- set value for number from string representation; to replace to_number in pljson_parser
  -- can automatically decide and use binary_double if needed
  -- less confusing than new constructor with dummy argument for overloading
  -- centralized parse_number to use everywhere else and replace code in pljson_parser
  *member procedure parse_number(str varchar2)*
  
  -- centralized toString to use everywhere else and replace code in pljson_printer
  *member function number_toString return varchar2*

**pljson** added new overloads with 'binary_double'

  *member procedure put(self in out nocopy pljson, pair_name varchar2, pair_value binary_double, position pls_integer default null)*
  *member procedure path_put(self in out nocopy pljson, json_path varchar2, elem binary_double, base number default 1)*

**pljson_list** added new overloads with 'binary_double'

  *member procedure append(self in out nocopy pljson_list, elem binary_double, position pls_integer default null)*
  *member procedure replace(self in out nocopy pljson_list, position pls_integer, elem binary_double)*
  *member procedure path_put(self in out nocopy pljson_list, json_path varchar2, elem binary_double, base number default 1)*

**pljson_parser** changed internally to use *pljson_value.parse_number()* for numbers

**pljson_printer** changed internally to use *pljson_value.number_toString()* for numbers

**pljson_ext** changed internally *function is_integer(v pljson_value) return boolean* and added new overloads

  *function get_double(obj pljson, path varchar2, base number default 1) return binary_double*
  *procedure put(obj in out nocopy pljson, path varchar2, elem binary_double, base number default 1)*

**pljson_helper** added new overloads

  *function equals(p_v1 pljson_value, p_v2 binary_double) return boolean*
  *function contains(p_v1 pljson, p_v2 binary_double, exact boolean default false) return boolean*
  *function contains(p_v1 pljson_list, p_v2 binary_double, exact boolean default false) return boolean*

**pljson_ac** added new overloads

  *procedure object_put(p_self in out nocopy pljson, pair_name varchar2, pair_value binary_double, position pls_integer default null)*
  *procedure object_path_put(p_self in out nocopy pljson, json_path varchar2, elem binary_double, base number default 1)*
  *procedure array_append(p_self in out nocopy pljson_list, elem binary_double, position pls_integer default null)*
  *procedure array_replace(p_self in out nocopy pljson_list, position pls_integer, elem binary_double)*
  *procedure array_path_put(p_self in out nocopy pljson_list, json_path varchar2, elem binary_double, base number default 1)*
  *function jv_get_double(p_self in pljson_value) return binary_double*

Finally there are

- updated test suite with many new tests (and a minor extra printout of test running)
- minor renames of a few install files to reflect real package/type name installed

**Comment by jsumners** [comment]
For reference, the work discussed is in commit https://github.com/pljson/pljson/commit/20022b5bdad742690226d3b73a8d244d67cfc85c

@dsnz amazing work. Thank you so much for all of your effort.
