### ISSUE TITLE
Removing a node from an array is not working

### ISSUE THREAD

**Issue by LeonardGC** [pljson/pljson#79]
The following example will clarify it a bit:
```
declare 
  mJson json;
begin
  mJson := json('{"item":[{"id":1,"text":"Test"},{"id":2,"text":"Sample"}]}');
  -- Try removing all the 'id' nodes
  json_ext.remove (obj  => mJson,
                   path => 'item.id');
  
  Dbms_Output.put_line (mJson.to_char);
end;
```
If you run this you will notice that nothing has changed.
Is this "as designed" or a bug?

**Comment by jsumners** [comment]
That path isn't going to work. You will have to loop through the object to remove items. Notice that the following works:

```sql
declare 
  mJson pljson;
  foo pljson;
begin
  mJson := pljson('{"item":[{"id":1,"text":"Test"},{"id":2,"text":"Sample"}]}');
  foo := pljson_ext.get_json(mJson, 'item[1]');
  dbms_output.put_line('item 1: ' || foo.to_char);
  dbms_output.put_line('---------------------------');
  -- Try removing all the 'Id' nodes
  pljson_ext.remove (mJson, 'item[1]');
  
  Dbms_Output.put_line (mJson.to_char);
end;
```

**Comment by dsnz** [comment]
pljson does not support JsonPath  (http://goessner.net/articles/JsonPath/)
because it is not standard and has no formal syntax
though I guess we could consider the possibility to implement in the future
at least **$**, **\***, and **number ranges**
which features are also the the only extra ones supported by Oracle's JSON_QUERY()

at this moment you can use the following loop

```
declare 
  mJson json;
  x pls_integer;
begin
  mJson := json('{"item":[{"id":1,"text":"Test"},{"id":2,"text":"Sample"}]}');
  x := 1;
  while True loop
    if (json_ext.get_json_value(mJson, 'item['||x||']') is null) then
      exit;
    end if;
    json_ext.remove (obj  => mJson,
                 path => 'item['||x||'].id');
    x := x + 1;
  end loop;
  Dbms_Output.put_line (mJson.to_char);
end;
```

**Comment by jsumners** [comment]
@dsnz actually, we support a variation of it. The summary is nicely sectioned out in my `pldoc` branch -- https://github.com/pljson/pljson/blob/pldoc/site_src/pages/json_path.html . Basically, we support enough of it to make accessing objects/arrays similar to actual JavaScript accessors.

**Comment by LeonardGC** [comment]
> That path isn't going to work. You will have to loop through the object to remove items.
Thanks for that, but I knew it already that I could do this.
But to answer the question myself: "as designed"?

**Comment by LeonardGC** [comment]
Hi all,

Thanks for the code samples and the links, I learned a lot today. 
Looking forward to the implementation of this feature, though. As of now, I'll use the current functionality.

**Comment by jsumners** [comment]
I believe you misunderstand, @LeonardGC. The JsonPath support currently implemented is all that is planned to be implemented.

I am closing this because it seems like your question is answered.
