### ISSUE TITLE
 Minisculas in the Keys of the Json

### ISSUE THREAD

**Issue by ARCHAMO** [pljson/pljson#81]
Good afternoon. I am using the json_dyn.executeList package but I notice that the names of the key or names of the fields of the bd always come in UPPERCASE, as it could do so that they arrive in LOWERCASE. Thank you

**Comment by dsnz** [comment]
Hello,

It is standard that Oracle column names are in uppercase;
they are stored internally in uppercase (unless you quote them with " ") and also all Oracle database tools show them in uppercase too.
Pljson just returns the column names that Oracle uses internally.
