### ISSUE TITLE
Oracle 12.2 introduced several new keyword which conflict with object name of PLJSON

### ISSUE THREAD

**Issue by RetainCountZero** [pljson/pljson#83]
When running install.sql on an Oracle 12.2.0.1 database, several PLS-00103 errors are raised.  It looks like the reason can be tracked to these changes:

https://docs.oracle.com/database/122/ADJSN/changes.htm#GUID-9C3C5E0A-9895-4F93-9997-E24AA9DF2635

> SQL/JSON functions json_value, json_query, json_object, and json_array, as well
> as SQL/JSON condition json_exists, have been added to the PL/SQL language as 
> built-in functions (json_exists is a Boolean function in PL/SQL).

A simple workaround would be something like renaming all instances of the symbols in PLJSON which conflict with the Oracle internal symbols.

**Comment by jsumners** [comment]
We are working (very slowly) on a new release. It's available via our `develop` branch -- https://github.com/pljson/pljson/tree/develop . You shouldn't have any issues with it; the main blocker is a documentation revamp. In the new release everything is `pljson_*` instead of `json_*`.

**Comment by RetainCountZero** [comment]
Thanks for the fast reply.  I'll close the issue and have a look at the develop branch.
