### ISSUE TITLE
Display of special characters

### ISSUE THREAD

**Issue by ARCHAMO** [pljson/pljson#86]
Good afternoon, as I can so that the Ñ and the vowels checked appear correctly. They are not interpreted.

Thank you

**Comment by jsumners** [comment]
Are you using UTF-8 encoding? Are you using the `develop` branch of this project?

**Comment by ARCHAMO** [comment]
This is the configuration of my DB.
But I can not modify those parameters. What option do I have to set the value at the time of executing the query with json_dyn.executeList(va_vcQuery);

![image](https://user-images.githubusercontent.com/12633358/28088915-df6410f6-664c-11e7-9bd9-660cb9f90d21.png)

**Comment by jsumners** [comment]
I'm sorry. I don't understand what your issue is.

**Comment by ARCHAMO** [comment]
I will try to explain to you step by step.
1. I create this test test in my database.
![image](https://user-images.githubusercontent.com/12633358/28093173-c6089136-665b-11e7-8096-53d4a4e0b75c.png)

2. What is in red is the query that I want to convert to JSON.
3. What is yellow in the execution of the query.
4. If the query is executed normally it returns this result to me correctly.
![image](https://user-images.githubusercontent.com/12633358/28093297-48c74252-665c-11e7-88c9-e45363f5fcb8.png)
5. When I run json_dyn.executeList (va_vcQuery) on the test the result is the following.
![image](https://user-images.githubusercontent.com/12633358/28093366-9456a9ba-665c-11e7-81d4-fc3488ee1a1e.png)


What I need is for the special character Ñ to be displayed correctly.

**Comment by jsumners** [comment]
That result is correct. That is the escaped form of 'ñ'. The program that reads the JSON should recognize it and act accordingly.

**Comment by dsnz** [comment]
Hello,

James is correct in that the output is okay, but of course you expected to see unicode in the result string which is valid too. In fact there is an option for this but is a compile time one and not runtime one.

Specifically in package **pljson_printer** and at line 24, change

  ascii_output boolean    not null := true;

to

  ascii_output boolean    not null := false;
